### ISSUE TITLE
Syncing items fails when backend is a SMB mount point

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#10855]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The owncloud instance running 10.11 in combination of the desktop app 3.2, and all version before never had syncing issues, a recent upgrade to desktop 4.0 did not changed the following behaviour.

**Problem:**

Having some SMB and Google Drive mount points and post upgrading to server 10.12.0 respectively 10.12.1, syncing data fails in the following conditions, but ONLY when using SMB, works flawless with GD.

Files can be located in any folder/subfolder representing the synced SMB mountpoint:

In these conditions the issue appears:

* Adding a new file via the local filesystem.
* Editing an existing file like with Excel.
* Overwriting an **existing** file via the browser.
Note that the file gets fully accepted by the backend and can be downloaded manually without any issue, but fails syncing.

When the file is NOT present in the local sync folder, you can upload it via browser and it gets synced. It is the available locally as usual

This shows up like a sync issue from the client to the server but not vice versa.

This is the SMB mount point:
![image](https://github.com/owncloud/client/assets/3321281/c963a145-d2eb-4766-9750-5c794619b302)

### Expected behavior

Files should sync to SMB mount points as before

### Steps to reproduce the issue

See the description in the bug

### Logs

Right click on files that failed syncing:

Locally present but should get overwritten by the server (file update via browser)
```
Issues         ,File                                                            ,Folder                        ,Size  ,Account             ,Time                ,Status              ,
The downloaded file does not match the checksum, it will be resumed. '374e32ad842ed171ac51af672724887cea3a0c2f' != '98d3eb8c44e936c7d7110c09b4464a91e2c7cfae' (skipped due to earlier error, trying again in 21 second(s)),martin@filer/Dokumente/Firma/Buchhaltung/2023/2023 Abgaben Bewegungen.xlsx,ownCloud\diemattels.at        ,      ,mmattel@owncloud.diemattels.at,2023-05-18T10:06:07.845,Blacklisted         ,
```
Newly added local file
```
Issues         ,File                                                            ,Folder                        ,Size  ,Account             ,Time                ,Status              ,
Server replied "400 Bad Request" to "PUT https://owncloud.diemattels.at/remote.php/dav/files/mmattel/martin@filer/desktop_client_test.txt" (The computed checksum does not match the one received from the client.),martin@filer/desktop_client_test.txt                            ,ownCloud\diemattels.at        ,0 B   ,mmattel@owncloud.diemattels.at,2023-05-18T10:13:36.000,Error               ,
```

Log for newly added local file
```
23-05-18 10:24:51:311 [ info sync.propagator ]:	Starting SyncInstruction(CSYNC_INSTRUCTION_IGNORE) propagation of "martin@filer/desktop_client_test.txt" by OCC::PropagateIgnoreJob(0x2ea7a0d3fb0)
23-05-18 10:24:51:312 [ warning sync.propagator ]:	Could not complete propagation of "martin@filer/desktop_client_test.txt" by OCC::PropagateIgnoreJob(0x2ea7a0d3fb0) with status OCC::SyncFileItem::BlacklistedError and error: "Server replied \"400 Bad Request\" to \"PUT https://owncloud.diemattels.at/remote.php/dav/files/mmattel/martin@filer/desktop_client_test.txt\" (The computed checksum does not match the one received from the client.) (skipped due to earlier error, trying again in 10 minute(s))"
23-05-18 10:24:51:312 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "martin@filer/desktop_client_test.txt" OCC::SyncFileItem::BlacklistedError SyncInstruction(CSYNC_INSTRUCTION_IGNORE)
23-05-18 10:24:51:312 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:IGNORE:C:\\Users\\marti\\ownCloud\\diemattels.at\\martin@filer" to QLocalSocket(0x2ea74a11a80)
23-05-18 10:24:51:312 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:ERROR:C:\\Users\\marti\\ownCloud\\diemattels.at\\martin@filer\\desktop_client_test.txt" to QLocalSocket(0x2ea74a11a80)
23-05-18 10:24:51:312 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::slotItemCompleted ]:	inserted error item "martin@filer/desktop_client_test.txt"
```

### Client version number

**Client:**
* Windows x64
* 4.0.0.10896
* QT 5.15.8
* NO virtual files

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

**Server:**
* Ubuntu 20.04
* mariadb
* php7.4
* Version 10.12.1

### Additional context

The interesting thing is, that it was challenging to identify that this is a checksum issue because the client tells that the file is blacklisted. As the server has a blacklisting configuration possibility too, this was confusing. Note that there is NO server blacklisting configured!

**Comment by mmattel** [comment]
Here is the log entry from the server:

```
Exception: HTTP\/1.1 400 The computed checksum does not match the one received from the client.: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"The computed checksum does not match the one received from the client.\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(172): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put()\\
n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\
n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\
n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\
n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\
n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\
n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\
n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\
n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/w...')\\
n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":219}

\/remote.php\/dav\/files\/user-x\/martin@filer\/desktop_client_test.txt
```

**Comment by mmattel** [comment]
Update, it seems that other users of my instance have issues with the same problem on Google Drive too. Means that this is likely a generic problem and not related to a mount point type.

**Comment by jnweiger** [comment]
@IljaN hoijoijoi a new checksum error that was introduced in 10.12.1 ??
