### ISSUE TITLE
Client crash in `startSync()` at `folder.cpp:929` (during GUI tests run)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11199]
### Describe the bug

```cpp
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1003a15844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f100033bf00 (LWP 431))]
#0  0x00007f1003a15844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f10039c4abe in raise () at /lib64/libc.so.6
#2  0x00007f10039ad90f in abort () at /lib64/libc.so.6
#3  0x00007f1003f910eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f1003f91b7f in  () at /lib64/libQt6Core.so.6
#5  0x00000000004c7720 in __OC_ENSURE(bool, char const*, char const*, int, char const*) (condition=false, cond=0x68a610 "canSync()", file=0x68142f "/drone/src/src/gui/folder.cpp", line=929, info=0x681ed0 "void OCC::Folder::startSync()") at /drone/src/src/common/asserts.h:43
#6  0x00000000004e4dbb in OCC::Folder::startSync() (this=0x2496520) at /drone/src/src/gui/folder.cpp:929
        fullLocalDiscoveryInterval = std::chrono::duration = { 28956816ms }
        hasDoneFullLocalDiscovery = false
        periodicFullLocalDiscoveryNow = false
#7  0x00000000005f4b1a in OCC::SyncScheduler::startNext() (this=0x1541a70) at /drone/src/src/gui/scheduling/syncscheduler.cpp:158
        nextSync = {wp = {d = 0x2945b90, value = 0x2496520}}
```

### Logs

<details>
<summary>Full stacktrace</summary>

```bash
<<<<< STACKTRACE START >>>>>
[New LWP 431]
[New LWP 453]
[New LWP 452]
[New LWP 450]
[New LWP 435]
[New LWP 445]
[New LWP 434]
[New LWP 433]
[New LWP 461]
[New LWP 451]
[New LWP 454]
[New LWP 446]
[New LWP 458]
[New LWP 459]
[New LWP 456]
[New LWP 465]
[New LWP 463]
[New LWP 444]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /t'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1003a15844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f100033bf00 (LWP 431))]
#0  0x00007f1003a15844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f10039c4abe in raise () at /lib64/libc.so.6
#2  0x00007f10039ad90f in abort () at /lib64/libc.so.6
#3  0x00007f1003f910eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f1003f91b7f in  () at /lib64/libQt6Core.so.6
#5  0x00000000004c7720 in __OC_ENSURE(bool, char const*, char const*, int, char const*) (condition=false, cond=0x68a610 "canSync()", file=0x68142f "/drone/src/src/gui/folder.cpp", line=929, info=0x681ed0 "void OCC::Folder::startSync()") at /drone/src/src/common/asserts.h:43
#6  0x00000000004e4dbb in OCC::Folder::startSync() (this=0x2496520) at /drone/src/src/gui/folder.cpp:929
        fullLocalDiscoveryInterval = std::chrono::duration = { 28956816ms }
        hasDoneFullLocalDiscovery = false
        periodicFullLocalDiscoveryNow = false
#7  0x00000000005f4b1a in OCC::SyncScheduler::startNext() (this=0x1541a70) at /drone/src/src/gui/scheduling/syncscheduler.cpp:158
        nextSync = {wp = {d = 0x2945b90, value = 0x2496520}}
#8  0x00000000005f52ea in OCC::SyncScheduler::startNext()::$_0::operator()(OCC::SyncResult const&) const (this=0x23a4860, result=...) at /drone/src/src/gui/scheduling/syncscheduler.cpp:154
#9  0x00000000005f519e in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<OCC::SyncResult const&>, void, OCC::SyncScheduler::startNext()::$_0>::call(OCC::SyncScheduler::startNext()::$_0&, void**) (f=..., arg=0x7ffd768d4230) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:127
#10 0x00000000005f5161 in QtPrivate::Functor<OCC::SyncScheduler::startNext()::$_0, 1>::call<QtPrivate::List<OCC::SyncResult const&>, void>(OCC::SyncScheduler::startNext()::$_0&, void*, void**) (f=..., arg=0x7ffd768d4230) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:241
#11 0x00000000005f5101 in QtPrivate::QFunctorSlotObject<OCC::SyncScheduler::startNext()::$_0, 1, QtPrivate::List<OCC::SyncResult const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x23a4850, r=0x1541a70, a=0x7ffd768d4230, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:408
#12 0x00007f1004095864 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#13 0x00000000004601a6 in OCC::Folder::syncFinished(OCC::SyncResult const&) (this=0x14a0d60, _t1=...) at src/gui/owncloudCore_autogen/EWIEGA46WW/moc_folder.cpp:553
        _a = {0x0, 0x14a0e48}
#14 0x00000000004e8c02 in OCC::Folder::slotSyncFinished(bool)::$_0::operator()() const (this=0x221b2a0) at /drone/src/src/gui/folder.cpp:1075
#15 0x00000000004e8ba6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::Folder::slotSyncFinished(bool)::$_0>::call(OCC::Folder::slotSyncFinished(bool)::$_0&, void**) (f=..., arg=0x293fa18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:127
#16 0x00000000004e8b71 in QtPrivate::Functor<OCC::Folder::slotSyncFinished(bool)::$_0, 0>::call<QtPrivate::List<>, void>(OCC::Folder::slotSyncFinished(bool)::$_0&, void*, void**) (f=..., arg=0x293fa18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:241
#17 0x00000000004e8b11 in QtPrivate::QFunctorSlotObject<OCC::Folder::slotSyncFinished(bool)::$_0, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x221b290, r=0x14a0d60, a=0x293fa18, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:408
#18 0x00007f1004087767 in QObject::event(QEvent*) () at /lib64/libQt6Core.so.6
#19 0x00007f1005370698 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#20 0x00007f1004034018 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#21 0x00007f100403b7a5 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt6Core.so.6
#22 0x00007f1004304bbf in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#23 0x00007f100359d48c in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#24 0x00007f10035fb648 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#25 0x00007f100359ab13 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#26 0x00007f100430445f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#27 0x00007f1004034135 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () at /lib64/libQt6Core.so.6
#28 0x00007f0ffe29685b in Squish::Hook::notifyApplicationExit() () at /home/headless/squish/lib/libsquishhook.so
#29 0x00007f0ffed87a89 in write_event_queue () at /home/headless/squish/lib/libsquishqtwrapper.so
#30 0x00007f0ffed8b5de in Squish::QtWrapper::Application::exitAUT(int) () at /home/headless/squish/lib/libsquishqtwrapper.so
#31 0x00007f0ffe2891fc in Squish::Hook::kill() () at /home/headless/squish/lib/libsquishhook.so
#32 0x00007f0ffe297166 in Squish::Hook::handleSend(unsigned int, QString const&, Squish::ArgumentList const&) () at /home/headless/squish/lib/libsquishhook.so
#33 0x00007f0ffe34be74 in Squish::AsyncIPC::IncomingSend::finalize(QDataStream&) () at /home/headless/squish/lib/libsquishhook.so
#34 0x00007f0ffe349561 in Squish::AsyncIPC::onMessageArrived(QByteArray) () at /home/headless/squish/lib/libsquishhook.so
#35 0x00007f0ffe365b41 in Squish::AsyncIPC::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at /home/headless/squish/lib/libsquishhook.so
#36 0x00007f1004095df8 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#37 0x00007f0ffe3663b2 in Squish::AsyncMessageChannel::messageArrived(QByteArray) () at /home/headless/squish/lib/libsquishhook.so
#38 0x00007f0ffe350f63 in Squish::TCPMessageChannel::processSingleMessage(QByteArray*) () at /home/headless/squish/lib/libsquishhook.so
#39 0x00007f0ffe3525a1 in Squish::TCPMessageChannel::dispatchMessages(bool) () at /home/headless/squish/lib/libsquishhook.so
#40 0x00007f1004095df8 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#41 0x00007f10040a4bc5 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () at /lib64/libQt6Core.so.6
#42 0x00007f10040a53a5 in QSocketNotifier::event(QEvent*) () at /lib64/libQt6Core.so.6
#43 0x00007f1005370698 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#44 0x00007f1004034018 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#45 0x00007f100430547c in socketNotifierSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#46 0x00007f100359d48c in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#47 0x00007f10035fb648 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#48 0x00007f100359ab13 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#49 0x00007f100430445f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#50 0x00007f100404112b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#51 0x00007f100403c8fd in QCoreApplication::exec() () at /lib64/libQt6Core.so.6
#52 0x00000000004515aa in main(int, char**) (argc=8, argv=0x7ffd768d59a8) at /drone/src/src/gui/main.cpp:437
        resource = {<No data fields>}
        platform = std::unique_ptr<OCC::Platform> = {get() = 0x141ab00}
        app = <incomplete type>
        options = {show = true, quitInstance = false, logDir = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}, logFile = {d = {d = 0x153b960, ptr = 0x153b970 u"-", size = 1}, static _empty = 0 u'\000'}, logFlush = true, logDebug = true, debugMode = false, userEnforcedLanguage = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}, fileToOpen = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}}
        singleApplication = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f10044f8460 <QObject::staticMetaObject>}, stringdata = 0x7f1005fd1240 <(anonymous namespace)::qt_meta_stringdata_KDSingleApplication>, data = 0x7f1005fd1160 <qt_meta_data_KDSingleApplication>, static_metacall = 0x7f1005fcccc0 <KDSingleApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, metaTypes = 0x7f1005fd3b20 <qt_incomplete_metaTypeArray<(anonymous namespace)::qt_meta_stringdata_KDSingleApplication_t, QtPrivate::TypeAndForceComplete<QString, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<KDSingleApplication, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<void, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<int, std::integral_constant<bool, false> > >>, extradata = 0x0}}, d_ptr = std::unique_ptr<KDSingleApplicationPrivate> = {get() = 0x153e050}}
        folderManager = std::unique_ptr<OCC::FolderMan> = {get() = 0x153b7f0}
        ocApp = std::unique_ptr<OCC::Application> = {get() = 0x1540930}

<<<<< STACKTRACE END >>>>>
```
</details>

[client-log.log](https://github.com/owncloud/client/files/12572104/client-log.log)

**Comment by saw-jan** [comment]
Frequency:
https://drone.owncloud.com/owncloud/client/16562
https://drone.owncloud.com/owncloud/client/16565
https://drone.owncloud.com/owncloud/client/16570
https://drone.owncloud.com/owncloud/client/16577

**Comment by HanaGemela** [comment]
Crash is hard to reproduce. We let the CI (mainly nightlies) run and then check if the crash occurs there. Will be reopened if needed, moving to Done now

**Comment by saw-jan** [comment]
Haven't seen it recently
