### ISSUE TITLE
Client crash in AbstractNetworkJob at `abstractnetworkjob.cpp:296` (during GUI tests run)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11203]
### Describe the bug

```c
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /t'.
Program terminated with signal SIGILL, Illegal instruction.
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob (this=0x7f498006bb90) at /drone/src/src/libsync/abstractnetworkjob.cpp:296
296	{
[Current thread is 1 (Thread 0x7f49c9082f00 (LWP 4232))]
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob() (this=0x7f498006bb90) at /drone/src/src/libsync/abstractnetworkjob.cpp:296
#1  0x00007f49ccde1003 in QObjectPrivate::deleteChildren() () at /lib64/libQt6Core.so.6
#2  0x00007f49ccde5428 in QObject::~QObject() () at /lib64/libQt6Core.so.6
```

### Logs
<details>
<summary>Full stacktrace</summary>

```c
[New LWP 4232]
[New LWP 4236]
[New LWP 4422]
[New LWP 4416]
[New LWP 4235]
[New LWP 4247]
[New LWP 4425]
[New LWP 4417]
[New LWP 4424]
[New LWP 4599]
[New LWP 4234]
[New LWP 4423]
[New LWP 4420]
[New LWP 4598]
[New LWP 4427]
[New LWP 4605]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /t'.
Program terminated with signal SIGILL, Illegal instruction.
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob (this=0x7f498006bb90) at /drone/src/src/libsync/abstractnetworkjob.cpp:296
296	{
[Current thread is 1 (Thread 0x7f49c9082f00 (LWP 4232))]
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob() (this=0x7f498006bb90) at /drone/src/src/libsync/abstractnetworkjob.cpp:296
#1  0x00007f49ccde1003 in QObjectPrivate::deleteChildren() () at /lib64/libQt6Core.so.6
#2  0x00007f49ccde5428 in QObject::~QObject() () at /lib64/libQt6Core.so.6
#3  0x00007f49ce7e3c04 in OCC::GraphApi::SpacesManager::~SpacesManager() (this=0x26d1a60) at src/libsync/libsync_autogen/IZJHD56IMP/../../../../../src/libsync/graphapi/spacesmanager.h:33
#4  0x00007f49ce7e3c29 in OCC::GraphApi::SpacesManager::~SpacesManager() (this=0x26d1a60) at src/libsync/libsync_autogen/IZJHD56IMP/../../../../../src/libsync/graphapi/spacesmanager.h:33
#5  0x00007f49ccde1003 in QObjectPrivate::deleteChildren() () at /lib64/libQt6Core.so.6
#6  0x00007f49ccde5428 in QObject::~QObject() () at /lib64/libQt6Core.so.6
#7  0x00007f49ce80c9d8 in OCC::Account::~Account() (this=0x2a85fd0) at /drone/src/src/libsync/account.cpp:89
#8  0x00007f49ce80c9f9 in OCC::Account::~Account() (this=0x2a85fd0) at /drone/src/src/libsync/account.cpp:88
#9  0x00007f49ce81305b in QtSharedPointer::CustomDeleter<OCC::Account, QtSharedPointer::NormalDeleter>::execute() (this=0x2929740) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:158
#10 0x00007f49ce812fa1 in QtSharedPointer::ExternalRefCountWithCustomDeleter<OCC::Account, QtSharedPointer::NormalDeleter>::deleter(QtSharedPointer::ExternalRefCountData*) (self=0x2929730) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:176
        realself = 0x2929730
#11 0x00007f49ce807686 in QtSharedPointer::ExternalRefCountData::destroy() (this=0x2929730) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:114
#12 0x00007f49ce80762a in QSharedPointer<OCC::Account>::deref(QtSharedPointer::ExternalRefCountData*) (dd=0x2929730) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:445
#13 0x00007f49ce8075e9 in QSharedPointer<OCC::Account>::deref() (this=0x7f498006bbb8) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:440
#14 0x00007f49ce8075c5 in QSharedPointer<OCC::Account>::~QSharedPointer() (this=0x7f498006bbb8) at /usr/include/qt6/QtCore/qsharedpointer_impl.h:280
#15 0x00007f49ce87a53d in OCC::AbstractNetworkJob::~AbstractNetworkJob() (this=0x7f498006bb90) at /drone/src/src/libsync/abstractnetworkjob.cpp:302
#16 0x00007f49ce880777 in OCC::SimpleNetworkJob::~SimpleNetworkJob() (this=0x7f498006bb90) at /drone/src/src/libsync/networkjobs.cpp:499
#17 0x00007f49ce925707 in OCC::JsonJob::~JsonJob() (this=0x7f498006bb90) at /drone/src/src/libsync/networkjobs/jsonjob.cpp:29
#18 0x00007f49ce931827 in OCC::GraphApi::Drives::~Drives() (this=0x7f498006bb90) at /drone/src/src/libsync/graphapi/jobs/drives.cpp:38
#19 0x00007f49ce931849 in OCC::GraphApi::Drives::~Drives() (this=0x7f498006bb90) at /drone/src/src/libsync/graphapi/jobs/drives.cpp:38
#20 0x00007f49ccdd9569 in QObject::event(QEvent*) () at /lib64/libQt6Core.so.6
#21 0x00007f49ce04d698 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#22 0x00007f49ccd86018 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#23 0x00007f49ccd8d7a5 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt6Core.so.6
#24 0x00007f49cd056bbf in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#25 0x00007f49cc2e648c in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007f49cc344648 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007f49cc2e3b13 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00007f49cd05645f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#29 0x00007f49ccd9312b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#30 0x00007f49ccd8e8fd in QCoreApplication::exec() () at /lib64/libQt6Core.so.6
#31 0x00000000004515de in main(int, char**) (argc=8, argv=0x7ffea976db18) at /drone/src/src/gui/main.cpp:444
        resource = {<No data fields>}
        platform = std::unique_ptr<OCC::Platform> = {get() = 0x15a0b00}
        app = <incomplete type>
        options = {show = true, quitInstance = false, logDir = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}, logFile = {d = {d = 0x16c1900, ptr = 0x16c1910 u"-", size = 1}, static _empty = 0 u'\000'}, logFlush = true, logDebug = true, debugMode = false, userEnforcedLanguage = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}, fileToOpen = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}}
        singleApplication = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f49cd24a460 <QObject::staticMetaObject>}, stringdata = 0x7f49ced18240 <(anonymous namespace)::qt_meta_stringdata_KDSingleApplication>, data = 0x7f49ced18160 <qt_meta_data_KDSingleApplication>, static_metacall = 0x7f49ced13cc0 <KDSingleApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, metaTypes = 0x7f49ced1ab20 <qt_incomplete_metaTypeArray<(anonymous namespace)::qt_meta_stringdata_KDSingleApplication_t, QtPrivate::TypeAndForceComplete<QString, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<KDSingleApplication, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<void, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<int, std::integral_constant<bool, false> > >>, extradata = 0x0}}, d_ptr = std::unique_ptr<KDSingleApplicationPrivate> = {get() = 0x16c4110}}
        folderManager = std::unique_ptr<OCC::FolderMan> = {get() = 0x16c1790}
        ocApp = std::unique_ptr<OCC::Application> = {get() = 0x16c6ad0}
```
</details>

[client-log.log](https://github.com/owncloud/client/files/12593557/client-log.log)

### Similar fix

https://github.com/owncloud/client/commit/0875e9fb3beb1bcd79bee2733cd07099bb71788e for crash below
```c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /t'.
Program terminated with signal SIGILL, Illegal instruction.
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob (this=0x7fab9801d770) at /drone/src/src/libsync/abstractnetworkjob.cpp:298
298	{
[Current thread is 1 (Thread 0x7fabe0aecf00 (LWP 4250))]
#0  OCC::AbstractNetworkJob::~AbstractNetworkJob() (this=0x7fab9801d770) at /drone/src/src/libsync/abstractnetworkjob.cpp:298
#1  0x00007fabe484b003 in QObjectPrivate::deleteChildren() () at /lib64/libQt6Core.so.6
#2  0x00007fabe484f428 in QObject::~QObject() () at /lib64/libQt6Core.so.6
```

**Comment by saw-jan** [comment]
Frequency:
https://drone.owncloud.com/owncloud/client/16577

**Comment by saw-jan** [comment]
haven't seen recently
