### ISSUE TITLE
[5]Client crash in OCC::Folder::slotWatchedPathsChanged at `src/gui/folder.cpp:698` (gui-test)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11330]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug
ci build: https://drone.owncloud.com/owncloud/client/16924

```c
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3e22cf1844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f3e1f617f00 (LWP 1925))]
#0  0x00007f3e22cf1844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f3e22ca0abe in raise () at /lib64/libc.so.6
#2  0x00007f3e22c8990f in abort () at /lib64/libc.so.6
#3  0x00007f3e2326d0eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f3e2326db7f in  () at /lib64/libQt6Core.so.6
#5  0x00007f3e2326d083 in qt_assert_x(char const*, char const*, char const*, int) () at /lib64/libQt6Core.so.6
#6  0x00000000004e79a1 in OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}::operator()(OCC::CheckSums::Algorithm, QByteArray const&) const (this=0x1acb1f0, checksum=...) at /drone/src/src/gui/folder.cpp:698
#7  0x00000000004e7774 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<OCC::CheckSums::Algorithm, QByteArray const&>, void, OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}>::call(OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}&, void**) (f=..., arg=0x7ffc40710b00) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:127
#8  0x00000000004e7731 in QtPrivate::Functor<OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}, 2>::call<QtPrivate::List<OCC::CheckSums::Algorithm, QByteArray const&>, void>(OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}&, void*, void**) (f=..., arg=0x7ffc40710b00) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:241
#9  0x00000000004e76c1 in QtPrivate::QFunctorSlotObject<OCC::Folder::slotWatchedPathsChanged(QSet<QString> const&, OCC::Folder::ChangeReason)::$_0::operator()() const::{lambda(OCC::CheckSums::Algorithm, QByteArray const&)#1}, 2, QtPrivate::List<OCC::CheckSums::Algorithm, QByteArray const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x1acb1e0, r=0xd7e970, a=0x7ffc40710b00, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:408
#10 0x00007f3e23371864 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
```
![Screenshot from 2023-11-06 09-37-45](https://github.com/owncloud/client/assets/52366632/85c99aa3-50e4-4199-8e08-939c2aa866cd)

### Logs

[stacktrace.log](https://github.com/owncloud/client/files/13246670/stacktrace.log)
[clientlog.log](https://github.com/owncloud/client/files/13246675/serverlog.log)

### Client version number

built from branch `5` - commit: https://github.com/owncloud/client/commit/3a5ffb5f702077cd3ae256ea9dacd42d66a5f0e8

### Server information
oC 10.13.2 - channel: stable

**Comment by TheOneRing** [comment]
```
01:59:04:119 AUT stdout: 23-11-03 01:59:04:118 [ warning default ]:	Spurious notification: "/tmp/client-bdd/Brian/FOLDER/simple.txt" false "c93ec18f8933a58970120ad90ae45ae939cf7632" "94e66df8cd09d410c62d9e0dc59d3a884e458e05" Inode: 7035168 7035168
01:59:04:119 AUT stdout: 23-11-03 01:59:04:118 [ fatal default ]:	ASSERT: "checksum == header.checksum()" in file /drone/src/src/gui/folder.cpp, line 712
```

A couple of month ago I introduced an assert that validates the checksum if the client think a change event was spurious. Apparently the situation can really happen, but it could also be the case that there was yet another change event...
