### ISSUE TITLE
Client crashed OCC::AccountSettings::addModalWidget at `accountsettings.cpp:839` (master branch - CI)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11515]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Build: https://drone.owncloud.com/owncloud/client/17699

```c
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0299833844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f029616df00 (LWP 2447))]
#0  0x00007f0299833844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f02997e2abe in raise () at /lib64/libc.so.6
#2  0x00007f02997cb90f in abort () at /lib64/libc.so.6
#3  0x00007f0299daf0eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f0299dafb7f in  () at /lib64/libQt6Core.so.6
#5  0x00007f0299daf083 in qt_assert_x(char const*, char const*, char const*, int) () at /lib64/libQt6Core.so.6
#6  0x00000000004be708 in OCC::AccountSettings::addModalWidget(QWidget*, OCC::AccountSettings::ModalWidgetSizePolicy) (this=0x178bcf0, widget=0x21795b0, sizePolicy=OCC::AccountSettings::ModalWidgetSizePolicy::Expanding) at /drone/src/src/gui/accountsettings.cpp:839
        outerWidget = 0x7f0290003190
        groupBox = 0x7f029001f4d0
#7  0x00000000005409cb in OCC::ownCloudGui::slotShowShareDialog(QString const&, QString const&, OCC::ShareDialogStartPage) (this=0x15bb3f0, sharePath=..., localPath=..., startPage=OCC::ShareDialogStartPage::UsersAndGroups) at /drone/src/src/gui/owncloudgui.cpp:1074
        accountState = {wp = {d = 0x1552060, value = 0x1550480}}
        w = 0x21795b0
        fileRecord = {_path = {d = {d = 0x21d0290, ptr = 0x21d02a0 "textfile0.txt", size = 13}, static _empty = 0 '\000'}, _inode = 6771861, _modtime = 1707614311, _type = CSyncEnums::ItemTypeFile, _etag = {d = {d = 0x22415c0, ptr = 0x22415d0 "bf386da7a93b1e38e40cc32df4a23df5", size = 32}, static _empty = 0 '\000'}, _fileId = {d = {d = 0x7f029000ce00, ptr = 0x7f029000ce10 "00000340ocafat6h1btj", size = 20}, static _empty = 0 '\000'}, _fileSize = 25, _remotePerm = {_value = 415, static notNullMask = 1}, _serverHasIgnoredFiles = false, _hasDirtyPlaceholder = false, _checksumHeader = {d = {d = 0x17ade80, ptr = 0x17ade90 "SHA1:2052377dec0724bda0d57aeab67fa819278b7f74", size = 45}, static _empty = 0 '\000'}}
        resharingAllowed = true
        maxSharingPermissions = {i = 31}
        file = {d = {d = 0x2171ec0, ptr = 0x2171ed0 u"textfile0.txt", size = 13}, static _empty = 0 u'\000'}
        folder = 0x1566c70
```

### Logs

[stacktrace.log](https://github.com/owncloud/client/files/14235189/stacktrace.4.log)
[clientlog.log](https://github.com/owncloud/client/files/14235193/serverlog.2.log)

### Client version number

built from git master

### Desktop environment (Linux only)

Linux

### Server information

10.13.4 - channel: stable

**Comment by saw-jan** [comment]
Similar crash: https://drone.owncloud.com/owncloud/client/17733

```c
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0af9f35844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f0af686cf00 (LWP 2982))]
#0  0x00007f0af9f35844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f0af9ee4abe in raise () at /lib64/libc.so.6
#2  0x00007f0af9ecd90f in abort () at /lib64/libc.so.6
#3  0x00007f0afa4b10eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f0afa4b1b7f in  () at /lib64/libQt6Core.so.6
#5  0x00007f0afa4b1083 in qt_assert_x(char const*, char const*, char const*, int) () at /lib64/libQt6Core.so.6
#6  0x00000000004bd288 in OCC::AccountSettings::addModalWidget(QWidget*, OCC::AccountSettings::ModalWidgetSizePolicy) (this=0x1f1a380, widget=0x28f3bc0, sizePolicy=OCC::AccountSettings::ModalWidgetSizePolicy::Expanding) at /drone/src/src/gui/accountsettings.cpp:780
        outerWidget = 0x298b300
        groupBox = 0x294c5b0
#7  0x000000000053bebb in OCC::ownCloudGui::slotShowShareDialog(QString const&, QString const&, OCC::ShareDialogStartPage) (this=0x1d4c8a0, sharePath=..., localPath=..., startPage=OCC::ShareDialogStartPage::UsersAndGroups) at /drone/src/src/gui/owncloudgui.cpp:1074
        accountState = {wp = {d = 0x1ce5050, value = 0x1ce33a0}}
        w = 0x28f3bc0
        fileRecord = {_path = {d = {d = 0x2f61cb0, ptr = 0x2f61cc0 "textfile0.txt", size = 13}, static _empty = 0 '\000'}, _inode = 5878253, _modtime = 1708045464, _type = CSyncEnums::ItemTypeFile, _etag = {d = {d = 0x29156d0, ptr = 0x29156e0 "b67fd99b8cf76d3110b7451ab88eb598", size = 32}, static _empty = 0 '\000'}, _fileId = {d = {d = 0x7f0af000b570, ptr = 0x7f0af000b580 "00000497ocnr7dl9mizh", size = 20}, static _empty = 0 '\000'}, _fileSize = 25, _remotePerm = {_value = 415, static notNullMask = 1}, _serverHasIgnoredFiles = false, _hasDirtyPlaceholder = false, _checksumHeader = {d = {d = 0x29cc7d0, ptr = 0x29cc7e0 "SHA1:2052377dec0724bda0d57aeab67fa819278b7f74", size = 45}, static _empty = 0 '\000'}}
        resharingAllowed = true
        maxSharingPermissions = {i = 31}
        file = {d = {d = 0x29c9e40, ptr = 0x29c9e50 u"textfile0.txt", size = 13}, static _empty = 0 u'\000'}
        folder = 0x1cf9bd0
```

**Comment by saw-jan** [comment]
Have not seen this crash for a long time. :+1:
