### ISSUE TITLE
CI: DatabaseErrorTest fails

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11784]
The test only fails in drone, the issue was probably introduced in https://github.com/owncloud/client/pull/11770

```
QDEBUG : TestDatabaseError::testDatabaseError(Vfs::Off) 24-08-02 10:00:00:947 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotAboutToPropagate ]:	Investigating "D" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_NEW

WARNING: TestDatabaseError::testDatabaseError(Vfs::Off) Maximum amount of warnings exceeded. Use -maxwarnings to override.

QFATAL : TestDatabaseError::testDatabaseError(Vfs::Off) 24-08-02 10:00:06:276 [ fatal default ]:	ENFORCE: "_state != Finished" in file /drone/src/src/libsync/owncloudpropagator.cpp, line 230 virtual void OCC::PropagateItemJob::done(SyncFileItem::Status, const QString &)

FAIL!  : TestDatabaseError::testDatabaseError(Vfs::Off) Received a fatal error.

   Loc: [/drone/src/src/libsync/owncloudpropagator.cpp(230)]

Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 5684ms

********* Finished testing of TestDatabaseError *********

Received signal 6 (SIGABRT)

         testDatabaseError function time: 5684ms, total time: 5684ms


      Start 28: LockedFilesTest

28/38 Test #28: LockedFilesTest ..................   Passed    0.19 sec

      Start 29: FolderMigrationTest

29/38 Test #29: FolderMigrationTest ..............   Passed    0.13 sec

      Start 30: FolderWatcherTest

30/38 Test #30: FolderWatcherTest ................   Passed  140.14 sec

      Start 31: InotifyWatcherTest

31/38 Test #31: InotifyWatcherTest ...............   Passed    0.05 sec

      Start 32: LongPathTest

32/38 Test #32: LongPathTest .....................   Passed    0.06 sec

      Start 33: FolderManTest

33/38 Test #33: FolderManTest ....................   Passed    0.11 sec

      Start 34: OAuthTest

34/38 Test #34: OAuthTest ........................   Passed    6.06 sec

      Start 35: JobQueueTest

35/38 Test #35: JobQueueTest .....................   Passed    0.14 sec

      Start 36: SpacesMigrationTest

36/38 Test #36: SpacesMigrationTest ..............   Passed    0.14 sec

      Start 37: ActivityModelTest

37/38 Test #37: ActivityModelTest ................   Passed    0.06 sec

      Start 38: ProtocolModelTest

38/38 Test #38: ProtocolModelTest ................   Passed    0.13 sec


97% tests passed, 1 tests failed out of 38


Total Test time (real) = 210.66 sec


The following tests FAILED:

	 27 - DatabaseErrorTest (Subprocess aborted)

Errors while running CTest
```
https://drone.owncloud.com/owncloud/client/18922/2/3

**Comment by TheOneRing** [comment]
I failed to reproduce the issue with craft builds

**Comment by saw-jan** [comment]
> I failed to reproduce the issue with craft builds

CI builds the client from the available system dependencies (doesn't use craft build). maybe that's the reason
https://drone.owncloud.com/owncloud/client/18929/1/2

**Comment by saw-jan** [comment]
Ctests can pass sometime: https://drone.owncloud.com/owncloud/client/18964/4/3

**Comment by saw-jan** [comment]
I tried to run ctests and found that the test fails starting from commit https://github.com/owncloud/client/commit/d4ae452a4d98167f0cc81286ee9638a1fc8ce166

**Comment by saw-jan** [comment]
For now, skipping the failing ctest so that GUI test PRs are unblocked.
Need to revert #11795 with the fix PR.

**Comment by erikjv** [comment]
Stack trace below. The interesting bit is where `PropfindJob::finished` (frame 25) manages to trigger `PropagateUploadFileCommon::done` (with status success) through `PropagateUploadFileCommon::finalize`.

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff48a48a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff48528ee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff483a8ff in __GI_abort () at abort.c:79
#4  0x00007ffff4e34523 in qAbort () at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/global/qglobal.cpp:161
#5  0x00007ffff4e79bf0 in qt_message_fatal<QString&> (message=..., context=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/global/qlogging.cpp:2003
#6  qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *) (msgType=msgType@entry=QtFatalMsg, context=<optimized out>, msg=<optimized out>, ap=ap@entry=0x7fffffffae70) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/global/qlogging.cpp:378
#7  0x00007ffff4e354b3 in QMessageLogger::fatal (this=<optimized out>, msg=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/global/qlogging.cpp:901
#8  0x00007ffff79cf2f0 in OCC::PropagateItemJob::done (this=0x682440, statusArg=OCC::SyncFileItem::Success, errorString=...) at /client/src/libsync/owncloudpropagator.cpp:230
#9  0x00007ffff79ffefd in OCC::PropagateUploadFileCommon::done (this=0x682440, status=OCC::SyncFileItem::Success, errorString=...) at /client/src/libsync/propagateupload.cpp:429
#10 0x00007ffff7a01c26 in OCC::PropagateUploadFileCommon::finalize (this=0x682440) at /client/src/libsync/propagateupload.cpp:614
#11 0x00007ffff7a02c26 in OCC::PropagateUploadFileCommon::finalize()::$_0::operator()(QString const&, QMap<QString, QString> const&) const (this=0x640f40, map=...) at /client/src/libsync/propagateupload.cpp:585
#12 0x00007ffff7a02ab2 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QString const&, QMap<QString, QString> const&>, void, OCC::PropagateUploadFileCommon::finalize()::$_0>::call(OCC::PropagateUploadFileCommon::finalize()::$_0&, void**) (f=..., arg=0x7fffffffb720) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:137
#13 0x00007ffff7a02a61 in QtPrivate::Functor<OCC::PropagateUploadFileCommon::finalize()::$_0, 2>::call<QtPrivate::List<QString const&, QMap<QString, QString> const&>, void>(OCC::PropagateUploadFileCommon::finalize()::$_0&, void*, void**) (f=..., arg=0x7fffffffb720) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:339
#14 0x00007ffff7a029fe in QtPrivate::QCallableObject<OCC::PropagateUploadFileCommon::finalize()::$_0, QtPrivate::List<QString const&, QMap<QString, QString> const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x640f30, r=0x682440, a=0x7fffffffb720, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:522
#15 0x00007ffff4f52951 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffb720, r=0x682440, this=0x640f30) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobjectdefs_impl.h:433
#16 doActivate<false> (sender=0x67eba0, signal_index=7, argv=0x7fffffffb720) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobject.cpp:4039
#17 0x00007ffff791d212 in OCC::PropfindJob::directoryListingIterated (this=0x67eba0, _t1=..., _t2=...) at src/libsync/libsync_autogen/EWIEGA46WW/moc_networkjobs.cpp:657
#18 0x00007ffff79cd80d in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QString const&, QMap<QString, QString> const&>, void, void (OCC::PropfindJob::*)(QString const&, QMap<QString, QString> const&)>::call
    (f=(void (OCC::PropfindJob::*)(OCC::PropfindJob * const, const QString &, const QMap<QString, QString> &)) 0x7ffff791d1c0 <OCC::PropfindJob::directoryListingIterated(QString const&, QMap<QString, QString> const&)>, o=0x67eba0, arg=0x7fffffffb980) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:145
#19 0x00007ffff79cd74d in QtPrivate::FunctionPointer<void (OCC::PropfindJob::*)(QString const&, QMap<QString, QString> const&)>::call<QtPrivate::List<QString const&, QMap<QString, QString> const&>, void>
    (f=(void (OCC::PropfindJob::*)(OCC::PropfindJob * const, const QString &, const QMap<QString, QString> &)) 0x7ffff791d1c0 <OCC::PropfindJob::directoryListingIterated(QString const&, QMap<QString, QString> const&)>, o=0x67eba0, arg=0x7fffffffb980) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#20 0x00007ffff79cd675 in QtPrivate::QCallableObject<void (OCC::PropfindJob::*)(QString const&, QMap<QString, QString> const&), QtPrivate::List<QString const&, QMap<QString, QString> const&>, void>::impl (which=1, this_=0x6a28a0, r=0x67eba0, a=0x7fffffffb980, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#21 0x00007ffff4f52951 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffb980, r=0x67eba0, this=0x6a28a0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobjectdefs_impl.h:433
#22 doActivate<false> (sender=0x7fffffffbfe0, signal_index=4, argv=0x7fffffffb980) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobject.cpp:4039
#23 0x00007ffff791cc92 in OCC::LsColXMLParser::directoryListingIterated (this=0x7fffffffbfe0, _t1=..., _t2=...) at src/libsync/libsync_autogen/EWIEGA46WW/moc_networkjobs.cpp:410
#24 0x00007ffff79c4964 in OCC::LsColXMLParser::parse (this=0x7fffffffbfe0, xml=..., sizes=0x67ec80, expectedPath=...) at /client/src/libsync/networkjobs.cpp:201
#25 0x00007ffff79c5d7f in OCC::PropfindJob::finished (this=0x67eba0) at /client/src/libsync/networkjobs.cpp:319
#26 0x00007ffff79c079a in OCC::AbstractNetworkJob::slotFinished (this=0x67eba0) at /client/src/libsync/abstractnetworkjob.cpp:247
#27 0x00007ffff79c32c1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (OCC::AbstractNetworkJob::*)()>::call(void (OCC::AbstractNetworkJob::*)(), OCC::AbstractNetworkJob*, void**)
    (f=(void (OCC::AbstractNetworkJob::*)(OCC::AbstractNetworkJob * const)) 0x7ffff79bff20 <OCC::AbstractNetworkJob::slotFinished()>, o=0x67eba0, arg=0x7fffffffc548) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:145
#28 0x00007ffff79c320d in QtPrivate::FunctionPointer<void (OCC::AbstractNetworkJob::*)()>::call<QtPrivate::List<>, void>(void (OCC::AbstractNetworkJob::*)(), OCC::AbstractNetworkJob*, void**)
    (f=(void (OCC::AbstractNetworkJob::*)(OCC::AbstractNetworkJob * const)) 0x7ffff79bff20 <OCC::AbstractNetworkJob::slotFinished()>, o=0x67eba0, arg=0x7fffffffc548) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#29 0x00007ffff79c3135 in QtPrivate::QCallableObject<void (OCC::AbstractNetworkJob::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x63da90, r=0x67eba0, a=0x7fffffffc548, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#30 0x00007ffff4f52951 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffc548, r=0x67eba0, this=0x63da90) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobjectdefs_impl.h:433
#31 doActivate<false> (sender=0x63db60, signal_index=12, argv=0x7fffffffc548) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobject.cpp:4039
#32 0x000000000041e0ee in FakePropfindReply::respond (this=0x63db60) at /client/test/testutils/syncenginetestutils.cpp:435
#33 0x0000000000439214 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (FakePropfindReply::*)()>::call(void (FakePropfindReply::*)(), FakePropfindReply*, void**) (f=(void (FakePropfindReply::*)(FakePropfindReply * const)) 0x41dfc0 <FakePropfindReply::respond()>, o=0x63db60, arg=0x6138c8)
    at /usr/include/qt6/QtCore/qobjectdefs_impl.h:145
#34 0x000000000043916d in QtPrivate::FunctionPointer<void (FakePropfindReply::*)()>::call<QtPrivate::List<>, void>(void (FakePropfindReply::*)(), FakePropfindReply*, void**) (f=(void (FakePropfindReply::*)(FakePropfindReply * const)) 0x41dfc0 <FakePropfindReply::respond()>, o=0x63db60, arg=0x6138c8) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#35 0x0000000000439095 in QtPrivate::QCallableObject<void (FakePropfindReply::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x68ed40, r=0x63db60, a=0x6138c8, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#36 0x00007ffff4f43f87 in QObject::event (this=0x63db60, e=0x613880) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qobject.cpp:1437
#37 0x00007ffff4ef192b in doNotify (event=0x613880, receiver=0x63db60) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1217
#38 QCoreApplication::notify (event=<optimized out>, receiver=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1200
#39 QCoreApplication::notifyInternal2 (receiver=0x63db60, event=0x613880) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1121
#40 0x00007ffff4ef1b4d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1539
#41 0x00007ffff4ef5845 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x49b9b0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1901
#42 0x00007ffff4ef5bbd in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qcoreapplication.cpp:1760
#43 0x00007ffff51bd86f in postEventSourceDispatch (s=0x49f3d0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:243
#44 0x00007ffff433be5c in g_main_dispatch (context=0x49f1d0) at ../glib/gmain.c:3476
#45 g_main_context_dispatch_unlocked (context=0x49f1d0) at ../glib/gmain.c:4284
#46 0x00007ffff4396f18 in g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x49f1d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4349
#47 0x00007ffff4339ad3 in g_main_context_iteration (context=0x49f1d0, may_block=1) at ../glib/gmain.c:4414
#48 0x00007ffff51bd11f in QEventDispatcherGlib::processEvents (this=0x49f0a0, flags=...) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#49 0x00007ffff4efe70b in QEventLoop::exec (this=0x7fffffffcbd0, flags=...) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/global/qflags.h:34
#50 0x000000000042d478 in QTestEventLoop::enterLoop (this=0x7fffffffcce0, msecs=std::chrono::duration = { 3600000ms }) at /usr/include/qt6/QtTest/qtesteventloop.h:73
#51 0x000000000042965d in QSignalSpy::wait (this=0x7fffffffcc88, timeout=std::chrono::duration = { 3600000ms }) at /usr/include/qt6/QtTest/qsignalspy.h:105
#52 0x000000000042a2c1 in QSignalSpy::wait (this=0x7fffffffcc88, timeout=3600000) at /usr/include/qt6/QtTest/qsignalspy.h:98
#53 0x0000000000424003 in FakeFolder::execUntilFinished (this=0x7fffffffd508) at /client/test/testutils/syncenginetestutils.cpp:1173
#54 0x0000000000422c79 in FakeFolder::syncOnce (this=0x7fffffffd508) at /client/test/testutils/syncenginetestutils.cpp:1188
#55 0x00000000004156e7 in FakeFolder::applyLocalModificationsAndSync (this=0x7fffffffd508) at /client/test/testutils/syncenginetestutils.h:614
#56 0x0000000000413a1e in TestDatabaseError::testDatabaseError (this=0x7fffffffe1b0) at /client/test/testdatabaseerror.cpp:81
#57 0x0000000000412bf3 in TestDatabaseError::qt_static_metacall (_o=0x7fffffffe1b0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffda90) at test/DatabaseErrorTest_autogen/include/testdatabaseerror.moc:119
#58 0x00007ffff4f0772f in QMetaMethodInvoker::invokeImpl (self=..., target=0x7fffffffe1b0, connectionType=connectionType@entry=Qt::DirectConnection, paramCount=paramCount@entry=1, parameters=parameters@entry=0x7fffffffda90, typeNames=0x7fffffffda98, metaTypes=0x7fffffffdaa0)
    at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qmetaobject.cpp:2713
#59 0x00007ffff4f08638 in QMetaMethod::invokeImpl (self=..., target=<optimized out>, connectionType=connectionType@entry=Qt::DirectConnection, paramCount=paramCount@entry=1, parameters=parameters@entry=0x7fffffffda90, typeNames=0x7fffffffda98, metaTypes=0x7fffffffdaa0)
    at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qmetaobject.cpp:2551
#60 0x00007ffff7f803e5 in QMetaMethod::invoke<>(QObject*, Qt::ConnectionType, QMetaMethodReturnArgument) const (r=..., c=Qt::DirectConnection, obj=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qmetaobject.h:148
#61 QMetaMethod::invoke<>(QObject*, Qt::ConnectionType) const (c=Qt::DirectConnection, obj=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/corelib/kernel/qmetaobject.h:160
#62 QTest::TestMethods::invokeTestOnData (this=0x7fffffffe030, index=0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/testlib/qtestcase.cpp:1136
#63 0x00007ffff7f8134f in QTest::TestMethods::invokeTest (this=this@entry=0x7fffffffe030, index=index@entry=0, tag=..., watchDog=0x0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/testlib/qtestcase.cpp:1429
#64 0x00007ffff7f819ad in QTest::TestMethods::invokeTests (this=this@entry=0x7fffffffe030, testObject=0x7fffffffe1b0) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/testlib/qtestcase.cpp:1767
#65 0x00007ffff7f822c1 in QTest::qRun () at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/testlib/qtestcase.cpp:2401
#66 0x00007ffff7f82827 in QTest::qExec (testObject=<optimized out>, argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-qtbase-6.6.2-1.fc39.x86_64/src/testlib/qtestcase.cpp:2287
#67 0x0000000000412b6c in main (argc=1, argv=0x7fffffffe308) at /client/test/testdatabaseerror.cpp:111
```
