### ISSUE TITLE
1.6.4 segfault on disk full

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2473]
On rh6 I filled up my home partition where the sync folder is. The client crashed. It was only downloading files from the server (another client on another box was putting them to the server).

Trace:

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f3371a91064 in QSqlQuery::bindValue(QString const&, QVariant const&, QFlags<QSql::ParamTypeFlag>) () from /opt/qt-4.8/lib64/libQtSql.so.4
Missing separate debuginfos, use: debuginfo-install owncloud-client-1.6.4-1.1.x86_64
(gdb) bt
#0  0x00007f3371a91064 in QSqlQuery::bindValue(QString const&, QVariant const&, QFlags<QSql::ParamTypeFlag>) () from /opt/qt-4.8/lib64/libQtSql.so.4
#1  0x00007f33710016a8 in Mirall::SyncJournalDb::blacklistEntry(QString const&) () from /opt/qt-4.8/lib64/libowncloudsync.so.0
#2  0x00007f3370fde9ee in Mirall::SyncEngine::checkBlacklisting(Mirall::SyncFileItem*) () from /opt/qt-4.8/lib64/libowncloudsync.so.0
#3  0x00007f3370fdf3c3 in Mirall::SyncEngine::treewalkFile(csync_tree_walk_file_s*, bool) () from /opt/qt-4.8/lib64/libowncloudsync.so.0
#4  0x00007f3370d717d7 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#5  0x00007f3370d7c42e in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#6  0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#7  0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#8  0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#9  0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#10 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#11 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#12 0x00007f3370d7c441 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#13 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#14 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#15 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#16 0x00007f3370d7c419 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#17 0x00007f3370d7cacb in c_rbtree_walk () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#18 0x00007f3370d715c3 in ?? () from /opt/qt-4.8/lib64/owncloud/libocsync.so.0
#19 0x00007f3370fe17a3 in Mirall::SyncEngine::slotUpdateFinished(int) () from /opt/qt-4.8/lib64/libowncloudsync.so.0
#20 0x00007f33713f6dbe in QObject::event(QEvent*) () from /opt/qt-4.8/lib64/libQtCore.so.4
#21 0x00007f337233f4cc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/qt-4.8/lib64/libQtGui.so.4
#22 0x00007f33723454bd in QApplication::notify(QObject*, QEvent*) () from /opt/qt-4.8/lib64/libQtGui.so.4
#23 0x00007f33713e532c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/qt-4.8/lib64/libQtCore.so.4
#24 0x00007f33713e9603 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /opt/qt-4.8/lib64/libQtCore.so.4
#25 0x00007f3371412b03 in ?? () from /opt/qt-4.8/lib64/libQtCore.so.4
#26 0x000000360303feb2 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#27 0x0000003603043d68 in ?? () from /lib64/libglib-2.0.so.0
#28 0x0000003603043f1c in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#29 0x00007f3371412433 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt-4.8/lib64/libQtCore.so.4
#30 0x00007f33723e251e in ?? () from /opt/qt-4.8/lib64/libQtGui.so.4
#31 0x00007f33713e4012 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt-4.8/lib64/libQtCore.so.4
#32 0x00007f33713e4374 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt-4.8/lib64/libQtCore.so.4
#33 0x00007f33713e99c9 in QCoreApplication::exec() () from /opt/qt-4.8/lib64/libQtCore.so.4
#34 0x0000000000432ea5 in main ()
```

Last log lines:

```
11-08 07:16:14:810 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ? , ?, ? , ? )" "smashbox-osx-141108-071529/fc4858ceb956186b7c6a4d5b6f568aa6" "smashbox-osx-141108-071529/.fc4858ceb956186b7c6a4d5b6f568aa6.~5c00bc24" "919154676727808:252ef555" 0 
11-08 07:16:14:810 Transaction Start  "download file start" 
11-08 07:16:14:869 void Mirall::AbstractNetworkJob::setTimeout(qint64) 300000 
11-08 07:16:14:869 !!! Mirall::GETFileJob created for  QUrl( "https://testbox.cern.ch/cernbox/desktop" )  querying "home/smashbox-osx-141108-071529/fc4858ceb956186b7c6a4d5b6f568aa6" 
11-08 07:16:15:205 Error while writing to file 4343 8192 "Unknown error" 
11-08 07:16:15:205 void Mirall::AbstractNetworkJob::slotFinished() 5 "Operation canceled" 
11-08 07:16:15:205 void Mirall::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://testbox.cern.ch/cernbox/desktop/remote.php/webdav/home/smashbox-osx-141108-071529/f61c6ae0662e60fd297cec905d72e773" )  FINISHED WITH STATUS 5 "Operation canceled" 
11-08 07:16:15:406 SQL exec blacklistitem insert/update failed:  "disk I/O error Unable to fetch row" 
11-08 07:16:15:414 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "smashbox-osx-141108-071529/f61c6ae0662e60fd297cec905d72e773" 2 "Unknown error" 
11-08 07:16:15:448 Error while writing to file 247 8192 "Unknown error" 
11-08 07:16:15:448 void Mirall::AbstractNetworkJob::slotFinished() 5 "Operation canceled" 
11-08 07:16:15:448 void Mirall::PropagateDownloadFileQNAM::slotGetFinis
```

**Comment by ogoffart** [comment]
We are not using QtSql anymore in recent version.
I am closing this bug now, please open another bug if it still happen with 1.8
