### ISSUE TITLE
Big file never uploads when having slow upload speed (1.7 on Linux)

### ISSUE THREAD

**Issue by brozkeff** [owncloud/client#2514]
Client: Linux Mint 17 Cinnamon 64bit, 1.7.0
Server: Ubuntu Server 14.04, ownCloud 7.0.3

I have 512kbps upload speed of ADSL at home and I added a 1,1 GB video to my owncloud folder. It has been 4 hours and it tries to upload the file for something like 10th attempt. Once it uploaded like 300 MBs and then when I check later it is again at the beginning. Something in the process cancels the upload and the whole things starts completely from the beginning.

Desired behaviour:
Even if there are some temporary connection issues if the connection is restored the upload should continue where it stopped = in the middle of file, the same thing any download manager or ftp client can do. If the raw time to upload the video is 8 hours and after 4 hours it starts from scratch...again and again, even when the connection to internet should be stable, then I cannot upload the file never completely yet I keep my upload line always full and all the other apps slower.

**Comment by m33x** [comment]
Hi I have a similar problem.

The file is very large / big (6.3GB) and stored on an external WebDav. I uploaded the file with the client, but now I'm facing this problem in an endless loop: (See Screenshot)
As I'm connected via a gigabit connection I can easily reproduce the problem, if this would be helpful for you guys. Thank your very much for any fix or workaround.

![owncloud_bug2](https://cloud.githubusercontent.com/assets/883685/6371933/ad2b9502-bd00-11e4-88a7-8a5cb8645dd1.png)


The worst thing is, that everytime the loop repeats (every 5 minutes) the overall available storage decreases. Just compare these two screenshots.

![repeat](https://cloud.githubusercontent.com/assets/883685/6371962/e309a876-bd00-11e4-9b75-bc8f5c9db0d6.png)


**The grep command**: 
```sh
user@PC:~/ownCloud$ sqlite3 .csync_journal.db .dump | grep "Bigfile.7z"
INSERT INTO "downloadinfo" VALUES('Privat/Shares/Bigfile.7z','Privat/Shares/.Bigfile.7z.~5428e794','54edd18c120bb',0);
```
**Client Logfile (Pressed F12 in the Owncloud Client Settings Window): Ubuntu 14.04 - Sync Client 1.7.1**: 
```sh
02-25 14:49:19:085 0x112ca30 virtual void Mirall::PropagateDownloadFileQNAM::start() "Privat/Shares/Bigfile.7z" 0 
02-25 14:49:19:086 0x112ca30 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "Privat/Shares/Bigfile.7z" "Privat/Shares/.Bigfile.7z.~5428e794" "54edd18c120bb" 0 
02-25 14:49:19:087 0x112ca30 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
02-25 14:49:19:098 0x112ca30 !!! Mirall::GETFileJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/Privat/Shares/Bigfile.7z"

...

02-25 14:49:32:028 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:49:40:787 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:50:02:021 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:50:10:850 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:50:32:020 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:50:40:923 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:51:02:027 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:51:10:985 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:51:32:020 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:51:41:046 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:52:02:022 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:52:11:116 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:52:32:019 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:52:41:178 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:53:02:019 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:53:11:240 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:53:32:020 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:53:41:301 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:54:02:020 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-25 14:54:11:364 0x112ca30 !!! Mirall::CheckQuotaJob created for  QUrl( "https://server.example.org/owncloud" )  querying "/" 
02-25 14:54:19:105 0x112ca30 void Mirall::AbstractNetworkJob::slotFinished() 5 "Operation canceled" 
02-25 14:54:19:106 0x112ca30 void Mirall::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://server.example.org/owncloud/remote.php/webdav/Privat/Shares/Bigfile.7z" )  FINISHED WITH STATUS 5 "Operation canceled" 
02-25 14:54:19:107 0x112ca30 "DELETE FROM downloadinfo WHERE path=?1" "Privat/Shares/Bigfile.7z" 
02-25 14:54:19:108 0x112ca30 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "Privat/Shares/Bigfile.7z" 1 "Connection Timeout" 
02-25 14:54:19:114 0x112ca30 detected changes in folders: QSet("/home/user/ownCloud/Privat/Shares") 
02-25 14:54:19:115 0x112ca30 folder  "ownCloud"  is currently syncing. NOT scheduling. 
02-25 14:54:19:115 0x112ca30 void Mirall::Folder::watcherSlot(QString) Sync running, IGNORE event for  "/home/user/ownCloud/Privat/Shares" 
02-25 14:54:19:161 0x112ca30 void Mirall::SyncJournalDb::walCheckpoint() took 0 msec 
02-25 14:54:19:161 0x112ca30 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
02-25 14:54:19:169 0x112ca30 CSync run took  314666 
02-25 14:54:19:172 0x112ca30 -> SyncEngine finished with ERROR, warn count is 1 
02-25 14:54:19:172 0x112ca30 Processing result list and logging took  0  Milliseconds. 
02-25 14:54:19:173 0x112ca30 OO folder slotSyncFinished: result:  3 
02-25 14:54:19:178 0x112ca30   ** error Strings:  ("Connection Timeout", "Privat/Shares/Bigfile.7z: Connection Timeout") 
02-25 14:54:19:178 0x112ca30     * owncloud csync thread finished with error 
02-25 14:54:19:179 0x112ca30 the last 2 syncs failed 
02-25 14:54:19:530 0x112ca30 Folder in overallStatus Message:  Mirall::Folder(0x135ecf0)  with name  "ownCloud" 
02-25 14:54:19:530 0x112ca30 Sync state changed for folder  "ownCloud" :  "Error" 
02-25 14:54:19:730 0x112ca30 <===================================== sync finished for  "ownCloud" 
02-25 14:54:19:932 0x112ca30 XX slotScheduleFolderSync: folderQueue size:  0 
02-25 14:54:32:019 0x112ca30 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
```
**Server Logfile (/var/www/owncloud/data/owncloud.log) - Ubuntu 14.04 - Server ownCloud 8.0 (stable) - PHP 5.5.9-1ubuntu4.6 - MySQL Backend 5.5.41-0ubuntu0.14.04.1**:
```sh
{"reqId":"ba9f87356f2408d26d912eadeac981fa","remoteAddr":"<IP-Address-of-the-Client>","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-02-25T13:49:30+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"03078efef2d12fa1a0a64967ce3016ab","remoteAddr":"<IP-Address-of-the-Client>","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-02-25T13:55:30+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
```

**Comment by ogoffart** [comment]
The connection timeout issue is a known issue on the server that we still have to see fixed.

Server issue  https://github.com/owncloud/core/issues/12097
