### ISSUE TITLE
Nautilus integration: error on client shutdown

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2819]
When I quit the ownCloud client while nautilus has a socket api connection open, nautilus prints the following to stderr: (with e79e2b80c80790996646ce7d2773dfafa78fc69e)

```
Server response: UNREGISTER_PATH:/home/kamm/ownCloud/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 682, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/home/kamm/.local/share/nautilus-python/extensions/syncstate.py", line 234, in handle_notify
    self.handle_server_response(l)
  File "/home/kamm/.local/share/nautilus-python/extensions/syncstate.py", line 208, in handle_server_response
    self.sock.close()
AttributeError: 'syncStateExtension' object has no attribute 'sock'
```

The overlay icons don't come back when the client is started again.

**Comment by ckamm** [comment]
Sorry for the noise, was a trivial fix.
