### ISSUE TITLE
qt5 build does not sync and dumps core

### ISSUE THREAD

**Issue by arthurtiteica** [owncloud/client#2987]
Version 1.7 built with qt4 still works with the same server.

Owncloud 1.8, built with qt5, fails to sync and when trying to modify the account an error is shown:
"Timeout while trying to reach server/status.php"

Closing the client dumps core. Bellow is the gdb trace.
```
Core was generated by `owncloud'.
Program terminated with signal SIGILL, Illegal instruction.
#0 0x00007f4f8d169f10 in QListData::shared_null () from /usr/lib/libQt5Core.so.5
(gdb) bt full
#0 0x00007f4f8d169f10 in QListData::shared_null () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#1 0x00007f4f7ae539fd in KStatusNotifierItem::~KStatusNotifierItem() () from /usr/lib/libKF5Notifications.so.5
No symbol table info available.
#2 0x00007f4f7ae540b9 in KStatusNotifierItem::~KStatusNotifierItem() () from /usr/lib/libKF5Notifications.so.5
No symbol table info available.
#3 0x00007f4f7b37d4c3 in ?? () from /usr/lib/qt/plugins/platformthemes/KDEPlatformTheme.so
No symbol table info available.
#4 0x00007f4f8de4f94b in QSystemTrayIcon::~QSystemTrayIcon() () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#5 0x00000000004f8f67 in OCC::Systray::~Systray() ()
No symbol table info available.
#6 0x00007f4f8d0c2b0c in QObjectPrivate::deleteChildren() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#7 0x00007f4f8d0cd153 in QObject::~QObject() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#8 0x00000000004fa03b in OCC::ownCloudGui::~ownCloudGui() ()
No symbol table info available.
#9 0x00007f4f8d0c50a8 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#10 0x00007f4f8dad2acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#11 0x00007f4f8dad7f10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007f4f8d093d1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#13 0x00007f4f8d095d5b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#14 0x00007f4f8d0991c9 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#15 0x000000000044d818 in main ()
No symbol table info available.
```
Additional info:
owncloud-client 1.8.0-1 Arch Linux x64

**Comment by guruz** [comment]
Duplicate of https://github.com/owncloud/client/issues/2934

CC @ogoffart
