### ISSUE TITLE
[Beta1] I can't connect with Shibboleth

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3593]
### Steps to reproduce
1. Open your onwCloud Desktop client
2. Fill in the server url with shibboleth
3. Click NEXT
    
### Expected behaviour
You should be able to connect with SHIB

### Actual behaviour
the screen is blank

### Server configuration
Desktop v 2.0.0beta1 (build 2613)

**Web server:**

**Database:**

**Comment by danimo** [comment]
This works for me just fine with a current nightly. Please give the exact steps and OS to reproduce.

**Comment by Dianafg76** [comment]
@danimo With this url: https://docker.oc.solidgear.es:51735/oc-shib, I can't go in with the Desktop client, but if I try the same url in the Server I can

**Comment by guruz** [comment]
@Dianafg76 Did you try another server too?

**Comment by Dianafg76** [comment]
@guruz, I try with this url: https://docker.oc.solidgear.es:51801/oc-shib, and with the Server and the mobile it is working OK, but with the Desktop client it is not working

**Comment by guruz** [comment]
```
08-13 13:11:51:192 0x7fbbf8d182f0 OCC::ShibbolethWebView::slotLoadFinished: void OCC::ShibbolethWebView::slotLoadFinished(bool) Could not load Shibboleth login page to log you in.
```

**Comment by guruz** [comment]
It might be because  https://docker.oc.solidgear.es:51801/oc-shib has an untrusted SSL certificate and Shibboleth and Client use a different QNAM.

This also would explain why it works for @danimo with a different server.

**Comment by Dianafg76** [comment]
@guruz Hi, I tested this issue and it is not working. Now it is appears this: 
![screen shot 2015-08-14 at 08 30 18](https://cloud.githubusercontent.com/assets/12032058/9268380/bef1068a-425e-11e5-92aa-e47e51f313e1.png)

**Comment by Dianafg76** [comment]
Log:
```
08-14 08:33:07:417 0x7fe3e071d490 OCC::OwncloudSetupWizard::slotConnectToOCUrl: Connect to url:  "https:// https://docker.oc.solidgear.es:51801/oc-shib"
08-14 08:33:07:418 0x7fe3e071d490 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Trying to connect to ownCloud at https:// https://docker.oc.solidgear.es:51801/oc-shib..."
08-14 08:33:07:418 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es/oc-shib" + "/"
08-14 08:33:07:419 0x7fe3e28a1da0 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7fe3e28faae0) 4 QObject(0x0) 
08-14 08:33:07:419 0x7fe3e28a1da0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fe3e28faae0) QObject(0x0)  0 false 3 16
08-14 08:33:07:665 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es/oc-shib" + "/"
08-14 08:33:07:677 0x7fe3e071d490 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  3
08-14 08:33:08:654 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::EntityExistsJob created for "https://docker.oc.solidgear.es/oc-shib" + "remote.php/webdav/"
08-14 08:33:08:778 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7fe3e28ead20) 0 QObject(0x0) 
08-14 08:33:08:778 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fe3e28ead20) QObject(0x0)  0 false 3 16
08-14 08:33:08:780 0x7fe3e071d490 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 403 "Error downloading https://docker.oc.solidgear.es:51801/oc-shib/remote.php/webdav/ - server replied: Service Unavailable" QVariant(int, 503)
08-14 08:33:08:780 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::ShibbolethUserJob created for "https://docker.oc.solidgear.es/oc-shib" + "ocs/v1.php/cloud/user"
08-14 08:33:11:333 0x7fe3e2a21d80 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fe3e0578140) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-14 08:33:11:333 0x7fe3e2a21d80 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fe3e0578140) QObject(0x0)  0 false 3 0
08-14 08:33:12:612 0x7fe3e071d490 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fe3e31e72a0)
08-14 08:33:12:612 0x7fe3e071d490 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/Diana/user7/"
08-14 08:33:12:613 0x7fe3e071d490 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
08-14 08:33:14:007 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fe3e28ead20) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-14 08:33:14:007 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fe3e28ead20) QObject(0x0)  0 false 3 0
08-14 08:33:20:595 0x7fe3e071d490 OCC::OwncloudSetupWizard::slotCreateLocalAndRemoteFolders: Setup local sync folder for new oC connection  "/Users/Diana/SHIB"
08-14 08:33:20:596 0x7fe3e071d490 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Local sync folder /Users/Diana/SHIB already exists, setting it up for sync.<br/><br/>"
08-14 08:33:20:596 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::EntityExistsJob created for "https://docker.oc.solidgear.es/oc-shib" + "remote.php/webdav//"
08-14 08:33:20:823 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7fe3e28ead20) 0 QObject(0x0) 
08-14 08:33:20:823 0x7fe3e288b8f0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fe3e28ead20) QObject(0x0)  0 false 3 16
08-14 08:33:20:825 0x7fe3e071d490 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 403 "Error downloading https://docker.oc.solidgear.es:51801/oc-shib/remote.php/webdav/ - server replied: Service Unavailable" QVariant(int, 503)
```

**Comment by Dianafg76** [comment]
Other Log:
```
08-14 08:33:08:780 0x7fe3e071d490 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 403 "Error downloading https://docker.oc.solidgear.es:51801/oc-shib/remote.php/webdav/ - server replied: Service Unavailable" QVariant(int, 503)
08-14 08:33:08:780 0x7fe3e071d490 OCC::AbstractNetworkJob::start: !!! OCC::ShibbolethUserJob created for "https://docker.oc.solidgear.es/oc-shib" + "ocs/v1.php/cloud/user"
08-14 08:33:11:333 0x7fe3e2a21d80 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fe3e0578140) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
```

**Comment by guruz** [comment]
OK, but isn't that a server side issue ```Internal Server Error```? Maybe some setup problem?
Did you try another instance? Did you check the server's ```owncloud.log```?

**Comment by Dianafg76** [comment]
I tried with 2 different server:
https://docker.oc.solidgear.es:51801/oc-shib
https://docker.oc.solidgear.es:51792/oc-shib
And on the server it is working

**Comment by Dianafg76** [comment]
the server oncloud.log:
```

Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 503 Exception: Session has been closed - no further changes to the session as allowed","Code":0,"Trace":"#0 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#4 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(253): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpHead(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:HEAD', Array)\n#8 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/opt\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#10 \/opt\/owncloud\/remote.php(132): require_once('\/opt\/owncloud\/a...')\n#11 {main}","File":"\/opt\/owncloud\/lib\/private\/connector\/sabre\/auth.php","Line":129} 
```

**Comment by guruz** [comment]
@danimo Please re-test with a more official server and then close..

**Comment by Dianafg76** [comment]
@danimo, @guruz  I tested with the official server and it is working OK
Closed

**Comment by davitol** [comment]
Tested with a Shibboleth user V.2.0.0. RC1 and with OC server version":"8.2.0.4","versionstring":"8.2 pre alpha" and I get the same behaviour @Dianafg76 reported. FYI it is also used the lastest Shibboleth app for 8.2 in SSO mode.

**Comment by guruz** [comment]
@danimo Can you help out here? I think the problem is the server setup as you said that another account works.. https://github.com/owncloud/client/issues/3593#issuecomment-130040951

**Comment by danimo** [comment]
@guruz Could also be a newer version of the server. @davitol URL, pls.

**Comment by rperezb** [comment]
Further details:
### STEPS
1.- Login to a shib server
2.- Select the sync folder
3.- Error

###Server logs
owncloud.log
````
{"reqId":"29cQ6LKctg8S\/WkrVj6V","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Exception: Session has been closed - no further changes to the session as allowed\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\
```
access.ssh.log
```
myself@testshib.org [19/Aug/2015:16:24:55 +0000] "HEAD /oc-shib/remote.php/webdav/ HTTP/1.1" 503 0 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.0 (testpilotcloud)"
```

**Comment by ckamm** [comment]
The interesting thing that "Choose what to sync" can display the account's contents just fine so the PROPFIND works. But the EntityExistsJob (HEAD) fails with a 503. The same cookies are used for both requests.

**Comment by ckamm** [comment]
I think this is a server bug. In response to the HEAD request the server logs `503 Exception: Session has been closed - no further changes to the session as allowed` but that doesn't seem true. Follow up PROPFINDs work just fine.

**Comment by danimo** [comment]
@DeepDiver1975 pls

**Comment by DeepDiver1975** [comment]
Which server versions did you test this against?
Are old clients connecting to these server versions?

^ this is necessary information to get it sorted out to see if this is a client or a server issues - THX

**Comment by dragotin** [comment]
The server version is  ownCloud Enterprise Edition 8.2 pre alpha (daily) Build:2015-08-19T03:11:14+00:00 69e72eeb37b6d0084c137e1cffffe8717c2f1de0

**Comment by DeepDiver1975** [comment]
THX @dragotin 

can we please test 2.0.0 client against 8.1 or earlier? This will give a representative result on 2.0.0 client being ready for release or not.

Within 8.2 the shibboleth code has been touched and is currently being tested - it might be broken or not - nothing to care about with respect to the 2.0.0 client release.

**Comment by danimo** [comment]
Ok, here we go:

client/server | result
--------------------------- | ----------
2.0.0rc1 with 8.2pre: | breaks
2.0.0rc1 with 8.1.1:   | breaks
2.0.0rc1 with 8.0.6:   | **works**
2.0.0rc1 with 7.0.6:   | **works**

So this looks like a regression as old as 8.1.1.

**Comment by DeepDiver1975** [comment]
> So this looks like a regression as old as 8.1.1.

Congrats! Awesome!

**Comment by DeepDiver1975** [comment]
Same for an older client 1.8.x?

**Comment by danimo** [comment]
@DeepDiver1975 @ckamm Curious...

1.8.4 doesn't manage to open the testshib website (stays blank)
1.7.1 works

(with 8.1.1)

**Comment by DeepDiver1975** [comment]
> 1.7.1 works

with any oc server version?

**Comment by danimo** [comment]
Server issue. Filed in https://github.com/owncloud/user_shibboleth/issues/82.

**Comment by dragotin** [comment]
Ok, and since we have confirmation that 2.0.0 RC1 works with the non infected servers 8.0.6 and 7.0.6 I think this can be closed. @davitol feel free to verify again.

**Comment by davitol** [comment]
Agree with danimo's results
