### ISSUE TITLE
[Linux] Sync always canceling on the same files: Connection Closed

### ISSUE THREAD

**Issue by despens** [owncloud/client#3826]
## Expected behaviour

Sync all files

## Actual behaviour

Sync aborting on certain files, then connection is set to "closed"

## Steps to reproduce

I created a directory called `3sfs` to compile this software.
The sync always stops on some file inside this directory, typically one from `s3fs/src`

## Client log file

```
09-14 07:15:49:537 0x237a460 "/home/despens/.local/share/data//ownCloud//cookies.db" 
09-14 07:15:49:539 0x237a460 Saving account "https://oc.1x-upon.com" 
09-14 07:15:49:540 0x237a460 Saving  1  unknown certs. 
09-14 07:15:49:540 0x237a460 Saving cookies. 
09-14 07:15:49:541 0x237a460 "/home/despens/.local/share/data//ownCloud//cookies.db" 
09-14 07:15:58:456 0x237a460 # Check whether authenticated propfind works. 
09-14 07:15:58:457 0x237a460 !!! OCC::PropfindJob created for "https://oc.1x-upon.com" + "/" 
09-14 07:16:18:935 0x237a460 void OCC::AbstractNetworkJob::slotFinished() 2 "Connection closed" QVariant(, ) 
09-14 07:16:18:937 0x237a460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://oc.1x-upon.com/remote.php/webdav/Projects/s3fs/s3fs-fuse/.git/objects/pack/pack-14e331de4f6fc84fd6baea9e1a0e255130d6ed48.pack" )  FINISHED WITH STATUS 2 "Connection closed" QVariant(, ) QVariant(, ) 
09-14 07:16:18:938 0x237a460 "" 
09-14 07:16:18:938 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse/.git/objects/pack/pack-14e331de4f6fc84fd6baea9e1a0e255130d6ed48.pack" INSTRUCTION_NEW 1 "Connection closed" 
09-14 07:16:18:939 0x237a460 virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0x95d9580) "s3fs/s3fs-fuse/src/curl.o" 
09-14 07:16:18:940 0x237a460 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
09-14 07:16:18:941 0x237a460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://myserver/remote.php/webdav/Projects/s3fs/s3fs-fuse/src/curl.o" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(, ) QVariant(, ) 
09-14 07:16:18:942 0x237a460 "" 
09-14 07:16:18:942 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse/src/curl.o" INSTRUCTION_NEW 1 "Operation canceled" 
09-14 07:16:18:943 0x237a460 virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0xbf6db40) "s3fs/s3fs-fuse/src/s3fs" 
09-14 07:16:18:944 0x237a460 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
09-14 07:16:18:945 0x237a460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://myserver/remote.php/webdav/Projects/s3fs/s3fs-fuse/src/s3fs" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(, ) QVariant(, ) 
09-14 07:16:18:946 0x237a460 "" 
09-14 07:16:18:947 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse/src/s3fs" INSTRUCTION_NEW 1 "Operation canceled" 
09-14 07:16:18:948 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:955 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse/src" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:957 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse/src" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:958 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:959 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:960 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs/s3fs-fuse" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:961 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:964 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs" INSTRUCTION_NONE 0 "" 
09-14 07:16:18:964 0x237a460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "s3fs" INSTRUCTION_NONE 0 "" 
09-14 07:16:19:152 0x237a460 void OCC::SyncJournalDb::walCheckpoint() took 0 msec 
09-14 07:16:19:153 0x237a460 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
09-14 07:16:19:190 0x237a460 CSync run took  311006 
09-14 07:16:19:191 0x237a460 virtual OCC::BandwidthManager::~BandwidthManager() 
09-14 07:16:19:196 0x237a460  - client version 2.0.1  Qt 4.8.6 
09-14 07:16:19:198 0x237a460 -> SyncEngine finished with ERROR, warn count is 71 
09-14 07:16:19:229 0x237a460 (+) Watcher: "/home/despens/Projects/s3fs/s3fs-fuse/test" 
09-14 07:16:19:271 0x237a460 Processing result list and logging took  71  Milliseconds. 
09-14 07:16:19:272 0x237a460 OO folder slotSyncFinished: result:  3 
09-14 07:16:19:331 0x237a460   ** error Strings:  ("Connection closed", "Operation canceled", "Operation canceled", "s3fs/s3fs-fuse/.git/objects/pack/pack-14e331de4f6fc84fd6baea9e1a0e255130d6ed48.pack: Connection closed", "s3fs/s3fs-fuse/src/curl.o: Operation canceled", "s3fs/s3fs-fuse/src/s3fs: Operation canceled") 
09-14 07:16:19:335 0x237a460     * owncloud csync thread finished with error 
09-14 07:16:19:336 0x237a460 the last 17 syncs failed 
09-14 07:16:19:336 0x237a460 Folder in overallStatus Message:  OCC::Folder(0x2662340)  with name  "Projects" 
09-14 07:16:19:336 0x237a460 Sync state changed for folder  "Projects" :  "Error" 
09-14 07:16:19:537 0x237a460 <===================================== sync finished for  "Projects" 
09-14 07:16:19:950 0x237a460 !!! OCC::PropfindJob created for "https://myserver" + "/" 
09-14 07:16:30:466 0x237a460 # Check whether authenticated propfind works. 
09-14 07:16:30:466 0x237a460 !!! OCC::PropfindJob created for "https://myserver" + "/" 
09-14 07:16:50:455 0x237a460 !!! OCC::PropfindJob created for "https://myserver" + "/" 
09-14 07:17:02:457 0x237a460 # Check whether authenticated propfind works. 
09-14 07:17:02:458 0x237a460 !!! OCC::PropfindJob created for "https://myserver" + "/" 
09-14 07:17:13:849 0x237a460 * Trying to check "Projects" for changes via ETag check. (time since last sync: 54 s) 
09-14 07:17:13:850 0x237a460 Scheduling "Projects" to check remote ETag 
09-14 07:17:13:850 0x237a460 !!! OCC::RequestEtagJob created for "https://myserver" + "Projects" 
09-14 07:17:14:373 0x237a460 * Compare etag with previous etag: last: ""55f5c78a5f1c9""55f491779e849""55f587cab855d""55f49177a18df""55f587ca7d843""55f587cabacea""55f587ca85e22""55f587ca77fc6""55f491778491e""55f4917793218""55f587cabe084""55f4917792724""55f587ca80d91""55f5a440c3736""55f587ca7cccc""55f587cabfec7""55f587ca37409""55f587ca4367b""55f587cabdc17""55f587ca86d08""55f491779c355""55f587cb6dead""55f49177966ee""55f587ca7d22f""55f4917785daf""55f491779fa73""55f587ca44549""55f491779cd2c""55f587ca9c151""55f49177a0413""55f587ca90714""55f587ca9cc0b""55f587cac5662""55f587ca8729f""55f587caba739""55f491778dac1""55f49177a4655""55f587cac6d29""55f491778020a""55f587ca87f75""55f587cac5084""55f587cab54c4""55f491779deda""55f587ca3db24""55f587ca91317""55f587cb3eb83""55f491779adb0""55f491778d18b""55f491778682e""55f491778c777""55f4917795aee""55f587cabe4e7""55f587ca81369""55f587caaa564""55f587ca43bf4""55f587ca7e2c0""55f587cabeed4""55f49177a8be4""55f587ca9aaef""55f4917791b26""55f491779a543""55f587cab6661""55f587ca3ba34""55f587ca7e850""55f49177aabaf""55f5c78a5fc6d""55f587caafae1""55f4917780a42""55f587cab4021""55f491777fa17""55f587ca9d59b""55f587cac60a9""55f49177946e6""55f4917799d26""55f491778a895""55f587caac119""55f587cab5b27""55f587ca9d104""55f49177ace98""55f587ca8682d"" , received: ""55f5c78a5f1c9""55f491779e849""55f587cab855d""55f49177a18df""55f587ca7d843""55f587cabacea""55f587ca85e22""55f587ca77fc6""55f491778491e""55f4917793218""55f587cabe084""55f4917792724""55f587ca80d91""55f5a440c3736""55f587ca7cccc""55f587cabfec7""55f587ca37409""55f587ca4367b""55f587cabdc17""55f587ca86d08""55f491779c355""55f587cb6dead""55f49177966ee""55f587ca7d22f""55f4917785daf""55f491779fa73""55f587ca44549""55f491779cd2c""55f587ca9c151""55f49177a0413""55f587ca90714""55f587ca9cc0b""55f587cac5662""55f587ca8729f""55f587caba739""55f491778dac1""55f49177a4655""55f587cac6d29""55f491778020a""55f587ca87f75""55f587cac5084""55f587cab54c4""55f491779deda""55f587ca3db24""55f587ca91317""55f587cb3eb83""55f491779adb0""55f491778d18b""55f491778682e""55f491778c777""55f4917795aee""55f587cabe4e7""55f587ca81369""55f587caaa564""55f587ca43bf4""55f587ca7e2c0""55f587cabeed4""55f49177a8be4""55f587ca9aaef""55f4917791b26""55f491779a543""55f587cab6661""55f587ca3ba34""55f587ca7e850""55f49177aabaf""55f5c78a5fc6d""55f587caafae1""55f4917780a42""55f587cab4021""55f491777fa17""55f587ca9d59b""55f587cac60a9""55f49177946e6""55f4917799d26""55f491778a895""55f587caac119""55f587cab5b27""55f587ca9d104""55f49177ace98""55f587ca8682d"" 
```

## Server configuration

Operating system: Linux owncloud 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Web server: Apache/2.4.7 (Ubuntu)

Database: 5.5.44-0ubuntu0.14.04.1 (Ubuntu)

PHP version: PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul 2 2015 15:23:08)

ownCloud version: 8.1.1 (stable)

Storage backend: Standard file system

## Client configuration

Client version: 2.0.1

Operating system: ubuntu 14.04

OS language: en_US

Installation path of client: /usr/bin/owncloud

**Comment by guruz** [comment]
Does the situation improve if you set bandwidth limits to ```automatic``` in the settings dialog?

Do you see anything in the server's ```owncloud.log``` and webserver error log?

**Comment by guruz** [comment]
...and do you see that only for uploads?

**Comment by despens** [comment]
I haven't changed any setup option, but since this morning, the sync is displaying as complete, the client's log file is empty. :confused: The files that haven't been synced before are now all present on the server, as shown by the oc files app.

I wonder if the behavior changed because the indexing has finished?

**Comment by guruz** [comment]
Do you want to retry by uploading a big file? Like a 50 MB file or so?

If that fails:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#apache
Does changing ```SSLRenegBufferSize``` and the other ones (and restarting Apache) change anything?

**Comment by despens** [comment]
Suddenly, the same error appears again, but the client's logfile stays blank.

The s3fs source files are pretty small. I have uploaded much larger stuff already.

**Comment by guruz** [comment]
Please still try the ```SSLRenegBufferSize``` change, multiple files are sent down one SSL connection.

**Comment by guruz** [comment]
What do you have in ```owncloud.log``` on the server?

**Comment by despens** [comment]
Good call! `owncloud.log` says:

```
{"reqId":"H4e\/Pz4dEILvB26vyFu\/","remoteAddr":"10.0.3.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-09-16T19:33:08+00:00","method":"GET","url":"\/remote.php\/webdav\/"}
{"reqId":"Xi6fPCgQpooWOIu2H2V+","remoteAddr":"10.0.3.1","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-09-16T19:33:10+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/despens\/contacts\/"}
```

**Comment by guruz** [comment]
Nothing more from the previous hours?

**Comment by despens** [comment]
Dear @guruz, 

regarding, `SSLRenegBufferSize` on the Apache side: my Apache is not using SSL, the nginx frontend is handling it.

Regarding the logfiles: the sync client on my laptop doesn't show a log file anymore when i hit F12. My `owncloud.log` on he server is pretty long, can you give me a hint what to look for?

**Comment by guruz** [comment]
> the nginx frontend is handling it.

No chance that something is behaving wrong there?
Can you set the involved servers (both nginx and Apache) to verbose and check their log?

**Comment by despens** [comment]
I have been able to get rid of this problem by setting nginx's `client_max_body_size` to `0`. The error was noticeable on the web interface when trying to upload the same files there. I'm ok with closing this bug.

**Comment by despens** [comment]
(That being said, it would be great if the sync client could figure out, by trying different request sizes, what is the server configuration. nginx's default is a measly 1 MB.)

**Comment by guruz** [comment]
@despens Great! FYI https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html

FYI @RealRancor

**Comment by RealRancor** [comment]
The client_max_body_size is configured to 10G; in the nginx config shown above which should be more than enough.

Furthermore https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-your-webserver shows that you need to raise it if you want to upload even larger files.
