### ISSUE TITLE
Can't login behind Pound Reverse Proxy

### ISSUE THREAD

**Issue by enoch85** [owncloud/client#3881]
### Steps to reproduce
1. Install Pound Reverse Proxy with these settings:

```
ListenHTTP
        Address 192.168.1.200    # Pound Proxy Server
        Port    80
        xHTTP   2

# example.com (ownCloud VM 1)

        Service
                HeadRequire "Host:.*example.com.*"
                BackEnd
                        Address 192.168.1.150
                        Port    80
                End
        Session
                Type IP
                TTL 60000
                End
         End

# example.se (Website on VM2)

        Service
                HeadRequire "Host:*.example.se.*"
                BackEnd
                Address 192.168.1.160
                        Port 80
                End
        Session
                Type IP
                TTL 60000
                End
        End

# subdomain.example.se (ownCloud on VM2)

        Service
                HeadRequire "Host:*.subdomain.example.se.*"
                BackEnd
                Address 192.168.1.160
                        Port 80
                End
        Session
                Type IP
                TTL 60000
                End

         End

End
```
2. Try to login to the client

### Expected behavoiur

It should work

### Tested instances that is working

- NetDrive
- Android Client
- Browser (message appears)

### Actual Behaviour

```
Fatal	webdav	Exception: {"Message":"Requested uri (http:\/\/example.se\/owncloud\/remote.php\/webdav\/) is out of base uri (\/owncloud\/remote.php\/webdav\/)","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1279): Sabre\\HTTP\\Request->getPath()\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(464): Sabre\\DAV\\Server->checkPreconditions(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#4 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#5 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Request.php","Line":210}	2015-09-24T19:41:51+00:00
```

![image](https://cloud.githubusercontent.com/assets/4511254/10090177/88e01542-632c-11e5-8de9-d758a22e0dad.png)

### References

https://forum.owncloud.org/viewtopic.php?t=4949

**What does HTTPx do?**

http://manpages.ubuntu.com/manpages/precise/en/man8/pound.8.html

```
xHTTP value
              Defines which HTTP verbs are accepted. The possible values are:

              0  (default)  accept  only  standard  HTTP  requests (GET, POST,
              HEAD).

              1 additionally allow extended HTTP requests (PUT, DELETE).

              2  additionally  allow  standard  WebDAV  verbs  (LOCK,  UNLOCK,
              PROPFIND,  PROPPATCH, SEARCH, MKCOL, MOVE, COPY, OPTIONS, TRACE,
              MKACTIVITY, CHECKOUT, MERGE, REPORT).

              3 additionally allow  MS  extensions  WebDAV  verbs  (SUBSCRIBE,
              UNSUBSCRIBE,  NOTIFY, BPROPFIND, BPROPPATCH, POLL, BMOVE, BCOPY,
              BDELETE, CONNECT).

              4 additionally  allow  MS  RPC  extensions  verbs  (RPC_IN_DATA,
              RPC_OUT_DATA).
```

### Server and Client

**Client**
2.0.1

**Server**
8.1.3

**Comment by enoch85** [comment]
Some more info:

```
enoch@solve-it:~$ curl -X PROPFIND http://USER:PASS@example.com/remote.php/owncloud/Photos

<!DOCTYPE html>
<!--[if lte IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en"                                                             ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif                                                            ]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--                                                            <![endif]-->
        <head data-requesttoken="">
                <meta charset="utf-8">
                <title>
                ownCloud                </title>
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-sca                                                            le=1.0">
                <meta name="apple-itunes-app" content="app-id=543672169">
                <link rel="shortcut icon" type="image/png" href="/core/img/favicon.png">
                <link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
                                        <link rel="stylesheet" href="/core/css/styles.css?v=0a89f                                                            29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/header.css?v=0a89f                                                            29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/mobile.css?v=0a89f                                                            29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/icons.css?v=0a89f2                                                            9ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/fonts.css?v=0a89f2                                                            9ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/apps.css?v=0a89f29                                                            ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/fixes.css?v=0a89f2                                                            9ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/multiselect.css?v=                                                            0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/vendor/jquery-ui/theme                                                            s/base/jquery-ui.css?v=0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/jquery-ui-fixes.cs                                                            s?v=0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/jquery-tipsy.css?v                                                            =0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/jquery.ocdialog.cs                                                            s?v=0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/share.css?v=0a89f2                                                            9ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/apps/files_versions/css/ver                                                            sions.css?v=0a89f29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/styles.css?v=0a89f                                                            29ef91a7496f04c90005c3c295b" media="screen">
                                        <link rel="stylesheet" href="/core/css/header.css?v=0a89f                                                            29ef91a7496f04c90005c3c295b" media="screen">
                                                        <script src="/core/vendor/jquery/jquery.m                                                            in.js?v=0a89f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/jquery-migrate/jquery-migrate.m                                                            in.js?v=0a89f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.j                                                            s?v=0a89f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/underscore/underscore.js?v=0a89        
f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/moment/min/moment-with-locales.                                                            js?v=0a89f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/handlebars/handlebars.js?v=0a89                                                            f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/vendor/blueimp-md5/js/md5.js?v=0a89f29                                                            ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/js/placeholders.js?v=0a89f29ef91a7496f                                                            04c90005c3c295b"></script>
                                        <script src="/core/js/jquery-tipsy.js?v=0a89f29ef91a7496f                                                            04c90005c3c295b"></script>
                                        <script src="/core/js/compatibility.js?v=0a89f29ef91a7496                                                            f04c90005c3c295b"></script>
                                        <script src="/core/js/jquery.ocdialog.js?v=0a89f29ef91a74                                                            96f04c90005c3c295b"></script>
                                        <script src="/core/js/oc-dialogs.js?v=0a89f29ef91a7496f04                                                            c90005c3c295b"></script>
                                        <script src="/core/js/js.js?v=0a89f29ef91a7496f04c90005c3                                                            c295b"></script>
                                        <script src="/core/js/l10n.js?v=0a89f29ef91a7496f04c90005                                                            c3c295b"></script>
                                        <script src="/core/js/octemplate.js?v=0a89f29ef91a7496f04                                                            c90005c3c295b"></script>
                                        <script src="/core/js/eventsource.js?v=0a89f29ef91a7496f0                                                            4c90005c3c295b"></script>
                                        <script src="/core/js/config.js?v=0a89f29ef91a7496f04c900                                                            05c3c295b"></script>
                                        <script src="/core/search/js/search.js?v=0a89f29ef91a7496                                                            f04c90005c3c295b"></script>
                                        <script src="/core/js/oc-requesttoken.js?v=0a89f29ef91a74                                                            96f04c90005c3c295b"></script>
                                        <script src="/core/js/apps.js?v=0a89f29ef91a7496f04c90005                                                            c3c295b"></script>
                                        <script src="/core/vendor/snapjs/dist/latest/snap.js?v=0a                                                            89f29ef91a7496f04c90005c3c295b"></script>
                                        <script src="/core/js/placeholder.js?v=0a89f29ef91a7496f0                                                            4c90005c3c295b"></script>
                                        <script src="/core/js/jquery.avatar.js?v=0a89f29ef91a7496                                                            f04c90005c3c295b"></script>
                                        <script src="/core/js/avatar.js?v=0a89f29ef91a7496f04c900                                                            05c3c295b"></script>
                                        <script src="/core/js/backgroundjobs.js?v=0a89f29ef91a749                                                            6f04c90005c3c295b"></script>
                                        <script src="/core/js/share.js?v=0a89f29ef91a7496f04c9000                                                            5c3c295b"></script>
                                        <script src="/apps/files_sharing/js/share.js?v=0a89f29ef9                                                            1a7496f04c90005c3c295b"></script>
                                        <script src="/apps/files_sharing/js/external.js?v=0a89f29                                                            ef91a7496f04c90005c3c295b"></script>
                                        <script src="/apps/files_versions/js/versions.js?v=0a89f2                                                            9ef91a7496f04c90005c3c295b"></script>
                                        </head>
        <body id="body-login">
                <noscript>
        <div id="nojavascript">
                <div>
                        This application requires JavaScript for correct operation. Please <a hre                                                            f="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and relo                                                            ad the page.            </div>
        </div>
</noscript>
                <div class="wrapper">
                        <div class="v-align">
                                                                        <header role="banner">
                                                <div id="header">
                                                        <div class="logo svg">
                                                                <h1 class="hidden-visually">
                                                                        ownCloud                <                                                            /h1>
                                                        </div>
                                                        <div id="logo-claim" style="display:none;                                                            "></div>
                                                </div>
                                        </header>
                                                                <span class="error error-wide">
        <h2><strong>Internal Server Error</strong></h2>
                <p>The server encountered an internal error and was unable to complete your reque                                                            st.</p>
                <p>Please contact the server administrator if this error reappears multiple times                                                            , please include the technical details below in your report.</p>
                <p>More details can be found in the server log.</p>
        <br>

        <h2><strong>Technical details</strong></h2>
        <ul>
                <li>Remote Address: 192.168.1.200</li>
                <li>Request ID: uQ07l/p3WwZ9vSg0k1Ge</li>
                        </ul>

        </span>
                                <div class="push"></div><!-- for sticky footer -->
                        </div>
                </div>
                <footer role="contentinfo">
                        <p class="info">
                                <a href="https://owncloud.org" target="_blank" rel="noreferrer">o                                                            wnCloud</a> – web services under your control                   </p>
                </footer>
        </body>
</html>
```

**Comment by enoch85** [comment]
I looked in access.log and this is what I found

**Android**
```
192.168.1.200 - demoadmin [25/Sep/2015:13:10:17 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1533 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"
192.168.1.200 - demoadmin [25/Sep/2015:13:10:17 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3628 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"
192.168.1.200 - demoadmin [25/Sep/2015:13:10:17 +0200] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=false&subfiles=true HTTP/1.1" 200 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"
```
**Client:**
```
192.168.1.200 - - [25/Sep/2015:13:12:02 +0200] "PROPFIND http://example.com/remote.php/webdav/ HTTP/1.1" 401 980 "-" "Mozilla/5.0 (Windows) mirall/2.0.1"
192.168.1.200 - demouser [25/Sep/2015:13:12:02 +0200] "PROPFIND http://example.com/remote.php/webdav/ HTTP/1.1" 500 950 "-" "Mozilla/5.0 (Windows) mirall/2.0.1"
```

**Comment by PVince81** [comment]
@guruz @ogoffart is the desktop client doing a PROPFIND on a full URL ?

**Comment by MorrisJobke** [comment]
> @guruz @ogoffart is the desktop client doing a PROPFIND on a full URL ?

That looks wrong. HTTP doesn't use the domain and protocol in that line (it's already in the HTTP headers)

**Comment by enoch85** [comment]
@MorrisJobke Just looked in a access.log on a server that doesn't run behind a proxy, and there the client did a PROPFIND against the correct address `/remote.php/webdav/`. Do you (or someone else) have a clue what to do here?

**Comment by MorrisJobke** [comment]
This simply looks like a wrong request

**Comment by enoch85** [comment]
@MorrisJobke Ok, so what can I do about it? :)

**Comment by enoch85** [comment]
I tested on another computer outside my network, and it worked. 

Sorry for the noise.
