### ISSUE TITLE
Client Window keeps popping up on Ubuntu 14.04

### ISSUE THREAD

**Issue by leftyfb** [owncloud/client#4065]
### Expected behaviour
Owncloud window stays closed and docked after closing window.

### Actual behaviour
Window keeps opening up on it's own

### Steps to reproduce
1. Boot computer
2. Close owncloud window
3. window pops back up on it's own

### Server configuration
Operating system:
Ubuntu 12.04.5

Web server: 
apache 2.2.22-1ubuntu1.10

Database:
mysql-server 5.5.46-0ubuntu0.12.04.2

PHP version:
php5 5.4.45-2+deb.sury.org~precise+2

ownCloud version:
owncloud 8.1.3-13.1

Storage backend:
ext4

### Client configuration
Client version:
owncloud-client 2.0.2-3

Operating system:
Ubuntu 14.04.3

OS language:
English

Installation path of client:
/var/www/owncloud

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
http://pastebin.com/d9ixtyhM

2. Web server error log:
[Mon Nov 02 19:31:49 2015] [error] [client 128.199.95.16] File does not exist: /var/www/owncloud/l27.zip

3. ownCloud log (data/owncloud.log):
{"reqId":"s6XV8wP4zQ8ecs0pG3mY","remoteAddr":"<removed>","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-03T15:58:08+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"3OzlDsXLlNR6H77+9KsE","remoteAddr":"<removed>","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-03T15:58:36+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}

**Comment by guruz** [comment]
How often does the Window pop back in?

I believe this might be fixed in the 2.1 nightlies...

**Comment by leftyfb** [comment]
It pops up 3 times and at that point gives up. I guess I never made it to 4, getting frustrated and closing the whole application after 1 or 2 times popping up.

**Comment by Dianafg76** [comment]
@leftyfb could you install this version: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.5606-nightly20151106-setup.exe, please.
And try again
Thanks

**Comment by tps800** [comment]
Same her. After login in ownCloud-Client opens its window while starting. The windows version does not have this behaviour. I've only seeing it with linux and only with GNOME- or XFCE-Desktops

**Comment by leftyfb** [comment]
@Dianafg76 As I posted above per your template for bugs, I am not running Windows so your .exe file won't work.

**Comment by guruz** [comment]
@tps800 You say it is only after login..
For @leftyfb it is continously doing that for no good reason!?

**Comment by tps800** [comment]
It is after login. I can then minimize the client to my taskbar and it stays there until I logoff and on again.

**Comment by guruz** [comment]
Do you both still get this with 2.1?

**Comment by leftyfb** [comment]
Yes. In particular, I'm running version 2.1.0-1.1 on Ubuntu 14.04.3

**Comment by dragotin** [comment]
Have you checked the setting "General" "Launch on System Startup"? Is it on or off? Does tweeking it change the behaviour?

**Comment by leftyfb** [comment]
I have checked and unchecked that option. It only prevents OC from starting on bootup or not, as it should. No change to reported problem.

**Comment by guruz** [comment]
We've moved this to the next milestone since you're the only 2 reporting this at the moment.
If you can find out more it would be appreciated.

**Comment by ogoffart** [comment]
The main windows is opened when the owncloud program is run.  Is there anything like a script or so that tries to launch owncloud?

**Comment by dragotin** [comment]
Closing for inactivity. Please speak up if we need to reopen.

**Comment by leftyfb** [comment]
Still a problem on owncloud-client 2.1.1-1.1

**Comment by danimo** [comment]
@leftyfb: Still the same platform?

**Comment by leftyfb** [comment]
@danimo yes, Ubuntu 14.04.3 LTS using the following repository:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /

**Comment by ogoffart** [comment]
It won't happen with 2.2 based on Qt 5 on ubuntu 16.04 because of commit 0da2adcbe02eb9499e90622ca60a726ba75d0188
