### ISSUE TITLE
OC client keeps (unsuccesfully) syncing local files creating zillion new .*~* files that are copies of original files and filling up HD

### ISSUE THREAD

**Issue by mkfer** [owncloud/client#4251]
OC server 8.1.3
Client Win Version 2.0.2 (build 5569)

OC client keeps (unsuccesfully) syncing local files creating zillion new .*~* files that are copies of original files and filling up HD. This happens (mostly) with image file types ??? (but not exclusively). 
Client reports: Access is denied.
On the server there are number of fatar error messages such as:

Exception: {"Message":"An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path` = ?, `path_hash` = ? WHERE `fileid` = ?' with params [\"45\", \"files_trashbin\\\/files\\\/BParts.d1449229405\\\/Bob_l_thumb_ext.wrl\", \"67bdf59169705cd4548e6e82a5a1a93d\", \"33354\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '45-67bdf59169705cd4548e6e82a5a1a93d' for key 'fs_storage_path_hash'","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE `oc_file...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/owncloud\/lib\/private\/db.php(147): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/files\/cache\/cache.php(555): OC_DB::executeAudited(Object(OC_DB_StatementWrapper), Array)\n#5 \/var\/www\/owncloud\/lib\/private\/files\/cache\/cache.php(511): OC\\Files\\Cache\\Cache->moveFromCache(Object(OC\\Files\\Cache\\HomeCache), 'files\/Work_fer\/...', 'files_trashbin\/...')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/cache\/updater.php(178): OC\\Files\\Cache\\Cache->move('files\/Work_fer\/...', 'files_trashbin\/...')\n#7 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(227): OC\\Files\\Cache\\Updater->rename('\/files\/Work_fer...', '\/files_trashbin...')\n#8 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(152): OCA\\Files_Trashbin\\Trashbin::move2trash('Work_fer\/razvoj...')\n#9 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(105): OCA\\Files_Trashbin\\Storage->doDelete('files\/Work_fer\/...', 'rmdir')\n#10 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1006): OCA\\Files_Trashbin\\Storage->rmdir('files\/Work_fer\/...')\n#11 \/var\/www\/owncloud\/lib\/private\/files\/view.php(292): OC\\Files\\View->basicOperation('rmdir', '\/Work_fer\/razvo...', Array)\n#12 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(244): OC\\Files\\View->rmdir('\/Work_fer\/razvo...')\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OC\\Connector\\Sabre\\Directory->delete()\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(287): Sabre\\DAV\\Tree->delete('Work_fer\/razvoj...')\n#15 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#18 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#19 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#20 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#21 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66} 

Exception: {"Exception":"Exception","Message":"\\OC_Image::_output(): \"image\/x-ms-bmp\" is not supported when forcing a specific output format","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/image.php(193): OC_Image->_output(NULL, 'image\/x-ms-bmp')\n#1 \/var\/www\/owncloud\/lib\/private\/preview.php(733): OC_Image->show(NULL)\n#2 \/var\/www\/owncloud\/core\/ajax\/preview.php(60): OC\\Preview->showPreview()\n#3 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#4 [internal function]: __lambda_func(Array)\n#5 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('?lambda_435', Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/core\/preview.p...')\n#7 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/image.php","Line":260} 

Exception: {"Exception":"Exception","Message":"\\OC_Image::_output(): \"image\/x-ms-bmp\" is not supported when forcing a specific output format","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/image.php(193): OC_Image->_output(NULL, 'image\/x-ms-bmp')\n#1 \/var\/www\/owncloud\/lib\/private\/preview.php(733): OC_Image->show(NULL)\n#2 \/var\/www\/owncloud\/core\/ajax\/preview.php(60): OC\\Preview->showPreview()\n#3 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#4 [internal function]: __lambda_func(Array)\n#5 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('?lambda_653', Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/core\/preview.p...')\n#7 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/image.php","Line":260} 

No matter what I tried, the syncing never ends, and those .*~* files are constantly being generated, so for each original file I get number of copies...

**Comment by mkfer** [comment]
I think I solved the issue by deleting the complete local folder and re sync-ing.
