### ISSUE TITLE
[2.1.0] [Linux] chunked upload fails due to missing authorization header in some put requests

### ISSUE THREAD

**Issue by xshadow** [owncloud/client#4312]
### Expected behaviour
If you upload a big file, it should be uploaded without any problems.

Big file: a file that has to be chunked into more than 3 to 5 (or more) parts. 

### Actual behaviour
If you upload a big file the upload fails due to a "internal server error". 

On Mac OSX there is no problem with the client.

### Steps to reproduce
1.  Run owncloud 8.2.1 and linux client 2.1.0
2. Try to sync a file that has to be chunked in more than 3 to 5 (or more) parts

### Server configuration
Operating system: Debian 8 

Web server: Apache2.4 / mod_fcgid

Database: mysql  Ver 14.14 Distrib 5.6.25, for debian-linux-gnu (x86_64)

PHP version: PHP 5.6.14-0+deb8u1

ownCloud version: 8.2.1(stable)

### Client configuration
Client version:  ownCloud version 2.1.0 / Using Qt 4.8.6

Operating system: Xubuntu 14.04 / Ubuntu 14.04

OS language: English

### Logs

1. Web server error log:

```
[Mon Dec 21 19:31:11.422277 2015] [fcgid:warn] [pid 11117:tid 140664566130432] (70008)Partial results are valid but processing is incomplete: [client 46.246.40.115:43876] mod_fcgid: can't get data from http client
```

2. ownCloud log (data/owncloud.log):

```
Dec 21 19:31:11 www ownCloud[11702]: {webdav} Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/var\/www\/cloud.foo.org\/www\/lib\/private\/connector\/sabre\/auth.php(154): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/cloud.foo.org\/www\/lib\/private\/connector\/sabre\/auth.php(127): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/cloud.foo.org\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/cloud.foo.org\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/cloud.foo.org\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/cloud.foo.org\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/cloud.foo.org\/www\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/cloud.foo.org\/www\/remote.php(137): require_once('\/var\/www\/cloud....')\n#9 {main}","File":"\/var\/www\/cloud.foo.org\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
```

## Investigation of this error case

So I started a local proxy to check if the client send the correct header. After some chunks the client stops sending an authorization header. And mod_fcgid terminates the upload.

Second chunk, with an auth header:
![screenshot - 22 12 2015 - 18 03 14](https://cloud.githubusercontent.com/assets/3142448/11968336/8bf3be26-a90b-11e5-8af9-f48c67839a8d.png)

Third chunk, without an auth header:
![screenshot - 22 12 2015 - 18 03 23](https://cloud.githubusercontent.com/assets/3142448/11968343/9f366934-a90b-11e5-86ee-1b4da936dfa4.png)

### Interesting side effect

Upload of the same file is working, if parallel connections for the client are limited to one: 
```
OWNCLOUD_MAX_PARALLEL=1 owncloud --logfile -
```

Upload via the webinterface of the same file is working too.

Upload a big file with the current MacOSX client and the same server works without any problems.

**Comment by guruz** [comment]
You blurred the ```oc_sessionPassphrase``` cookie.. is there another session cookie sent? (in the same line..)

**Comment by xshadow** [comment]
@guruz, nope, the session cookie is the same, as the first request / picture.

**Comment by guruz** [comment]
@PVince81 @ogoffart @dragotin @danimo  I've seen the ```HTTP\/1.1 401 No basic authentication headers were found``` in quite a few issues now. Shouldn't the cookies be enough to authenticate the request?

**Comment by guruz** [comment]
@xshadow I'm clueless why (when using 2.1) there is a difference between linux and OS X client..

**Comment by guruz** [comment]
@xshadow Which error are you getting on the client side for a failing chunk? What is displayed there?

**Comment by xshadow** [comment]
```sh

01-04 13:54:02:380 0x800460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-3547168894-27-3" 
01-04 13:54:02:380 0x800460 Upload chunk 4 of 27 transferid(remote)= 3547168894 
01-04 13:54:02:381 0x800460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-3547168894-27-4" 
01-04 13:54:02:382 0x800460 Upload chunk 5 of 27 transferid(remote)= 3547168894 
01-04 13:54:02:383 0x800460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-3547168894-27-5" 
01-04 13:54:08:788 0x800460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-3547168894-27-3" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
01-04 13:54:08:789 0x800460 "DELETE FROM blacklist WHERE path=?1" "123.mp3" 
01-04 13:54:08:789 0x800460 "INSERT OR REPLACE INTO uploadinfo (path, chunk, transferid, errorcount, size, modtime) VALUES ( ?1 , ?2, ?3 , ?4 ,  ?5, ?6 )" "123.mp3" 4 -750944130 0 
01-04 13:54:08:789 0x800460 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "Upload info" and starting new transaction 
01-04 13:54:08:789 0x800460 Upload chunk 6 of 27 transferid(remote)= 3547168894 
01-04 13:54:08:793 0x800460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-3547168894-27-6" 
01-04 13:54:08:943 0x800460 void OCC::AbstractNetworkJob::slotFinished() 299 "Error downloading https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-3547168894-27-4 - server replied: Internal Server Error" QVariant(int, 500) 
01-04 13:54:08:943 0x800460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-3547168894-27-4" )  FINISHED WITH STATUS 299 "Error downloading https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-3547168894-27-4 - server replied: Internal Server Error" QVariant(int, 500) QVariant(QString, "Internal Server Error") 
01-04 13:54:08:943 0x800460 "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 admin@foo.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
" 
01-04 13:54:08:943 0x800460 virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0xee6970) "123.mp3" 
01-04 13:54:08:943 0x800460 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, )
```

**Comment by guruz** [comment]
@xshadow Thanks! And you're 100% confident that this is also the one without ```Authorization``` header? And all other requests have such header?

**Comment by xshadow** [comment]
Yes I'm. As you can see, chunk number two raises this error. Chunk number one is canceled afterwards, due to the sync error, but also has no authorization header.

Is that possible that chunk number two is uploaded, before chunk number two? 

```bash

01-04 16:42:03:739 0x1b81460 Sync state changed for folder  "ownCloud1" :  "Sync Running" 
01-04 16:42:03:739 0x1b81460 Upload chunk 0 of 27 transferid(remote)= 2635610708 
01-04 16:42:03:742 0x1b81460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-2635610708-27-0" 
01-04 16:42:03:742 0x1b81460 Upload chunk 1 of 27 transferid(remote)= 2635610708 
01-04 16:42:03:744 0x1b81460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-2635610708-27-1" 
01-04 16:42:03:744 0x1b81460 Upload chunk 2 of 27 transferid(remote)= 2635610708 
01-04 16:42:03:747 0x1b81460 !!! OCC::PUTFileJob created for "https://cloud.foo.org" + "/123.mp3-chunking-2635610708-27-2" 
01-04 16:42:04:064 0x1b81460 Saving account "https://cloud.foo.org" 
01-04 16:42:04:064 0x1b81460 Saving  1  unknown certs. 
01-04 16:42:04:064 0x1b81460 Saving cookies. 
01-04 16:42:04:065 0x1b81460 "/home/greg/.local/share/data//ownCloud//cookies.db" 
01-04 16:42:04:065 0x1b81460 Saved account settings, status: 0 
01-04 16:42:04:077 0x1b81460 Saving account "https://cloud.foo.org" 
01-04 16:42:04:077 0x1b81460 Saving  1  unknown certs. 
01-04 16:42:04:077 0x1b81460 Saving cookies. 
01-04 16:42:04:078 0x1b81460 "/home/greg/.local/share/data//ownCloud//cookies.db" 
01-04 16:42:04:078 0x1b81460 Saved account settings, status: 0 
01-04 16:42:25:278 0x1b81460 void OCC::ownCloudGui::slotShowSettings() 
01-04 16:42:25:302 0x1b81460 !!! OCC::PropfindJob created for "https://cloud.foo.org" + "/" 
01-04 16:42:25:309 0x1b81460 void OCC::AbstractNetworkJob::setTimeout(qint64) 60000 
01-04 16:42:25:310 0x1b81460 !!! OCC::LsColJob created for "https://cloud.foo.org" + "/" 
01-04 16:42:26:240 0x1b81460 Saving account "https://cloud.foo.org" 
01-04 16:42:26:240 0x1b81460 Saving  1  unknown certs. 
01-04 16:42:26:240 0x1b81460 Saving cookies. 
01-04 16:42:26:241 0x1b81460 "/home/greg/.local/share/data//ownCloud//cookies.db" 
01-04 16:42:26:241 0x1b81460 Saved account settings, status: 0 
01-04 16:42:30:284 0x1b81460 void OCC::AbstractNetworkJob::slotFinished() 299 "Error downloading https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-2 - server replied: Internal Server Error" QVariant(int, 500) 
01-04 16:42:30:284 0x1b81460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-2" )  FINISHED WITH STATUS 299 "Error downloading https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-2 - server replied: Internal Server Error" QVariant(int, 500) QVariant(QString, "Internal Server Error") 
01-04 16:42:30:284 0x1b81460 "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 admin@foo.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
" 
01-04 16:42:30:285 0x1b81460 virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0x22369d0) "123.mp3" 
01-04 16:42:30:285 0x1b81460 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
01-04 16:42:30:285 0x1b81460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-0" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(, ) QVariant(, ) 
01-04 16:42:30:285 0x1b81460 virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0x2239080) "123.mp3" 
01-04 16:42:30:285 0x1b81460 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
01-04 16:42:30:285 0x1b81460 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-1" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(, ) QVariant(, ) 
01-04 16:42:30:285 0x1b81460 blacklisting  "123.mp3"  for  25 , retry count  1 
01-04 16:42:30:285 0x1b81460 set blacklist entry for  "123.mp3" 1 "Error downloading https://cloud.foo.org/remote.php/webdav/123.mp3-chunking-2635610708-27-2 - server replied: Internal Server Error" 1451922150 25 1449496520 "" 

```

**Comment by guruz** [comment]
@xshadow Thanks, I'll try to find out why it would not send that header..

**Comment by skjnldsv** [comment]
Hi!
I just upgraded php7 on archlinux and I get those errors from my carddav and caldav sync app on android. I also got the error from the foldersync app (which should be using webdav i think)
The error on bot of those 3 app is: "Chunked stream ended unexpectedly"
Don't know if this help or not.

But this is the same error and bot of those app are giving <code>Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No basic authentication headers were found error</code>
Whole error:
<code>
Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No basic authentication headers were found
/usr/share/webapps/owncloud/lib/private/connector/sabre/auth.php - line 154: Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud')
/usr/share/webapps/owncloud/lib/private/connector/sabre/auth.php - line 127: OC\Connector\Sabre\Auth->auth(Object(OC\Connector\Sabre\Server), 'ownCloud')
/usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 118: OC\Connector\Sabre\Auth->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud')
[internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 456: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/usr/share/webapps/owncloud/apps/files/appinfo/remote.php - line 56: Sabre\DAV\Server->exec()
/usr/share/webapps/owncloud/remote.php - line 137: require_once('/usr/share/weba...')
{main}
</code>

**Comment by guruz** [comment]
@skjnldsv Interesting. If it only happens with PHP7 and you get it for a different client app (this repo is for the official ownCloud desktop sync client) then please also submit on https://github.com/owncloud/core .. (this issue is using PHP 5)

**Comment by guruz** [comment]
@xshadow Thanks a ton for the initial clue. Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 !
