### ISSUE TITLE
[Windows] [NGINX] [PHP7] 2.0.x "Verbindung Beendet" - "Connection Closed"

### ISSUE THREAD

**Issue by Berndinox** [owncloud/client#4332]
### Steps to reproduce
1. Install Owncloud 8.2 on Nginx + PHP7 with Openstack Swift Storage Backend as Default Storage
2. Install a Client newer then V2 on Windows
3. When trying to connect for the first time, after Entering your User Credentials there is the Error "Connection Closed"

### Expected behaviour
Should connect as with V1.8

### Actual behaviour
"Connection Closed" = "Verbindung Beendet". No more Errors.

### Server configuration
**OS:** Ubuntu 14.04

**Web server:** Nginx 1.9

**Database:** Mariadb 5

**PHP version:** 7.0.1

**ownCloud version:** 8.2

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - documents
  - encryption
  - external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```

{
    "system": {
        "activity_expire_days": 90,
        "instanceid": "oc26qblee771",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.berndklaus.at",
            "landjugend-tullnerfeld.tk"
        ],
        "datadirectory": "\/var\/www\/cloud.berndklaus.at\/data",
        "overwrite.cli.url": "https:\/\/cloud.berndklaus.at",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "zc99fbUqtumW",
                "password": "***REMOVED SENSITIVE VALUE***",
                "container": "owncloud",
                "autocreate": true,
                "region": "SBG1",
                "url": "https:\/\/auth.cloud.ovh.net\/v2.0",
                "tenantName": "xxxx",
                "serviceName": "swift"
            }
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "berndklaus.at",
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.zoho.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```

**Are you using external storage, if yes which one:** OpenStack Swift

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Operating System**: Windows 10

#### Web server error log
```

2016/01/04 08:51:18 [error] 10078#10078: *9263 readv() failed (104: Connection reset by peer) while reading upstream, client: 193.187.235.17, server: XXXXXX, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "xxxx"

```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/var\/www\/cloud.berndklaus.at\/lib\/private\/connector\/sabre\/auth.php(154): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/cloud.berndklaus.at\/lib\/private\/connector\/sabre\/auth.php(127): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/cloud.berndklaus.at\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/cloud.berndklaus.at\/remote.php(137): require_once('\/var\/www\/cloud....')\n#9 {main}","File":"\/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
```

**Comment by guruz** [comment]
Could you also check the php-fpm log for clues?

**Comment by guruz** [comment]
Does it work if you set "bandwidth limiting" to "Automatic" in the client?

**Comment by Berndinox** [comment]
There is no Error in the php-fom log. 
There is no difference if enable bandwidth limit or setting it to default.

I've also tried it with an comodo cert aswell as with a letsencrypt cert. This does not change anything.

BR

**Comment by skjnldsv** [comment]
@guruz That sounds exactly like what I have. It would explain the error I explained in #4312.
But I thin this isn"t coming from the client like you said. But from the core.

**Comment by guruz** [comment]
Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 for now. It's a combined core/client issue IMHO.
