### ISSUE TITLE
Windows client 2.1.0 (build 5683) does not synchronize shared files

### ISSUE THREAD

**Issue by crysman** [owncloud/client#4418]
We've just found out with my colleague that **Windows client 2.1 does not synchronize shared files** until logged-out/connect again or restarting the computer.

What is even worse, in "activity" it is logged, but physically, on the hard drive, nothing is being created/deleted. Tested on two independent windows machines (W7pro, W10) and two independent user accounts. In web interface, everything is OK, synchronized correctly.

My very obsolete (newest official) Xubuntu owncloud client (1.8.1+dsfg-1ubuntu1) does not have any problem and synchronizes everything correctly.

I've even tried to turn off the cache (memcache.local) in the owncloud config - has not helped. 

**How to debug this and get it fixed**? Thanks
### Steps to reproduce
1. Create a new dir in web client on account A
2. Share the dir with account B
3. Login to web client as "B" and see the directory - OK
4. Wait some time
5. See client's B owncloud directory in HDD if there is the new directory - no it is not
### Server configuration

```
⚡ ./ownclouddebuginfo.sh 
sudo -u ownclouduser php occ status
  - installed: true
  - version: 8.2.2.2
  - versionstring: 8.2.2
  - edition: 
sudo -u ownclouduser php occ app:list
Enabled:
  - activity: 2.1.3
  - external: 1.2
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - user_external: 0.4
Disabled:
  - calendar
  - contacts
  - conversations
  - documents
  - encryption
  - files_encryption
  - files_external
  - files_pdfviewer
  - files_videoviewer
  - firstrunwizard
  - galleryplus
  - notes
  - notifications
  - tasks
  - templateeditor
  - user_ldap
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:    7.9
Codename:   wheezy
mysql --version
mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
php --version
PHP 5.5.30-1~dotdeb+7.1 (cli) (built: Oct  1 2015 17:38:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
### Client configuration

Client version: 2.1.0

Operating system: W7P,W10

OS language: czech, english

Installation path of client: _default_
### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   Which lines are you interrested in? I cannot post here all the sensitiva information. Just give me a regexp to use to paste just some relevant lines here.
## 2. Web server error log:
1. ownCloud log (data/owncloud.log):
   latest ten rows (tail):

```
{"reqId":"M0j2faU\/\/pRHso4PouMa","remoteAddr":"89.24.124.xxx","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in \/var\/www\/owncloud\/core\/application.php on line 90 and defined at \/var\/www\/owncloud\/core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-02-01T09:46:51+00:00"}
{"reqId":"\/3Qnc\/ZJFzaAKb\/a4xa0","remoteAddr":"78.80.228.xxx","app":"PHP","message":"opendir(\/var\/www\/owncloud\/data\/majka\/files_trashbin\/files): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#96","level":3,"time":"2016-02-01T09:58:26+00:00"}
{"reqId":"0KVPLEXixNHamd73rNM8","remoteAddr":"78.80.228.xxx","app":"core","message":"Login failed: 'someuser' (Remote IP: '78.80.228.xxx')","level":2,"time":"2016-02-01T10:04:05+00:00"}
{"reqId":"4w0xLEWmpKY7K1AtnsjZ","remoteAddr":"78.80.228.xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(583): Sabre\\\\DAV\\\\Server->createCollection('IT\\\/Windows 10 U...', Array, Array)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1154}","level":4,"time":"2016-02-01T10:28:24+00:00"}
{"reqId":"adAONDuwLIEW5CNSs\/Wl","remoteAddr":"78.80.228.xxx","app":"PHP","message":"Undefined index: timeframe at \/var\/www\/owncloud\/themes\/mycompany\/apps\/activity\/templates\/email.notification.php#10","level":3,"time":"2016-02-01T10:28:52+00:00"}
{"reqId":"QCfBKKBx0PaPOR+XQYtH","remoteAddr":"78.80.228.xxx","app":"core","message":"Login failed: 'someuser' (Remote IP: '78.80.228.xxx')","level":2,"time":"2016-02-01T10:31:58+00:00"}
{"reqId":"XuDviIWJ+ME5c+1zwEQ5","remoteAddr":"78.80.228.xxx","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#363","level":3,"time":"2016-02-01T10:48:52+00:00"}
{"reqId":"aT7XSU9zTYLxgisXKx\/e","remoteAddr":"78.80.228.xxx","app":"PHP","message":"Undefined offset: 3 at \/var\/www\/owncloud\/lib\/private\/files\/view.php#264","level":3,"time":"2016-02-01T10:52:11+00:00"}
{"reqId":"PAzJEsvDLn3F3AiCfLTG","remoteAddr":"78.80.228.xxx","app":"no app in context","message":"Could not find mount point, can't keep encryption keys","level":3,"time":"2016-02-01T11:01:24+00:00"}
{"reqId":"raK9NhbwtxELlSywxZjp","remoteAddr":"78.80.228.xxx","app":"PHP","message":"Undefined index: timeframe at \/var\/www\/owncloud\/themes\/mycompany\/apps\/activity\/templates\/email.notification.php#10","level":3,"time":"2016-02-01T12:04:12+00:00"}
```

**Comment by guruz** [comment]
We're talking about an ownCloud share, not a Windows share right?

@LukasReschke this might still be a core issue? Especially given the stuff in the core log (which i'm not good in interpreting..)

**Comment by crysman** [comment]
Yes, owncloud share and windows OC client. Xubuntu client works just fine. Windows client worked also just fine until recently...

**Comment by bios-ben** [comment]
I'm having the same problem I believe with the Windows client, I was going to create a new ticket but this is probably the same issue. My Server Activity log says things changed on the server; however, my localhost doesn't actually download anything. If I click on my account and pause then resume, it'll then download the files that changed on the server. If @crysman you pause and resume (on account name by the share name 3 dots -> pause sync) does it start downloading the files?

**Comment by guruz** [comment]
Could you guys try 2.2.1?

**Comment by bios-ben** [comment]
It looks like it works now from my tests after updating. I will report back if it stops working but it's functioned properly for a few days now.
