### ISSUE TITLE
[Qt bug?] [X11] Crashes on screen resize

### ISSUE THREAD

**Issue by inducer** [owncloud/client#4419]
I observed this crash upon resizing my screen:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6eb63a0 in QScreen::handle() const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff6eb63a0 in QScreen::handle() const ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007fffe7c3d9d9 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#2  0x00007ffff75a6426 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff75a7a7c in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff75c5c2f in QWidgetPrivate::syncBackingStore() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff75f6e0d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff75f9c33 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff7599ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff759f4c6 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6b4eb6b in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6e8e17f in QGuiApplicationPrivate::processGeometryChangeEvent(QWindowSystemInterfacePrivate::GeometryChangeEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#11 0x00007ffff6e92fbd in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff6e76e38 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#13 0x00007fffe7c4ffd0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#14 0x00007ffff20c7fd7 in g_main_context_dispatch (context=0x7fffe00016f0) at /build/glib2.0-2.46.2/./glib/gmain.c:3154
#15 0x00007ffff20c7fd7 in g_main_context_dispatch (context=context@entry=0x7fffe00016f0) at /build/glib2.0-2.46.2/./glib/gmain.c:3769
#16 0x00007ffff20c8230 in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-2.46.2/./glib/gmain.c:3840
#17 0x00007ffff20c82dc in g_main_context_iteration (context=0x7fffe00016f0, may_block=1) at /build/glib2.0-2.46.2/./glib/gmain.c:3901
#18 0x00007ffff6ba52df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff6b4c2fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff6b543dc in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00005555555cbcc0 in main ()
```

I use the Debian package:

```
Package: owncloud-client
Version: 2.1.0+dfsg-1
Severity: wishlist

-- System Information:
Debian Release: stretch/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'stable-updates'), (500, 'unstable'), (500, 'stable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.4.0-trunk-amd64 (SMP w/4 CPU cores)
Locale: LANG=de_DE.utf8, LC_CTYPE=de_DE.utf8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages owncloud-client depends on:
ii  libc6                 2.21-7
ii  libgcc1               1:5.3.1-7
ii  libowncloudsync0      2.1.0+dfsg-1
ii  libqt5core5a          5.5.1+dfsg-13
ii  libqt5dbus5           5.5.1+dfsg-13
ii  libqt5gui5            5.5.1+dfsg-13
ii  libqt5keychain0       0.5.0-1
ii  libqt5network5        5.5.1+dfsg-13
ii  libqt5sql5-sqlite     5.5.1+dfsg-13
ii  libqt5webkit5         5.5.1+dfsg-2
ii  libqt5widgets5        5.5.1+dfsg-13
ii  libqt5xml5            5.5.1+dfsg-13
ii  libssl1.0.2           1.0.2f-2
ii  libstdc++6            5.3.1-7
ii  owncloud-client-l10n  2.1.0+dfsg-1

owncloud-client recommends no packages.

owncloud-client suggests no packages.

-- no debconf information
```

**Comment by guruz** [comment]
Did you check if there is an upstream bug at the Qt project bugtracker?

**Comment by inducer** [comment]
Actually, the issue seems to be suspend resume combined with screen resize.

**Comment by inducer** [comment]
Just tried with VLC (another app that uses Qt 5.5), and it crashes the same as the OC client. Looking like less of an owncloud issue at this point.

**Comment by inducer** [comment]
Seems to be this:
https://bugreports.qt.io/browse/QTBUG-45040
