### ISSUE TITLE
[Linux] Ubuntu 14.04: can't run client, SIGSEV signal from libQtNetwork

### ISSUE THREAD

**Issue by gentooza** [owncloud/client#4635]
### Expected behaviour
execute:
```
linux:~$ owncloud
```
and enjoy the owncloud client

### Actual behaviour
it returns a 'segment fault (core dumped)' error
gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff484d158 in ?? () from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
```
### Steps to reproduce
I think...
1. have ubuntu 14.04
2. have hacked the owncloud repositories in sources.list (opensuse repositories)
3. execute owncloud

### Server configuration
I think it's not important

### Client configuration
Client version:
```
linux:~$ owncloud --version
ownCloud version 2.1.1
Using Qt 4.8.6
```
Operating system:
x86_64 Ubuntu 14.04.4 LTS

Installation path of client:
added repository:
```
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /
```
installed by apt package manager

### Greetings
Hi! Thanks anyway! :-) If more information is needed here I am

**Comment by guruz** [comment]
@gentooza thanks. Would you run this in gdb and paste the output here: ```thread apply all backtrace```

**Comment by gentooza** [comment]
@guruz, here it is:  (I think, it's first time I use this option :-e)

```
Hilo 4 (Thread 0x7fffde988700 (LWP 10839)):
#0  0x00007ffff2a8a12d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff082bfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff082c0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff44967a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff44680af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff44683a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff4364c5f in QThread::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff436732f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007fffefb74182 in start_thread (arg=0x7fffde988700)
    at pthread_create.c:312
#9  0x00007ffff2a9747d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
```
Hilo 3 (Thread 0x7fffdf9c5700 (LWP 10834)):
#0  0x00007ffff2a8eda3 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff4446171 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff436732f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007fffefb74182 in start_thread (arg=0x7fffdf9c5700)
    at pthread_create.c:312
#4  0x00007ffff2a9747d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
```
Hilo 2 (Thread 0x7fffe7dbc700 (LWP 10833)):
#0  0x00007ffff2a8a12d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff082bfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff082c0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff44967a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff44680af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff44683a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff4364c5f in QThread::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff436732f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007fffefb74182 in start_thread (arg=0x7fffe7dbc700)
    at pthread_create.c:312
#9  0x00007ffff2a9747d in clone ()
```
```
Hilo 1 (Thread 0x7ffff7fa8800 (LWP 10829)):
#0  0x00007ffff484d158 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
#1  0x00007ffff4850cf3 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
#2  0x00007ffff48c295d in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
#3  0x00007ffff4481c1e in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff4f5de2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#5  0x00007ffff4f644a0 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007ffff44694dd in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff446cb3d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff4496f83 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff082be04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff082c048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff082c0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff44967a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff4fffbe6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007ffff44680af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#15 0x00007ffff44683a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#16 0x00007ffff446db79 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#17 0x000000000045b883 in main ()
```

**Comment by gentooza** [comment]
well, we can close this issue

Probably I had garbage in my package system:
+ I removed the opensuse repository, reinstalled the official ubuntu owncloud 1.5 client
+ tested it and it worked
+ added the opensuse repository again
+ upgraded it
+ it works now 2.1.1. client

I had to do something wrong, I think

**Comment by dragotin** [comment]
Yes, suspected that somehow. THanks for letting us know :-)
