### ISSUE TITLE
expected filesize x got y: Connection closed

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/client#4771]
The client refuses to sync a file in my ownCloud folder with the "connection closed" error.

### Steps to reproduce
No idea. This occurs from time to time to random files. Then it goes away equally spontaneously.

### Configuration
Please see https://github.com/owncloud/client/issues/4685. The configuration hasn't changed since I reported that issue.

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

`owncloud --logwindow` froze and `owncloud --logfile log.txt` generated 65 Mb worth of logs.

```
$ grep path/to/problematic/file log.txt
04-30 20:32:11:983 0x2f38ab0 csync_walker: file: /home/user/ownCloud/path/to/problematic/file [inode=20318465 size=2454334]
04-30 20:32:11:983 0x2f38ab0 _csync_detect_update: file: path/to/problematic/file, instruction: INSTRUCTION_EVAL <<=
04-30 20:32:16:038 0x2783b20 _csync_merge_algorithm_visitor: INSTRUCTION_SYNC     client file: path/to/problematic/file
04-30 20:32:18:966 0x2783b20 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: path/to/problematic/file
04-30 20:32:20:006 18288 OCC::AbstractNetworkJob::start: !!! OCC::PUTFileJob created for "https://my.owncloud.domain/owncloud" + "/path/to/problematic/file" ""
04-30 20:32:23:284 18288 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished() QUrl("https://my.owncloud.domain/owncloud/remote.php/webdav/path/to/problematic/file") FINISHED WITH STATUS 2 "Connection closed" QVariant(Invalid) QVariant(Invalid)
04-30 20:32:23:285 18288 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "path/to/problematic/file" INSTRUCTION_SYNC 1 "Connection closed"
04-30 20:32:23:877 18288 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Connection closed", "path/to/problematic/file: Connection closed")
```

2. Web server error log:

Nothing relevant.

3. ownCloud log (data/owncloud.log):

A lot of repetitions of this:

```
{"reqId":"2AEIg9zoz4RXwA99oqXd","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 2454334 got 8192\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1070): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #38)\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(511): Sabre\\\\DAV\\\\Server->updateFile('problematic\\\/file...', Resource id #38, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":149,\"User\":\"pastafarianist\"}","level":4,"time":"2016-04-30T17:32:23+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/problematic\/file","user":"pastafarianist"}

```

**Comment by guruz** [comment]
``` expected filesize x got y```
There's also a lot for this kind of issue in https://github.com/owncloud/core

Please check there.

**Comment by RealRancor** [comment]
And a whole FAQ here https://forum.owncloud.org/viewtopic.php?f=17&t=32517

**Comment by ogoffart** [comment]
This is a configuration issue and not a bug in the client.
