### ISSUE TITLE
Linux 2.0: "Backup detected"

### ISSUE THREAD

**Issue by Huster-at-github** [owncloud/client#4918]
### Expected behaviour
Server OC 9.0.2
Client on Ubuntu 16.04. was 2.1.1. Normal syncs were running, no problems.
Download- and Upload Bandwidth: Limit automatically

Updated to 2.2.0%nil (build 1605), reentered the password and get this message twice:

> This sync would reset the files to an erlier time in the sync folder 'owncloud/Fotos'.
> This might be because a backup was restored on the server.
> Continuing the sync as normal will cause all your files to be overwritten by an older file in an earlier state. Do you want to keep your local most recent files as conflict files?

Pressed "Normal Sync": No data errors or data loss (seems so).

Every time I choose "Normal Sync" I get this log entry:

### Server configuration
Operating system:
Ubuntu 16.04

Web server: 
Apache

Database:
MySQL

PHP version:
7.0.4

ownCloud version:
9.0.2

Storage backend:
local

### Client configuration
Client version:
Update from 2.1.1 to 2.2.0%nil (build 1605)

Operating system:
Ubuntu 16.04

OS language:
German

Installation path of client:
/usr/bin/

### Logs

```Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/dav\/lib\/server.php(144): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
- Killed process owncloud
- owncloud --logwindow
"Log Output" windows  freezed
process owncloud takes 100% CPU

2. Web server error log:
none

3. ownCloud log (data/owncloud.log):
see above

**Comment by Huster-at-github** [comment]
After a few reboots etc. client 2.2 works normally.

Except only English, can't access GUI by pressing "Recent Changes" etc. .... but that's another bug.  :-)
