### ISSUE TITLE
Internal Server Error: Client unable to sync files

### ISSUE THREAD

**Issue by mayarichman** [owncloud/client#4948]
### Expected behaviour
Client downloads folder structure from Owncloud Server

### Actual behaviour
Client throws Internal Server Error on different files within the largest folder (several GB's).

### Steps to reproduce
1. Login with owncloud credentials
2. Sync all folders
3. Pull out hair

### Server configuration
Operating system:
Debian 7.11

Web server: 
Apache

Database:
MySQL

PHP version:
PHP Version 5.4.45-0+deb7u3

ownCloud version:
ownCloud 8.2.5 (stable)

Storage backend:

### Client configuration
Client version:
Version 2.2.0%nil (build 1605). 

Operating System:
Ubuntu 14.04 LTS

OS language:
English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

https://gist.github.com/mayarichman/003e85b870cdcc0e9a1a6bdda6e2fe54

2. Web server error log:

```
[Tue Jun 07 06:25:04 2016] [warn] Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Tue Jun 07 06:25:04 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u3 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Tue Jun 07 06:25:04 2016] [warn] long lost child came home! (pid 13368)
[Tue Jun 07 07:09:59 2016] [error] [client 100.43.85.28] Directory index forbidden by Options directive: /var/www/alternc/a/admin/www/engn.it/
[Tue Jun 07 10:17:40 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:17:41 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:17:41 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:17:44 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:17:49 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:17:57 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:18:35 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:18:57 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:18:59 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:19:01 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:19:03 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:19:13 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:20:26 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:28:03 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:28:26 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:28:26 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:29:30 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:29:32 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:29:32 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/users (None could be negotiated).
[Tue Jun 07 10:29:36 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:29:43 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:29:43 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:30:12 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:33:48 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:07 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:11 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:11 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:17 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:17 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:19 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:20 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:22 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:22 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:25 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 10:34:25 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:04:50 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:14:20 2016] [error] [client 80.129.17.171] File does not exist: /var/www/alternc/a/admin/www/our-website.org/favicon.ico, referer: https://our-website.org/phpinfo.php
[Tue Jun 07 11:20:17 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:20:18 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:20:22 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:16 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:16 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:19 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:20 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:22 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
[Tue Jun 07 11:21:22 2016] [error] [client 80.129.17.171] Negotiation: discovered file(s) matching request: /var/www/alternc/a/admin/www/our-website.org/settings/admin (None could be negotiated).
```

3. ownCloud log (data/owncloud.log):

```
base	Exception: {"Exception":"ErrorException","Message":"session_start(): ps_files_cleanup_dir: opendir(\/var\/lib\/php5) failed: Permission denied (13)","Code":0,"Trace":"#0 [internal function]: OC\\Session\\Internal->trapError(8, 'session_start()...', '\/var\/www\/altern...', 44, Array)\n#1 \/var\/www\/alternc\/a\/admin\/www\/our-website.org\/lib\/private\/session\/internal.php(44): session_start()\n#2 \/var\/www\/alternc\/a\/admin\/www\/our-website.org\/lib\/base.php(411): OC\\Session\\Internal->__construct('ocd9uopog4sn')\n#3 \/var\/www\/alternc\/a\/admin\/www\/our-website.org\/lib\/base.php(566): OC::initSession()\n#4 \/var\/www\/alternc\/a\/admin\/www\/our-website.org\/lib\/base.php(1083): OC::init()\n#5 \/var\/www\/alternc\/a\/admin\/www\/our-website.org\/remote.php(87): require_once('\/var\/www\/altern...')\n#6 {main}","File":"\/var\/www\/alternc\/a\/admin\/www\/our-website.org\/lib\/private\/session\/internal.php","Line":106}
```

**Comment by guruz** [comment]
```
opendir(\/var\/lib\/php5) failed: Permission denied (13)
```
This is a setup/configuration issue on your server?

Does this error come for each file that fails?

You are saying some other files work?

**Comment by mayarichman** [comment]
Half of the files sync, just not the ones in larger sized folders. There are a ton of these Permission Denied errors I just added one.

**Comment by guruz** [comment]
@mayarichman Then look into fixing the permission error? :)

**Comment by dragotin** [comment]
Sorry, this is a bugtracker, please seek out for help on configuration on mailinglist or forum. Thanks.
