### ISSUE TITLE
owncloud client segmentation fault on start

### ISSUE THREAD

**Issue by horuga23** [owncloud/client#5144]
### Expected behaviour
Start the client

### Actual behaviour
segemtation fault on start in console

### Steps to reproduce
1. everytime on start
2. 
3. 

### Client configuration
Client version: 2.1.1, 2.2.3 (repo package or compiled) 

Operating system: openSuSE 13.2

OS language: DE

Installation path of client: /usr/bin

### Logs

```
(gdb) run
Starting program: /usr/bin/owncloud 
Got object file from memory but can't read symbols: File truncated.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe2e1c700 (LWP 29814)]
[New Thread 0x7fffd57b3700 (LWP 29827)]
[New Thread 0x7fffd4fb2700 (LWP 29828)]
Detaching after fork from child process 29829.
Detaching after fork from child process 29849.
Detaching after fork from child process 29889.
[New Thread 0x7fffc6e6c700 (LWP 29893)]

Program received signal SIGSEGV, Segmentation fault.
QHash (this=0x7fffc642cab0 <KAuth::s_watchers>) at /usr/include/QtCore/qhash.h:281
281         inline QHash() : d(&QHashData::shared_null) { d->ref.ref(); }
(gdb) backtrace
#0  0x00007fffc600422e in _GLOBAL__sub_I_kauthactionwatcher.cpp(void) (this=0x7fffc642cab0 <KAuth::s_watchers>) at /usr/include/QtCore/qhash.h:281
#1  0x00007fffc600422e in _GLOBAL__sub_I_kauthactionwatcher.cpp(void) (__initialize_p=1, __priority=65535) at /usr/src/debug/kdelibs-4.14.9/kdecore/auth/kauthactionwatcher.cpp:44
#2  0x00007fffc600422e in _GLOBAL__sub_I_kauthactionwatcher.cpp(void) () at /usr/src/debug/kdelibs-4.14.9/build/kdecore/kauthactionwatcher.moc:155
#3  0x00007ffff7dea8ea in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdc48, env=env@entry=0x7fffffffdc58) at dl-init.c:78
#4  0x00007ffff7dea9d3 in _dl_init (env=0x7fffffffdc58, argv=0x7fffffffdc48, argc=1, l=<optimized out>) at dl-init.c:36
#5  0x00007ffff7dea9d3 in _dl_init (main_map=main_map@entry=0xd3cce0, argc=1, argv=0x7fffffffdc48, env=0x7fffffffdc58) at dl-init.c:126
#6  0x00007ffff7deeb08 in dl_open_worker (a=a@entry=0x7fffffffc078) at dl-open.c:566
#7  0x00007ffff7dea7a4 in _dl_catch_error (objname=objname@entry=0x7fffffffc068, errstring=errstring@entry=0x7fffffffc070, mallocedp=mallocedp@entry=0x7fffffffc067, operate=operate@entry=0x7ffff7dee830 <dl_open_worker>, args=args@entry=0x7fffffffc078) at dl-error.c:187
#8  0x00007ffff7dee2fb in _dl_open (file=0xad6d18 "/usr/lib64/libproxy-0.4.11/modules/config_kde4.so", mode=-2147483647, caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffdc48, env=0x7fffffffdc58) at dl-open.c:650
#9  0x00007fffef7bb02b in dlopen_doit (a=a@entry=0x7fffffffc290) at dlopen.c:66
#10 0x00007ffff7dea7a4 in _dl_catch_error (objname=0x816ed0, errstring=0x816ed8, mallocedp=0x816ec8, operate=0x7fffef7bafd0 <dlopen_doit>, args=0x7fffffffc290) at dl-error.c:187
#11 0x00007fffef7bb5dd in _dlerror_run (operate=operate@entry=0x7fffef7bafd0 <dlopen_doit>, args=args@entry=0x7fffffffc290) at dlerror.c:163
#12 0x00007fffef7bb0c1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x00007fffef09ff25 in libmodman::module_manager::load_file(std::string, bool) (this=this@entry=0xa6a5e8, filename="/usr/lib64/libproxy-0.4.11/modules/config_kde4.so", symbreq=symbreq@entry=true) at /usr/src/debug/libmodman-2.0.1/libmodman/module_manager.cpp:250
#14 0x00007fffef0a02b3 in libmodman::module_manager::load_dir(std::string, bool) (this=this@entry=0xa6a5e8, dirname="/usr/lib64/libproxy-0.4.11/modules", symbreq=symbreq@entry=true)
    at /usr/src/debug/libmodman-2.0.1/libmodman/module_manager.cpp:327
#15 0x00007ffff3f91e06 in libproxy::proxy_factory::proxy_factory() (this=0xa6a5c0) at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:165
#16 0x00007ffff3f929bb in px_proxy_factory_new() (this=0xa6a5c0) at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:449
#17 0x00007ffff3f929bb in px_proxy_factory_new() () at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:454
#18 0x00007ffff72fc529 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) (this=0x7ffff758ee00 <(anonymous namespace)::Q_QGS_libProxyWrapper::innerFunction()::holder>)
    at kernel/qnetworkproxy_libproxy.cpp:55
#19 0x00007ffff72fc529 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) (this=0x7ffff758ee00 <(anonymous namespace)::Q_QGS_libProxyWrapper::innerFunction()::holder>)
    at kernel/qnetworkproxy_libproxy.cpp:72
#20 0x00007ffff72fc529 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) () at kernel/qnetworkproxy_libproxy.cpp:72
#21 0x00007ffff72fc529 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) (this=<optimized out>) at ../../src/corelib/global/qglobalstatic.h:135
#22 0x00007ffff72fc529 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) (query=...) at kernel/qnetworkproxy_libproxy.cpp:125
#23 0x00007ffff72f4411 in QSystemConfigurationProxyFactory::queryProxy(QNetworkProxyQuery const&) (this=<optimized out>, query=...) at ../../src/network/kernel/qnetworkproxy_p.h:66
#24 0x00007ffff72f3be4 in QGlobalNetworkProxy::proxyForQuery(QNetworkProxyQuery const&) (this=0x7ffff758ed40 <(anonymous namespace)::Q_QGS_globalNetworkProxy::innerFunction()::holder>, query=...) at kernel/qnetworkproxy.cpp:344
#25 0x00007ffff72f403a in QNetworkProxyFactory::proxyForQuery(QNetworkProxyQuery const&) (query=...) at kernel/qnetworkproxy.cpp:1568
#26 0x00007ffff72a2af0 in QNetworkAccessManagerPrivate::queryProxy(QNetworkProxyQuery const&) (this=0xda78e0, query=...) at access/qnetworkaccessmanager.cpp:1515
#27 0x00007ffff72c7db4 in QNetworkReplyHttpImplPrivate::postRequest(QNetworkRequest const&) (this=this@entry=0xa67710, newHttpRequest=...) at access/qnetworkreplyhttpimpl.cpp:651
#28 0x00007ffff72c9920 in QNetworkReplyHttpImplPrivate::start(QNetworkRequest const&) (this=this@entry=0xa67710, newHttpRequest=...) at access/qnetworkreplyhttpimpl.cpp:1701
#29 0x00007ffff72c9c5b in QNetworkReplyHttpImplPrivate::_q_startOperation() (this=this@entry=0xa67710) at access/qnetworkreplyhttpimpl.cpp:1757
#30 0x00007ffff72ca478 in QNetworkReplyHttpImpl::QNetworkReplyHttpImpl(QNetworkAccessManager*, QNetworkRequest const&, QNetworkAccessManager::Operation&, QIODevice*) (this=
    0xcf1c80, manager=<optimized out>, request=..., operation=<optimized out>, outgoingData=0x0) at access/qnetworkreplyhttpimpl.cpp:241
#31 0x00007ffff72a4112 in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (this=this@entry=0xc4ee40, op=op@entry=QNetworkAccessManager::GetOperation, req=..., outgoingData=outgoingData@entry=0x0) at access/qnetworkaccessmanager.cpp:1223
#32 0x00007ffff6ab49ec in OCC::AccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (this=
    0xc4ee40, op=QNetworkAccessManager::GetOperation, request=..., outgoingData=0x0) at /usr/src/debug/owncloudclient-2.1.1/src/libsync/accessmanager.cpp:72
#33 0x00007ffff72a08c4 in QNetworkAccessManager::get(QNetworkRequest const&) (this=0xc4ee40, request=...) at access/qnetworkaccessmanager.cpp:722
#34 0x00000000005557e6 in OCC::OCUpdater::checkForUpdate() (this=0xd9f900) at /usr/src/debug/owncloudclient-2.1.1/src/gui/updater/ocupdater.cpp:194
#35 0x0000000000556743 in OCC::OCUpdater::backgroundCheckForUpdate() (this=this@entry=0xd9f900) at /usr/src/debug/owncloudclient-2.1.1/src/gui/updater/ocupdater.cpp:124
#36 0x0000000000556df5 in OCC::PassiveUpdateNotifier::backgroundCheckForUpdate() (this=0xd9f900) at /usr/src/debug/owncloudclient-2.1.1/src/gui/updater/ocupdater.cpp:445
#37 0x0000000000556306 in OCC::UpdaterScheduler::slotTimerFired() (this=<optimized out>) at /usr/src/debug/owncloudclient-2.1.1/src/gui/updater/ocupdater.cpp:79
#38 0x00007ffff5c917d5 in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0xc6dc30, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=---Type <return> to continue, or q <return> to quit---
argv@entry=0x0) at kernel/qobject.cpp:3740
#39 0x00007ffff5c92367 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0xc6dc30, m=m@entry=0x7ffff60aae80 <QSingleShotTimer::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3602
#40 0x00007ffff5c9eb73 in QSingleShotTimer::timerEvent(QTimerEvent*) (this=0xc6dc30) at .moc/qtimer.moc:124
#41 0x00007ffff5c9eb73 in QSingleShotTimer::timerEvent(QTimerEvent*) (this=0xc6dc30) at kernel/qtimer.cpp:320
#42 0x00007ffff5c92cb4 in QObject::event(QEvent*) (this=0xc6dc30, e=<optimized out>) at kernel/qobject.cpp:1244
#43 0x00007ffff76f1b6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0xc6dc30, e=0x7fffffffd720) at kernel/qapplication.cpp:3799
#44 0x00007ffff76f8af0 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffda50, receiver=0xc6dc30, e=0x7fffffffd720) at kernel/qapplication.cpp:3556
#45 0x00007ffff5c69795 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0xc6dc30, event=0x7fffffffd720) at kernel/qcoreapplication.cpp:988
#46 0x00007ffff5cb794e in QTimerInfoList::activateTimers() (event=<optimized out>, receiver=<optimized out>) at ../../src/corelib/kernel/qcoreapplication.h:231
#47 0x00007ffff5cb794e in QTimerInfoList::activateTimers() (this=0x8d0a10) at kernel/qtimerinfo_unix.cpp:644
#48 0x00007ffff5cb7d01 in timerSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:182
#49 0x00007fffef4f7a04 in g_main_context_dispatch (context=0x7fffdc0016f0) at gmain.c:3111
#50 0x00007fffef4f7a04 in g_main_context_dispatch (context=context@entry=0x7fffdc0016f0) at gmain.c:3710
#51 0x00007fffef4f7c48 in g_main_context_iterate (context=context@entry=0x7fffdc0016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3781
#52 0x00007fffef4f7cec in g_main_context_iteration (context=0x7fffdc0016f0, may_block=1) at gmain.c:3842
#53 0x00007ffff5cb804b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x8cb980, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#54 0x00007ffff5c67a6b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffd960, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#55 0x00007ffff5c6f866 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1261
#56 0x00007ffff61b499c in QGuiApplication::exec() () at kernel/qguiapplication.cpp:1639
#57 0x00007ffff76f1ac5 in QApplication::exec() () at kernel/qapplication.cpp:2975
#58 0x0000000000474108 in main(int, char**) (argc=1, argv=<optimized out>) at /usr/src/debug/owncloudclient-2.1.1/src/gui/main.cpp:155


```

**Comment by guruz** [comment]
Please see my comment on https://github.com/owncloud/client/issues/4525#issuecomment-242708988 :)
