### ISSUE TITLE
[Windows] After upgrade to 2.4.0 client hangs

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/client#6272]
### Expected behaviour
Should work like before update

### Actual behaviour
Says there are unresolved conflicts and I should click to resolve them. I click and the client doesnt responed anymore. Also windows explorer doesnt responed anymore.

### Steps to reproduce
1. Open client

### Server configuration
Operating system: Debian 8

````
$ dpkg --list | grep -E 'mysql|apache|owncloud|php'
ii  apache2                        2.4.10-10+deb8u11                  amd64        Apache HTTP Server
ii  apache2-bin                    2.4.10-10+deb8u11                  amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                   2.4.10-10+deb8u11                  all          Apache HTTP Server (common files)
ii  apache2-doc                    2.4.10-10+deb8u11                  all          Apache HTTP Server (on-site documentation)
ii  apache2-suexec-custom          2.4.10-10+deb8u11                  amd64        Apache HTTP Server configurable suexec program for mod_suexec
ii  apache2-suexec-pristine        2.4.10-10+deb8u11                  amd64        Apache HTTP Server standard suexec program for mod_suexec
ii  apache2-utils                  2.4.10-10+deb8u11                  amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php5            5.6.30+dfsg-0+deb8u1               amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libdbd-mysql-perl              4.028-2+deb8u2                     amd64        Perl5 database interface to the MySQL database
ii  libmysqlclient18:amd64         5.5.58-0+deb8u1                    amd64        MySQL database client library
ii  mysql-client-5.5               5.5.58-0+deb8u1                    amd64        MySQL database client binaries
ii  mysql-common                   5.5.58-0+deb8u1                    all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                   5.5.58-0+deb8u1                    all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.5               5.5.58-0+deb8u1                    amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.5          5.5.58-0+deb8u1                    amd64        MySQL database server binaries
ii  owncloud                       9.1.6-1.1                          all          ownCloud - Server
ii  owncloud-deps-php5             9.1.6-1.1                          all          ownCloud - dependencies for php5
ii  owncloud-files                 9.1.6-1.1                          all          ownCloud - Server
ii  php-apc                        4.0.7-1                            all          APC User Cache for PHP 5 (transitional package)
ii  php-pear                       5.6.30+dfsg-0+deb8u1               all          PEAR - PHP Extension and Application Repository
ii  php-xml-parser                 1.3.4-7                            all          XML parsing class based on PHP's bundled expat
ii  php5                           5.6.30+dfsg-0+deb8u1               all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-apcu                      4.0.7-1                            amd64        APC User Cache for PHP 5
ii  php5-cli                       5.6.30+dfsg-0+deb8u1               amd64        command-line interpreter for the php5 scripting language
ii  php5-common                    5.6.30+dfsg-0+deb8u1               amd64        Common files for packages built from the php5 source
ii  php5-curl                      5.6.30+dfsg-0+deb8u1               amd64        CURL module for php5
ii  php5-gd                        5.6.30+dfsg-0+deb8u1               amd64        GD module for php5
ii  php5-imagick                   3.2.0~rc1-1                        amd64        Provides a wrapper to the ImageMagick library
ii  php5-intl                      5.6.30+dfsg-0+deb8u1               amd64        internationalisation module for php5
ii  php5-json                      1.3.6-1                            amd64        JSON module for php5
ii  php5-ldap                      5.6.30+dfsg-0+deb8u1               amd64        LDAP module for php5
ii  php5-mcrypt                    5.6.30+dfsg-0+deb8u1               amd64        MCrypt module for php5
ii  php5-mysqlnd                   5.6.30+dfsg-0+deb8u1               amd64        MySQL module for php5 (Native Driver)
ii  php5-pgsql                     5.6.30+dfsg-0+deb8u1               amd64        PostgreSQL module for php5
ii  php5-readline                  5.6.30+dfsg-0+deb8u1               amd64        Readline module for php5
ii  php5-sqlite                    5.6.30+dfsg-0+deb8u1               amd64        SQLite module for php5

````

Storage: Folder on the local HDD (ext4)

### Client configuration
Client version: 2.4.0

Operating system: Windows 7 64bit

OS language: DE

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
Doesnt output anything.

2. Web server error log:
````
ri Dec 29 06:25:02.097057 2017] [ssl:warn] [pid 1002] AH01906: owncloud.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Dec 29 06:25:02.097080 2017] [ssl:warn] [pid 1002] AH01909: owncloud.local:443:0 server certificate does NOT include an ID which matches the server name
[Fri Dec 29 06:25:02.097174 2017] [mpm_prefork:notice] [pid 1002] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Fri Dec 29 06:25:02.097179 2017] [core:notice] [pid 1002] AH00094: Command line: '/usr/sbin/apache2'
[Fri Dec 29 19:27:48.587892 2017] [authz_core:error] [pid 18940] [client 192.168.178.37:1122] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 19:59:52.447553 2017] [authz_core:error] [pid 18904] [client 192.168.178.37:4047] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 20:34:49.257519 2017] [authz_core:error] [pid 18940] [client 192.168.178.37:24917] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 21:08:39.458174 2017] [authz_core:error] [pid 18940] [client 192.168.178.37:35123] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 22:12:42.177803 2017] [authz_core:error] [pid 18905] [client 192.168.178.37:5884] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 22:43:56.925778 2017] [authz_core:error] [pid 18905] [client 192.168.178.37:6537] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 23:08:13.578551 2017] [authz_core:error] [pid 25068] [client 192.168.178.37:11885] AH01630: client denied by server configuration: /var/www/owncloud/config
[Fri Dec 29 23:29:48.993540 2017] [authz_core:error] [pid 25893] [client 192.168.178.37:12162] AH01630: client denied by server configuration: /var/www/owncloud/config

````

3. Server logfile: ownCloud log (data/owncloud.log):
````
{"reqId":"BNRuRBf6dFMh7hcJ3XWB","remoteAddr":"192.168.178.37","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 114688\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #58)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #58)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('foo', Resource id #58)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('foo', Resource id #58, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"user\"}","level":4,"time":"2017-12-29T23:13:54+01:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/foo","user":"user"}
{"reqId":"q2GMedN3dKgEcWEUeAcS","remoteAddr":"192.168.178.37","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 475136\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #58)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #58)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('foo', Resource id #58)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('foo', Resource id #58, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"user\"}","level":4,"time":"2017-12-29T23:15:19+01:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/foo","user":"user"}

````

### Possible other reasons:

- Self signed cert expired
- Game that created ~500 temp file. I removed them now
- Game that created ~92 savegames each 19 MB

**Comment by ogoffart** [comment]
Hi, 

Thanks for the report.  I will need additional information in order to investigate this issue.

Could you maybe send a screenshot that shows what the client is showing when it is frozen.

Do you have the logwindow enabled?  

Could you run the client with `--logfile log.txt  --logdebug --logflush`  and see the last items of log.txt when it freezes.  (and not --logwindow)

Would you be able to produce traces with gdb to see where it hangs?

**Comment by mueller-ma** [comment]
`C:\Program Files (x86)\ownCloud>owncloud.exe --logfile log.txt --logdebug --logflush`

Where should the log.txt appear?

After starting oc it searches for changed files
![1](https://user-images.githubusercontent.com/22525368/34481270-792596c2-efb1-11e7-93c5-1b2c44e47970.JPG)
Than it starts to copy files
![2](https://user-images.githubusercontent.com/22525368/34481271-79444dce-efb1-11e7-8c2f-ef1b2a360201.JPG)
Than this message appears
![3](https://user-images.githubusercontent.com/22525368/34481272-79614e9c-efb1-11e7-8018-427c878e858a.JPG)
And when I click on it:
![4](https://user-images.githubusercontent.com/22525368/34481273-797e4ace-efb1-11e7-8350-df313f346a9b.JPG)


The logfile in my home dir (.owncloudsync.log) shows me some INST_NEW and the last entry is INST_SYNC. So can I just rename the file and remove it from the server?

**Comment by ogoffart** [comment]
i think  it should appear  in the "current" directory. I don't know where it is.

Use `--logfile C:\log.txt` so it is created to the specified location.

**Comment by guruz** [comment]
> Use --logfile C:\log.txt so it is created to the specified location.

Windows might not allow to write there, better specify a good full path.

**Comment by mueller-ma** [comment]
I changed it to my home dir and now it writes the log. Waiting until it hangs again...

**Comment by mueller-ma** [comment]
I think I found the reason: It's just a GUI freeze, logging goes on.
Ubisoft's The Division creates a directory (C:\Users\user\Documents\My Games\Tom Clancy's The Division\ShaderCache\dx11) with ~15000 files. They once caused problems, but luckily the file type is .mcache, so I just added them to the ignore list.
Now in the logfile every second one entry like this is added:
```
01-02 12:44:15:868 [ info sync.propagator ]:    Starting INSTRUCTION_IGNORE propagation of "Documents/My Games/Tom Clancy's The Division/ShaderCache/dx11/b83d8863ca1aa4702f3.mcache" by OCC::PropagateIgnoreJob(0xe2f1a08)
01-02 12:44:15:868 [ warning sync.propagator ]: Could not complete propagation of "Documents/My Games/Tom Clancy's The Division/ShaderCache/dx11/b83d8863ca1aa4702f3.mcache" by OCC::PropagateIgnoreJob(0xe2f1a08) with status 6 and error: "Die Datei ist in der Ignorierliste gef▒hrt."
01-02 12:44:15:868 [ debug sync.statustracker ] [ OCC::SyncFileStatusTracker::slotItemCompleted ]:      Item completed "Documents/My Games/Tom Clancy's The Division/ShaderCache/dx11/b83d8863ca1aa4702f3.mcache" 6 32
```
So it needs 15000 seconds to go through this one folder.

**Comment by ckamm** [comment]
@mueller-ma Thanks for investigating!

We'd really like to know what triggered the gui-freeze, that should not happen! Do you still have the log file that was written while the gui was frozen?

Also, one `PropagateIgnoreJob` per second is not acceptable. The actual job execution takes 0ms as the logs show, so what's going on between those jobs?

If you have the full logs could you send them to me? mail at ckamm de

**Comment by ckamm** [comment]
I can reproduce the slowness in inserting to the issues widget and will fix that. Probably we both speed up the insertion as well as establish a maximum number of items.

**Comment by mueller-ma** [comment]
> To clarify, that freeze happens when you click on the "Für Details klicken" message? Then, possibly, the issue list view has a performance problem.

I think the freeze is unrelated to the click on "Für Details klicken".

The mentioned ignored files are 1KB to 40 KB large.

**Comment by wdsupport** [comment]
I am having same issue, since the update on client on windows , the owncloud client hang after checking for changes

**Comment by guruz** [comment]
@wdsupport @mueller-ma Have you tried a daily build https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.66-daily20180205-setup.exe ? Please report back.

**Comment by mueller-ma** [comment]
I havent tried, but I dont have any oh testing env and dont want to use unstable builds in my production env.

**Comment by wdsupport** [comment]
finally I use the daily latest version, and it stop hanging up, thanks mate, surely their was something in the version 2.4 that hang the software..

**Comment by guruz** [comment]
@wdsupport hooray :) 
Also confirmed to work in https://github.com/owncloud/client/issues/6344
