### ISSUE TITLE
[macOS only] 2.5.0 Client crashes when many files are to be synced

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6787]
### Expected behaviour
Client should sync without crashing

### Actual behaviour
There have been about +900 files to be synced after installation of the client.
- The client crashed always after syncing about 15-25 files and needed to be restarted.
*Many crash reports sent.*
- The DL speed after restarting the client was varying between 3-5MB/s or 23-25MB/s.
The files to be synced were music files, so sizes were all about the same.
Wondering where this speed difference is comeing from.
- When the complete sync was made, the client did not crash anymore, even I did change a view files.

### Steps to reproduce
1. Setup a sync with many files, some hundreds are optimal

### Server configuration
Operating system: Ubuntu 16.04

Web server: nginx

Database: mysql

PHP version: 7.1

ownCloud version: 10.0.10

Storage backend (external storage): smb
smb was working with the former sync client flawless.

### Client configuration
Client version: 2.5.0

Operating system: MacOS Mojave

OS language: DE

Installation path of client: default

### Logs

1. Client logfile: Client sent many crash reports

2. Web server error log: not relevant

3. Server logfile: ownCloud log (data/owncloud.log): not relevant

**Comment by michaelstingl** [comment]
@mmattel crash report window tells you an identifier. Could you post here the next time?

It would be also super helpful if you could capture client logs in the background. (F12-window with permanent option or start client with parameter) Here you can find more information: https://doc.owncloud.com/desktop/latest/troubleshooting.html#log-files

**Comment by mmattel** [comment]
> Could you post here the next time?

Will do.
Maybe you find the crash reports from yesterdayon your servers, time about 22-23h sent and in a relatively short period of time.

On the other hand side, I would be interested if this occurs on your side too if you give it a try...

**Comment by ckamm** [comment]
I'd guess it's this one: https://sentry.io/owncloud/desktop-win-and-mac/issues/231973066/events/31803969108/ - the only one with recent reports with 2.5.0 and OSX 10.14. 

Unfortunately it's one of those backtraces that's not useful for tracking down the issue. :/

@mmattel This is a long-standing bug (or cluster of bugs) that we haven't been able to track down. If you can reproduce this by retriggering an initial sync, it could be immensely helpful to capture logs (new logdir logging should make that much easier: https://doc.owncloud.org/desktop/2.5/troubleshooting.html#logging-to-a-temporary-directory) and potentially to attach a debugger and hopefully get a useful backtrace.

**Comment by mmattel** [comment]
@ckamm I will setup a new sync relation ship including an initial sync the next days and let you know the result.

**Comment by gabboman** [comment]
I also have the same bug. The bug report tool told me to tell this here:
bp-cee7e966-c5b4-48db-aa28-4a9482181002

**Comment by cdamken** [comment]
> bp-cee7e966-c5b4-48db-aa28-4a9482181002

@gabboman Can you look in your log files and search for this string?

**Comment by cdamken** [comment]
I can reproduce in my environment: I hope this helps

But the server error doesn't show to much information
```
"reqId":"b4f64fdd-21e7-46cd-bd16-53c22ca58dba","level":4,"time":"2018-10-04T12:25:34+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/admin\/manyfiles\/xaaaaaaahzo","message":"Exception: An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1538659483, \"files\\\/21c9d1a3914994435b1b667c6777cf67\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1538659483, \\\"files\\\\\\\/21c9d1a3914994435b1b667c6777cf67\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(170): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_file...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(657): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/21c9d1a39...', 1)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/manyfiles...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/manyfiles...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/manyfiles...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1975): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/manyfiles...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2078): OC\\\\Files\\\\View->lockPath('\\\/manyfiles\\\/xaaa...', 1, false)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1171): OC\\\\Files\\\\View->lockFile('\\\/manyfiles\\\/xaaa...', 1)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1029): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/manyfiles\\\/xaaa...', Array, 'rb')\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(393): OC\\\\Files\\\\View->fopen('manyfiles\\\/xaaaa...', 'rb')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}"}
```

The client log shows another error:

```
0-04 14:25:19:803 [ info sync.database ]:	Updating file record for path: "manyfiles/xaaaaaaaiuw" inode: 14690711 modtime: 1538655034 type: 0 etag: "8c3f57a53563e138036837c8e2555451" fileId: "00009004ocwqyst8qdgp" remotePerm: "WDNVR" fileSize: 10 checksum: "SHA1:9694c4ebd673a5e2fd26e4b2e64f92e914ebd95f"
10-04 14:25:19:805 [ info sync.propagator ]:	Completed propagation of "manyfiles/xaaaaaaaiuw" by OCC::PropagateDownloadFile(0x5635653285d0) with status 4
10-04 14:25:19:817 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("/tmp/TestClient/manyfiles/xaaaaaaaiuw")
10-04 14:25:19:836 [ info sync.propagator ]:	Starting INSTRUCTION_NEW propagation of "manyfiles/xaaaaaaaivu" by OCC::PropagateDownloadFile(0x5635606c3030)
10-04 14:25:19:839 [ info sync.accessmanager ]:	2 "" "http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaaivu" has X-Request-ID "76dae383-3a12-4fdf-b4c0-52240b60685e"
10-04 14:25:19:841 [ info sync.networkjob ]:	OCC::GETFileJob created for "http://localhost" + "/manyfiles/xaaaaaaaivu" "OCC::PropagateDownloadFile"
10-04 14:25:34:492 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(InternalServerError) "Server replied \"500 Internal Server Error\" to \"GET http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaahzo\"" QVariant(int, 500)
10-04 14:25:34:494 [ info sync.networkjob.get ]:	GET of "http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaahzo" FINISHED WITH STATUS "InternalServerError Server replied \"500 Internal Server Error\" to \"GET http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaahzo\"" "" "497"
10-04 14:25:34:497 [ info sync.database ]:	Setting blacklist entry for  "manyfiles/xaaaaaaahzo" 1 "Server replied \"500 Internal Server Error\" to \"GET http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaahzo\" (An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1538659483, \"files\\/21c9d1a3914994435b1b667c6777cf67\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction)" 1538655934 25 1538655034 "cb31fe5ea7d2b17e119ade867093537b" "" 0
10-04 14:25:34:499 [ warning sync.propagator ]:	Could not complete propagation of "manyfiles/xaaaaaaahzo" by OCC::PropagateDownloadFile(0x56355f78dc10) with status 2 and error: "Server replied \"500 Internal Server Error\" to \"GET http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaahzo\" (An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1538659483, \"files\\/21c9d1a3914994435b1b667c6777cf67\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction)"
10-04 14:25:34:520 [ info sync.propagator ]:	Starting INSTRUCTION_NEW propagation of "manyfiles/xaaaaaaaiwb" by OCC::PropagateDownloadFile(0x56355d9cd1a0)
10-04 14:25:34:527 [ info sync.accessmanager ]:	2 "" "http://localhost/remote.php/dav/files/admin/manyfiles/xaaaaaaaiwb" has X-Request-ID "a37ded41-087c-4369-9eba-ee1768071eb1"
10-04 14:25:34:529 [ info sync.networkjob ]:	OCC::GETFileJob created for "http://localhost" + "/manyfiles/xaaaaaaaiwb" "OCC::PropagateDownloadFile"
10-04 14:25:35:029 [ info sync.checksums ]:	Computing "SHA1" checksum of "/tmp/TestClient/manyfiles/.xaaaaaaaiwb.~6c65a1fd" in a thread
10-04 14:25:35:044 [ info sync.database ]:	Updating file record for path: "manyfiles/xaaaaaaaiwb" inode: 14690640 modtime: 1538655034 type: 0 etag: "e41d01e1836d41318fa02c1c39c8381c" fileId: "00011371ocwqyst8qdgp" remotePerm: "WDNVR" fileSize: 10 checksum: "SHA1:9694c4ebd673a5e2fd26e4b2e64f92e914ebd95f"
```

**Comment by mmattel** [comment]
For testing, I installed the client on W10x64 and setup a new sync relationship with the same items to sync.

On W10, the error did not occur like on macOS.
Seems to be something related to macOS only ?...

One interesting thing to note.
Download speed was continious about 200mbit/s which is in the range of where macOS top was, no drops.

**Comment by guruz** [comment]
> bp-cee7e966-c5b4-48db-aa28-4a9482181002

This is the also the weird Cocoa event dispatcher crash that @ckamm mentioned [two comments above](https://github.com/owncloud/client/issues/6787#issuecomment-425824382). (same backtrace)
https://sentry.io/owncloud/desktop-win-and-mac/issues/231973066/events/32020602185/
:-/ 

>  Seems to be something related to macOS only ?...

Happening also on 10.13 not only Mojave..

**Comment by guruz** [comment]
I can't find anything useful with https://bugreports.qt.io/browse/QTBUG-70341?jql=project%20%3D%20QTBUG%20AND%20text%20~%20%22QCocoaEventDispatcher%20processEvents%20crash%20HIToolbox%20appkit%20KERN_INVALID_ADDRESS%22%20ORDER%20BY%20created%20DESC

**Comment by guruz** [comment]
Both raw crash reports linked here contain a thread 1 with WebKit
```

Thread 1
 0  libsystem_kernel.dylib + 0x1ca16
    rax = 0x0000000002000131   rdx = 0x0000000000000000
    rcx = 0x0000700003bc1d98   rbx = 0x0000000000000000
    rsi = 0x0000000100000100   rdi = 0x000000010ceade10
    rbp = 0x0000700003bc1e30   rsp = 0x0000700003bc1d98
     r8 = 0x0000000000000000    r9 = 0x0000000000000060
    r10 = 0x0000000000000000   r11 = 0x0000000000000202
    r12 = 0x000000010ceade10   r13 = 0x0000700003bc1db8
    r14 = 0x0000000000000001   r15 = 0x0000700003bc2000
    rip = 0x00007fff68ea4a16
    Found by: given as instruction pointer in context
 1  libc++.1.dylib + 0x6cb0
    rbp = 0x0000700003bc1e40   rsp = 0x0000700003bc1e40
    rip = 0x00007fff66ca8cb0
    Found by: previous frame's frame pointer
 2  QtWebKit!void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 0x56
    rbp = 0x0000700003bc1e80   rsp = 0x0000700003bc1e50
    rip = 0x000000010c83c396
    Found by: previous frame's frame pointer
 3  QtWebKit!bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) + 0x9b
    rbp = 0x0000700003bc1ed0   rsp = 0x0000700003bc1e90
    rip = 0x000000010c83c29b
    Found by: previous frame's frame pointer
 4  QtWebKit!void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 0x28
    rbp = 0x0000700003bc1ef0   rsp = 0x0000700003bc1ee0
    rip = 0x000000010c83c458
    Found by: previous frame's frame pointer
 5  libsystem_pthread.dylib + 0x3661
    rbp = 0x0000700003bc1f20   rsp = 0x0000700003bc1f00
    rip = 0x00007fff6906c661
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x350d
    rbp = 0x0000700003bc1f50   rsp = 0x0000700003bc1f30
    rip = 0x00007fff6906c50d
    Found by: previous frame's frame pointer
 7  libsystem_pthread.dylib + 0x2bf9
    rbp = 0x0000700003bc1f78   rsp = 0x0000700003bc1f60
    rip = 0x00007fff6906bbf9
    Found by: previous frame's frame pointer
 8  QtWebKit!void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 0xf0
    rsp = 0x0000700003bc2028   rip = 0x000000010c83c430
    Found by: stack scanning
```

```
Thread 1
 0  libsystem_kernel.dylib + 0x41b2
    rax = 0x0000000002000131   rdx = 0x0000000000000000
    rcx = 0x0000700008c05dc8   rbx = 0x0000000000000002
    rsi = 0x0000000100000100   rdi = 0x0000000103cbde10
    rbp = 0x0000700008c05e50   rsp = 0x0000700008c05dc8
     r8 = 0x0000000000000000    r9 = 0x00000000000000a0
    r10 = 0x0000000000000000   r11 = 0x0000000000000202
    r12 = 0x0000000103cbde10   r13 = 0x0000000000000016
    r14 = 0x0000000100000100   r15 = 0x0000700008c06000
    rip = 0x00007fff62b191b2
    Found by: given as instruction pointer in context
 1  libc++.1.dylib + 0x7bda
    rbp = 0x0000700008c05e60   rsp = 0x0000700008c05e60
    rip = 0x00007fff600b4bda
    Found by: previous frame's frame pointer
 2  QtWebKit!void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 0x56
    rbp = 0x0000700008c05ea0   rsp = 0x0000700008c05e70
    rip = 0x000000010364c396
    Found by: previous frame's frame pointer
 3  QtWebKit!bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) + 0x9b
    rbp = 0x0000700008c05ef0   rsp = 0x0000700008c05eb0
    rip = 0x000000010364c29b
    Found by: previous frame's frame pointer
 4  QtWebKit!void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 0x28
    rbp = 0x0000700008c05f10   rsp = 0x0000700008c05f00
    rip = 0x000000010364c458
    Found by: previous frame's frame pointer
 5  libsystem_pthread.dylib + 0x333d
    rbp = 0x0000700008c05f30   rsp = 0x0000700008c05f20
    rip = 0x00007fff62bcf33d
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x62a7
    rbp = 0x0000700008c05f50   rsp = 0x0000700008c05f40
    rip = 0x00007fff62bd22a7
    Found by: previous frame's frame pointer
 7  libsystem_pthread.dylib + 0x2425
    rbp = 0x0000700008c05f78   rsp = 0x0000700008c05f60
    rip = 0x00007fff62bce425
    Found by: previous frame's frame pointer
```

**Comment by guruz** [comment]
@mmattel @gabboman You have at least 1 account configured in the client that uses OAuth2?

**Comment by mmattel** [comment]
@guruz no, I do not have any client configured that uses OAuth2. Not on the server and not on the client.

**Comment by guruz** [comment]
(Scratch my comment about OAuth2. I meant Shibboleth. Were we open a web view to login. But it's not possibly not related to that, there is a 2.4.3 crash without this WebKit thread https://sentry.io/owncloud/desktop-win-and-mac/issues/231973066/events/32738006597/ )

**Comment by mmattel** [comment]
Also no Shibboleth on my side...
Pure and native standard login.

**Comment by mmattel** [comment]
I will try to do my best getting asap for you.

**Comment by mmattel** [comment]
I tested today, same account, no changes on the server or setting side.
It is another Mac running HighSierra (LAN) and a W10x64 machine (WLAN)
Non of the syncs had an error and passed flawless :grimacing:

**Comment by guruz** [comment]
it's spontaneous crash in the macOS system libraries somewhere. But happy to hear it works now.
Maybe triggered by Qt (that we use), maybe not. So hard to reproduce. But there is definitely quite some people having this crash.

**Comment by mmattel** [comment]
The bad thing is, I can´t test on the MacBook (Mojave) of my doughter again - she needs it for school, and my other Macs are limited to High-Sierra (lovely Apple...)

**Comment by jnweiger** [comment]
## tested 252rc2 on macos 10.13.6 
* connected client to a local test server (fast connection)
* moved a tree of 3700 file into the sync folder. top level of the tree has 1100 files and many subdirs.
* client syncs perfectly fine to the server. OK-

* log out client from server
* remove 3700 files from client,
* log in back, -> keep files
* client syncs back everything fine. OK.

**Comment by jnweiger** [comment]
It probably needs a very specific setup to cause a crash? Structure of tree, direction, type of files, race conditions?

**Comment by mmattel** [comment]
Cant test atm as I am away from the mac where I coud do testing...

**Comment by ckamm** [comment]
@jnweiger Yes, we've never been able to systematically reproduce this problem. The best guess is that it's related to frequent opening and closing file-open dialogs that establish a connection to the sync client to show the right overlay icons for owncloud files.

**Comment by guruz** [comment]
As per the other issues, the crash is fixed :)
