### ISSUE TITLE
Delta-sync chunked upload runs into 423 Locked

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7262]
With 2.6 client:
- install owncloud/core master
- enable delta-sync in the client
- upload a large file (256MB in my case)
- either append a few bytes or change some early bytes
- the client uploads (a few?) chunks and the new zsync metadata then attempts the MOVE
- the MOVE of the update fails with "423 Locked"
- the client soft-errors and tries again, noticing the upload is already done
- but the MOVE fails again
- now the "z" permission somehow got lost and the next update uploads the full data

The file was in the root dir of the sync folder.

The 423 Locked shouldn't happen and the "z" permission should not get lost.

**Comment by ckamm** [comment]
Server log
```
{"reqId":"a4d5b845-c822-4dd9-a975-d314f3318a00","level":4,"time":"2019-06-20T11:15:36+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/admin\/3829735225\/.file.zsync","message":"Exception: HTTP\/1.1 423 "file" is locked: {"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Message":"\\"file\\" is locked","Code":0,"Trace":"#0 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/AssemblyStream.php(285): OCA\\DAV\\Connector\\Sabre\\File->get()\
#1 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/AssemblyStreamZsync.php(97): OCA\\DAV\\Upload\\AssemblyStream->getStream(Object(OCA\\DAV\\Connector\\Sabre\\File))\
#2 [internal function]: OCA\\DAV\\Upload\\AssemblyStreamZsync->stream_read(8192)\
#3 /var/www/owncloud/owncloud-20190620/lib/private/legacy/helper.php(305): fread(Resource id #43, 8192)\
#4 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/File.php(201): OC_Helper::streamCopy(Resource id #43, Resource id #48)\
#5 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/Directory.php(172): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #43)\
#6 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(311): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('file...', Resource id #43)\
#7 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(135): Sabre\\DAV\\Tree->copyNode(Object(OCA\\DAV\\Upload\\FutureFileZsync), Object(OCA\\DAV\\Connector\\Sabre\\Directory), 'file...')\
#8 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Tree.php(113): Sabre\\DAV\\Tree->copy('uploads/admin/3...', 'files/admin/WIS...')\
#9 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(167): OCA\\DAV\\Tree->copy('uploads/admin/3...', 'files/admin/WIS...')\
#10 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/ChunkingPluginZsync.php(142): Sabre\\DAV\\Tree->move('uploads/admin/3...', 'files/admin/WIS...')\
#11 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/ChunkingPluginZsync.php(62): OCA\\DAV\\Upload\\ChunkingPluginZsync->performMove('uploads/admin/3...', 'files/admin/WIS...')\
#12 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(96): OCA\\DAV\\Upload\\ChunkingPluginZsync->beforeMove('uploads/admin/3...', 'files/admin/WIS...')\
#13 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(632): Sabre\\DAV\\Server->emit('beforeMove', Array)\
#14 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
#15 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(464): Sabre\\DAV\\Server->emit('method:MOVE', Array)\
#16 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(241): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
#17 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(309): Sabre\\DAV\\Server->start()\
#18 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Server.php(305): Sabre\\DAV\\Server->exec()\
#19 /var/www/owncloud/owncloud-20190620/apps/dav/appinfo/v2/remote.php(31): OCA\\DAV\\Server->exec()\
#20 /var/www/owncloud/owncloud-20190620/remote.php(165): require_once('/var/www/ownclo...')\
#21 {main}","File":"/var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/File.php","Line":408}"}
```

**Comment by ckamm** [comment]
Likely a server issue, opening there.
