### ISSUE TITLE
removing and recreating a user causes internal server error when the user is still active

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7398]
Server 10.2.1, firefox browser.

When a user is removed from the system, he should be told so, when he tries to acess the system. Instead he may see an internal error.

Steps to reproduce:

* admin creates user Alice
* user Alice logs in on the web gui and sees her skeleton files.
* user Alice shortens the URL to the owncloud base URL and hits enter. She is returned to her folder view.
* admin deletes user Alice
* Alice clicks on folder 'Documents' and waits 10 seconds. She gets logged out and sees a login prompt on her web browser.
* admin creates user Alice without setting a password.
* (immediately within 10 seconds) user Alice shortens the URL to the owncloud base URL and hits enter. She gets an internal server error.

![image](https://user-images.githubusercontent.com/1108546/63104809-f1cce680-bf7f-11e9-9eaa-3ded41d528a9.png)

**Comment by jnweiger** [comment]
Last few lines from the server log:

```
{"reqId":"nhpDrh7vABHjUZgUjtHk","level":2,"time":"2019-08-15T15:13:41+00:00","remoteAddr":"127.0.0.1","user":"Alice","app":"core","method":"POST","url":"\/owncloud\/index.php\/login","message":"Login failed: 'Alice' (Remote IP: '127.0.0.1')"}
{"reqId":"iRKcOKVxHliprmDyOQY1","level":3,"time":"2019-08-15T15:13:53+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud-enterprise-complete-20190703\/data\/Alice for user: Alice which differs from existing value: "}
{"reqId":"iRKcOKVxHliprmDyOQY1","level":3,"time":"2019-08-15T15:13:53+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"settings","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"Can't send new user mail to a@ex.com: Expected response code 220 but got an empty response"}
{"reqId":"QBfD1Pdp5BNUhoZbheN1","level":3,"time":"2019-08-15T15:16:37+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud-enterprise-complete-20190703\/data\/Alice for user: Alice which differs from existing value: "}
{"reqId":"QBfD1Pdp5BNUhoZbheN1","level":3,"time":"2019-08-15T15:16:38+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"settings","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"Can't send new user mail to a@ex.com: Expected response code 220 but got an empty response"}
{"reqId":"Ngxvauemk2Q42iuRphrl","level":2,"time":"2019-08-15T15:19:52+00:00","remoteAddr":"127.0.0.1","user":"Alice","app":"core","method":"GET","url":"\/owncloud\/","message":"Login failed: 'Alice' (Remote IP: '127.0.0.1')"}
{"reqId":"Ngxvauemk2Q42iuRphrl","level":3,"time":"2019-08-15T15:19:52+00:00","remoteAddr":"127.0.0.1","user":"Alice","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/","message":"invalid credentials in token be5b45a0fdf782a05f1731f2465537bdb516e37c82a6eae31482b65899bc8c16af8a73271da7271d33d87bc0c947a02bb00994aba1a9e81e1e63a3a74bf3a0ac with token id 10"}
{"reqId":"rmNjrTRQezWKn5ZmI1zt","level":2,"time":"2019-08-15T15:20:15+00:00","remoteAddr":"127.0.0.1","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/login","message":"Login failed: 'alice' (Remote IP: '127.0.0.1')"}
{"reqId":"VA0uaM8DBSsPseaUbWQp","level":3,"time":"2019-08-15T15:21:17+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud-enterprise-complete-20190703\/data\/Alice for user: Alice which differs from existing value: "}
{"reqId":"VA0uaM8DBSsPseaUbWQp","level":3,"time":"2019-08-15T15:21:17+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"settings","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"Can't send new user mail to a@ex.com: Expected response code 220 but got an empty response"}
{"reqId":"GhGbZhVyPYPItNxLj3JE","level":3,"time":"2019-08-15T15:22:02+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud-enterprise-complete-20190703\/data\/Alice for user: Alice which differs from existing value: "}
{"reqId":"GhGbZhVyPYPItNxLj3JE","level":3,"time":"2019-08-15T15:22:02+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"settings","method":"POST","url":"\/owncloud\/index.php\/settings\/users\/users","message":"Can't send new user mail to a@ex.com: Expected response code 220 but got an empty response"}
{"reqId":"FmMfrreIpQTxYXBRtvrA","level":3,"time":"2019-08-15T15:22:10+00:00","remoteAddr":"127.0.0.1","user":"Alice","app":"index","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(134): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(207): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, NULL)\\n#3 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#4 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/base.php(911): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#8 \\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-enterprise-complete-20190703\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":585}"}
