### ISSUE TITLE
[QA] stops syncing while a modal dialog is open

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8170]
Seen with 2.7.0 RC1

The client is connected to multiple severs. One of them is demo.owncloud.org -- 
Whenever demo.owncloud.org resets, a "Remove All Files?" dialog is shown.

![image](https://user-images.githubusercontent.com/1108546/96114873-74379a00-0ee6-11eb-910e-bc44abac3c46.png)

While the dialog is open, the desktop client is completely blocked. The settings page is unresonsive, the tray icon is unresponsive. Nothing is synced.

Expected behaviour: syncing continues for all other folder sync connections. The GUI continues to respond.

**Comment by jnweiger** [comment]
The settings window as seen in the above screenshot can be minimized, while everything else is blocked. 
When the user does that, the dialog also disappears and the user can no longer unblock the client.

Calling `owncloud` on the shell re-opens the settings window and the dialog.


Now clicking on 'Remove all files' crashes the client.
```[2]+  Segmentation fault      (core dumped) owncloud```

A core file was not produced, although I have unlimited coredumpsize.

**Comment by TheOneRing** [comment]
You found on las occurence of dialog->exec().
Not blocking the others seems easy but I will need to prevent that one account from doing stuff before the user decides....

**Comment by jnweiger** [comment]
systemd incercepts coredumps. the core file is not generated, but a crude stack trace is stored in journalctl instead:
```
Oct 15 13:08:56 testy-ThinkPad-T480s kernel: owncloud[24839]: segfault at 118 ip 00007fda9d33348e sp 00007ffc2e51fbc0 error 4 in libowncloudsync.so.2.7.0[7fda9d27c000+112000]
Oct 15 13:08:56 testy-ThinkPad-T480s kernel: Code: 48 89 44 24 08 e8 32 99 f7 ff 48 8b 44 24 28 4c 8b 6b 50 8b 50 04 85 d2 0f 85 ee 09 00 00 48 8d 84 24 10 01 00 00 48 89 04 24 <41> 80 bd 18 01 00 00 00 74 14 8b 83 00 01 00 00 85 c0 75 0a c7 83
Oct 15 13:08:56 testy-ThinkPad-T480s systemd[1]: Started Process Core Dump (PID 15717/UID 0).
Oct 15 13:08:56 testy-ThinkPad-T480s systemd-coredump[15718]: Process 24839 (owncloud) of user 1000 dumped core.
                                                              
                                                              Stack trace of thread 24839:
                                                              #0  0x00007fda9d33348e _ZN3OCC10SyncEngine21slotDiscoveryFinishedEv (libowncloudsync.so.0)
                                                              #1  0x00007fda9bed760f _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                                              #2  0x00007fda9d2d50bd n/a (libowncloudsync.so.0)
                                                              #3  0x00007fda9bed760f _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                                              #4  0x00007fda9d2cc028 n/a (libowncloudsync.so.0)
                                                              #5  0x00007fda9bee44d4 n/a (libQt5Core.so.5)
                                                              #6  0x00007fda9bed805b _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                                                              #7  0x00007fda9cd7428c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                              #8  0x00007fda9cd7b890 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                              #9  0x00007fda9bea7a38 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                              #10 0x00007fda9bf03ee9 _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5)
                                                              #11 0x00007fda9bf046e9 n/a (libQt5Core.so.5)
                                                              #12 0x00007fda9966e417 g_main_context_dispatch (libglib-2.0.so.0)
                                                              #13 0x00007fda9966e650 n/a (libglib-2.0.so.0)
                                                              #14 0x00007fda9966e6dc g_main_context_iteration (libglib-2.0.so.0)
                                                              #15 0x00007fda9bf04a7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #16 0x00007fda9bea5c9a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #17 0x00007fda9beaee90 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                              #18 0x000056192459f460 n/a (owncloud)
                                                              #19 0x00007fda9b0e3b97 __libc_start_main (libc.so.6)
                                                              #20 0x000056192459fa4a _start (owncloud)
                                                              
                                                              Stack trace of thread 24896:
                                                              #0  0x00007fda9b1d6cf9 __GI___poll (libc.so.6)
                                                              #1  0x00007fda9966e5c9 n/a (libglib-2.0.so.0)
                                                              #2  0x00007fda9966e6dc g_main_context_iteration (libglib-2.0.so.0)
                                                              #3  0x00007fda9bf04a7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #4  0x00007fda9bea5c9a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #5  0x00007fda9bcbd22a _ZN7QThread4execEv (libQt5Core.so.5)
                                                              #6  0x00007fda9bcbe9d2 n/a (libQt5Core.so.5)
                                                              #7  0x00007fda9ac8d6db start_thread (libpthread.so.0)
                                                              #8  0x00007fda9b1e3a3f __clone (libc.so.6)
                                                              
                                                              Stack trace of thread 24872:
                                                              #0  0x00007fda9b1d6cf9 __GI___poll (libc.so.6)
                                                              #1  0x00007fda9966e5c9 n/a (libglib-2.0.so.0)
                                                              #2  0x00007fda9966e6dc g_main_context_iteration (libglib-2.0.so.0)
                                                              #3  0x00007fda9966e721 n/a (libglib-2.0.so.0)
                                                              #4  0x00007fda99696175 n/a (libglib-2.0.so.0)
                                                              #5  0x00007fda9ac8d6db start_thread (libpthread.so.0)
                                                              #6  0x00007fda9b1e3a3f __clone (libc.so.6)
                                                              
                                                              Stack trace of thread 24874:
                                                              #0  0x00007fda9b1d6cf9 __GI___poll (libc.so.6)
                                                              #1  0x00007fda9966e5c9 n/a (libglib-2.0.so.0)
                                                              #2  0x00007fda9966e962 g_main_loop_run (libglib-2.0.so.0)
                                                              #3  0x00007fda90bab276 n/a (libgio-2.0.so.0)
                                                              #4  0x00007fda99696175 n/a (libglib-2.0.so.0)
                                                              #5  0x00007fda9ac8d6db start_thread (libpthread.so.0)
                                                              #6  0x00007fda9b1e3a3f __clone (libc.so.6)
                                                              
                                                              Stack trace of thread 24865:
                                                              #0  0x00007fda9b1d6cf9 __GI___poll (libc.so.6)
                                                              #1  0x00007fda9966e5c9 n/a (libglib-2.0.so.0)
                                                              #2  0x00007fda9966e6dc g_main_context_iteration (libglib-2.0.so.0)
                                                              #3  0x00007fda9bf04a7f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #4  0x00007fda9bea5c9a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                              #5  0x00007fda9bcbd22a _ZN7QThread4execEv (libQt5Core.so.5)
                                                              #6  0x00007fda9bcbe9d2 n/a (libQt5Core.so.5)
                                                              #7  0x00007fda9ac8d6db start_thread (libpthread.so.0)
                                                              #8  0x00007fda9b1e3a3f __clone (libc.so.6)
                                                              
                                                              Stack trace of thread 31422:
                                                              #0  0x00007fda9b1d6cf9 __GI___poll (libc.so.6)

**Comment by TheOneRing** [comment]
as expected its a horrible mess

**Comment by jnweiger** [comment]
Reproduced the situation where the requester is open twice. Here is a proper stack trace, when closing them:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  OCC::ProcessDirectoryJob::processSubJobs (this=0x4400530045, nbJobs=nbJobs@entry=6) at ./src/libsync/discovery.cpp:1324

warning: Source file is more recent than executable.
1324	    if (_queuedJobs.empty() && _runningJobs.empty() && _pendingAsyncJobs == 0) {
[Current thread is 1 (Thread 0x7f8edda70800 (LWP 31444))]
(gdb) where
#0  0x00007f8edd775df2 in OCC::ProcessDirectoryJob::processSubJobs(int) (this=0x4400530045, nbJobs=nbJobs@entry=6) at ./src/libsync/discovery.cpp:1324
#1  0x00007f8edd775e56 in OCC::ProcessDirectoryJob::processSubJobs(int) (this=0x55e3e477e100, nbJobs=6) at ./src/libsync/discovery.cpp:1350
#2  0x00007f8edc38e4d4 in QSingleShotTimer::timerEvent(QTimerEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f8edc38205b in QObject::event(QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f8edd21e28c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f8edd225890 in QApplication::notify(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f8edc351a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f8edc3adee9 in QTimerInfoList::activateTimers() () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f8edc3ae6b1 in timerSourceDispatch(_GSource*, int (*)(void*), void*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f8ed9b18417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f8ed9b18650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f8ed9b186dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f8edc3aea7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f8edc34fc9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f8edd40bdd7 in QDialog::exec() () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x000055e3e2f6a998 in OCC::Folder::slotAboutToRemoveAllFiles(OCC::SyncFileItem::Direction, bool*) (this=0x55e3e4509130, dir=<optimized out>, cancel=0x7ffcf969b110) at ./src/gui/folder.cpp:1211
```

Is this also fixed with your commits above?

**Comment by TheOneRing** [comment]
It should be

**Comment by jnweiger** [comment]
Ah, should be, once https://github.com/owncloud/client/pull/8172 is merged :-)

Reproduced the crash today. But it is in a different location than above:
```
$ gdb /usr/bin/testpilotcloud ~/Downloads/Ubuntu_18.04/core.testpilotcloud.1603126981
Reading symbols from /usr/bin/testpilotcloud...Reading symbols from /usr/lib/debug/.build-id/fd/c6a0c1f156d7fa72e78ad9f2ac3286bae15629.debug...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `testpilotcloud'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  OCC::SyncEngine::slotDiscoveryFinished (this=0x55f21b664650) at ./src/libsync/syncengine.cpp:666

warning: Source file is more recent than executable.
666	    if (_discoveryPhase->_anotherSyncNeeded && _anotherSyncNeeded == NoFollowUpSync) {
[Current thread is 1 (Thread 0x7fe970a73800 (LWP 3920))]
(gdb) p _discoveryPhase
$1 = {d = 0x0}
(gdb) p _anotherSyncNeeded
$2 = OCC::NoFollowUpSync
(gdb) where
#0  0x00007fe9707dda5e in OCC::SyncEngine::slotDiscoveryFinished() (this=0x55f21b664650) at ./src/libsync/syncengine.cpp:666
#1  0x00007fe96f38160f in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fe97077f71d in OCC::DiscoveryPhase::<lambda()>::operator() (__closure=0x55f21bae6650) at ./src/libsync/discoveryphase.cpp:217
#3  0x00007fe97077f71d in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::DiscoveryPhase::startJob(OCC::ProcessDirectoryJob*)::<lambda()> >::call (arg=<optimized out>, f=...) at /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#4  0x00007fe97077f71d in QtPrivate::Functor<OCC::DiscoveryPhase::startJob(OCC::ProcessDirectoryJob*)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#5  0x00007fe97077f71d in QtPrivate::QFunctorSlotObject<OCC::DiscoveryPhase::startJob(OCC::ProcessDirectoryJob*)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x55f21bae6640, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:439
#6  0x00007fe96f38160f in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fe970776688 in OCC::ProcessDirectoryJob::processSubJobs(int) (this=0x55f21bb07dc0, nbJobs=6) at ./src/libsync/discovery.cpp:1345
#8  0x00007fe96f38e4d4 in QSingleShotTimer::timerEvent(QTimerEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fe96f38205b in QObject::event(QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fe97021e28c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fe970225890 in QApplication::notify(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fe96f351a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fe96f3adee9 in QTimerInfoList::activateTimers() () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fe96f3ae6e9 in idleTimerSourceDispatch(_GSource*, int (*)(void*), void*) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fe96cb18417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fe96cb18650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fe96cb186dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fe96f3aea7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fe96f34fc9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fe96f358e90 in QCoreApplication::exec() () at /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x000055f21b08f5f0 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ./src/gui/main.cpp:164
(gdb) 

```
