### ISSUE TITLE
[QA] AppImage client crashes when adding http://localhost:8080/server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8694]
Seen on Ubuntu 20.04, where already 3 other servers were connected.

![image](https://user-images.githubusercontent.com/1108546/121067183-091b3a80-c7cb-11eb-9d75-313a030f985a.png)

```
(gdb) run
Starting program: /home/testy/Downloads/ownCloud-2.9.0-daily20210607.4309.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 1524935]
process 1524931 is executing new program: /usr/bin/env
process 1524931 is executing new program: /bin/bash
[Detaching after fork from child process 1524940]
process 1524931 is executing new program: /tmp/.mount_ownClorRoDOj/usr/bin/owncloud
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff15b2700 (LWP 1524942)]
[New Thread 0x7fffe92c2700 (LWP 1524943)]
[New Thread 0x7fffe8ac1700 (LWP 1524944)]
warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so" (CRC mismatch).

[New Thread 0x7fffe3fff700 (LWP 1524945)]
[New Thread 0x7fffe37fe700 (LWP 1524946)]
warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqconnmanbearer.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqconnmanbearer.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqgenericbearer.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqgenericbearer.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqnmbearer.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/bearer/libqnmbearer.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqgif.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqgif.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqico.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqico.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqjpeg.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqjpeg.so" (CRC mismatch).

warning: the debug information found in "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqsvg.so.debug" does not match "/tmp/.mount_ownClorRoDOj/usr/plugins/imageformats/libqsvg.so" (CRC mismatch).

[Detaching after fork from child process 1524947]
[Detaching after fork from child process 1524949]
[New Thread 0x7fffe2a06700 (LWP 1524957)]
[New Thread 0x7fffe2205700 (LWP 1524958)]
[New Thread 0x7fffe1a04700 (LWP 1524959)]
[New Thread 0x7fffe11c9700 (LWP 1524960)]
[New Thread 0x7fffe09c8700 (LWP 1524961)]
[New Thread 0x7fffbffff700 (LWP 1524962)]
[New Thread 0x7fffbf7fe700 (LWP 1524963)]
[Thread 0x7fffbf7fe700 (LWP 1524963) exited]
[New Thread 0x7fffbf7fe700 (LWP 1524964)]
[Thread 0x7fffe2205700 (LWP 1524958) exited]
[New Thread 0x7fffe2205700 (LWP 1524965)]
[New Thread 0x7fffbeffd700 (LWP 1524966)]
[New Thread 0x7fffbe7fc700 (LWP 1524967)]
[New Thread 0x7fffbdffb700 (LWP 1524968)]
[Detaching after fork from child process 1524970]
[New Thread 0x7fffbd7fa700 (LWP 1524976)]
[New Thread 0x7fffbcff9700 (LWP 1524978)]
[New Thread 0x7fff9ffff700 (LWP 1524979)]
[Thread 0x7fffe2a06700 (LWP 1524957) exited]
[New Thread 0x7fffe2a06700 (LWP 1524982)]

Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x00005555555feeca in ?? ()
(gdb) where
#0  0x00005555555feeca in ?? ()
#1  0x00005555555d5e9e in ?? ()
#2  0x00007ffff6768270 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#3  0x00007ffff7131df7 in OCC::CheckServerJob::instanceFound(QUrl const&, QJsonObject const&) ()
   from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libowncloudsync.so.0
#4  0x00007ffff717eddd in OCC::CheckServerJob::finished() () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libowncloudsync.so.0
#5  0x00007ffff71798e9 in OCC::AbstractNetworkJob::slotFinished() () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libowncloudsync.so.0
#6  0x00007ffff6768270 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#7  0x00007ffff703f727 in QNetworkReplyHttpImplPrivate::finished() () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Network.so.5
#8  0x00007ffff7083846 in QNetworkReplyHttpImpl::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
   from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Network.so.5
#9  0x00007ffff67480e2 in QObject::event(QEvent*) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#10 0x00007ffff7e1cbdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff7e20820 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff6771788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#13 0x00007ffff677193c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#14 0x00007ffff67847a3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#15 0x00007ffff4ad7cca in g_main_context_dispatch () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libglib-2.0.so.0
#16 0x00007ffff4ad7f00 in ?? () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libglib-2.0.so.0
#17 0x00007ffff4ad7f8c in g_main_context_iteration () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libglib-2.0.so.0
#18 0x00007ffff677ea0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#19 0x00007ffff6861d5b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#20 0x00007ffff677d390 in QCoreApplication::exec() () from /tmp/.mount_ownClorRoDOj/usr/bin/../lib/libQt5Core.so.5
#21 0x000055555559df39 in ?? ()
#22 0x00007ffff60590b3 in __libc_start_main (main=0x55555559dc70, argc=1, argv=0x7fffffffd3e8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffd3d8) at ../csu/libc-start.c:308
#23 0x000055555559e51a in _start ()
(gdb) list
1	../sysdeps/unix/sysv/linux/dl-vdso-setup.c: No such file or directory.
(gdb)

**Comment by TheOneRing** [comment]
Your testing a two weeks old client.
The issue is already fixed.
