### ISSUE TITLE
[QA] 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8916]
Seen with 2.9.0-beta1 on Linux Mint 20.1

* after several hours of happy syncing,
* open the settings dialog, click the Quit button.
* SEGFAULT

```
⏚ 2& [testy:~/damkenCloud/tmp] $ gdb /usr/bin/owncloud /home/testy/core.owncloud.1000.2b90feecf2f1438ca109be1ca7571388.490561.1629297718000000000000
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/owncloud...
(No debugging symbols found in /usr/bin/owncloud)
[New LWP 490561]
[New LWP 490592]
[New LWP 490593]
[New LWP 752811]
[New LWP 490595]
[New LWP 490608]
[New LWP 490628]
[New LWP 739157]
[New LWP 741605]
[New LWP 752810]
[New LWP 490610]
[New LWP 753085]
[New LWP 498732]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `owncloud'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005582aa91c29b in ?? ()
[Current thread is 1 (Thread 0x7fccf8037800 (LWP 490561))]
(gdb) where
#0  0x00005582aa91c29b in  ()
#1  0x00007fccfb3767ed in QSortFilterProxyModel::lessThan(QModelIndex const&, QModelIndex const&) const ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fccfb3786a8 in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fccfb37ac2b in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fccfb37e401 in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fccfb381b86 in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fccfb382793 in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fccfb3cfe60 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fccfb350702 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fccfb3591c8 in QAbstractItemModel::endInsertRows() ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00005582aa91c660 in  ()
#11 0x00005582aa8f3cb8 in  ()
#12 0x00007fccfb3cffb8 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fccfb98958f in OCC::ProgressDispatcher::syncError(QString const&, QString const&, OCC::ErrorCategory) ()
    at /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/libowncloudsync.so.0
#14 0x00005582aa812b67 in  ()
#15 0x00007fccfb3cffb8 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fccfb989aca in OCC::SyncEngine::syncError(QString const&, OCC::ErrorCategory) ()
    at /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/libowncloudsync.so.0
#17 0x00007fccfba20b16 in OCC::SyncEngine::abort() ()
    at /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/libowncloudsync.so.0
#18 0x00007fccfba25998 in OCC::SyncEngine::~SyncEngine() ()
    at /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/libowncloudsync.so.0
#19 0x00007fccfba274ad in OCC::SyncEngine::~SyncEngine() ()
    at /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/libowncloudsync.so.0
#20 0x00005582aa81cf4a in  ()
#21 0x00005582aa81d3dd in  ()
#22 0x00007fccfb3d06d4 in QObject::event(QEvent*) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fccfc16ae06 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00007fccfc174300 in QApplication::notify(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fccfb3a446a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007fccfb3a70e8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fccfb3aad8f in QCoreApplication::exec() () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00005582aa80759c in  ()
#29 0x00007fccfabe50b3 in __libc_start_main (main=
    0x5582aa807390, argc=1, argv=0x7ffc7308d0a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc7308d098)
    at ../csu/libc-start.c:308
#30 0x00005582aa807cae in _start ()
(gdb) 
(gdb) 
```

**Comment by jnweiger** [comment]
Not reproducable...

**Comment by jnweiger** [comment]
@dschmidt @TheOneRing would #8930 possibly fix that?

**Comment by TheOneRing** [comment]
Nope

**Comment by dschmidt** [comment]
Agreed looks completely unrelated
