### ISSUE TITLE
[QA] Segfault after suspend/resume

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8950]
Seen with testpilotcloud 2.9.0-beta3 on Fedora33 (not the appimage)

```
$ gdb /usr/bin/testpilotcloud core
...
Reading symbols from /usr/bin/testpilotcloud...
Reading symbols from /usr/lib/debug/opt/ownCloud/testpilotcloud/bin/testpilotcloud-2.9.0-0.0.0.beta3.x86_64.debug...
[New LWP 7157]
[New LWP 7158]
[New LWP 7159]
[New LWP 7160]
[New LWP 7175]
[New LWP 7191]
[New LWP 7194]
[New LWP 7579]
[New LWP 7610]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `testpilotcloud -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  operator() (__closure=0x26a5c28) at /opt/ownCloud/qt-5.12.10/include/qt5/QtCore/qscopedpointer.h:116
[Current thread is 1 (Thread 0x7f00a4b2fd40 (LWP 7157))]
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.8-4.fc33.x86_64 dbus-libs-1.12.20-2.fc33.x86_64 fontconfig-2.13.92-12.fc33.x86_64 freetype-2.10.4-1.fc33.x86_64 glib2-2.66.8-1.fc33.x86_64 glibc-2.32-4.fc33.x86_64 graphite2-1.3.14-6.fc33.x86_64 harfbuzz-2.7.2-1.fc33.x86_64 libICE-1.0.10-4.fc33.x86_64 libSM-1.2.3-6.fc33.x86_64 libX11-1.6.12-3.fc33.x86_64 libXau-1.0.9-4.fc33.x86_64 libXcursor-1.2.0-3.fc33.x86_64 libXext-1.3.4-4.fc33.x86_64 libXfixes-5.0.3-12.fc33.x86_64 libXrender-0.9.10-12.fc33.x86_64 libblkid-2.36.1-1.fc33.x86_64 libbrotli-1.0.9-3.fc33.x86_64 libffi-3.1-26.fc33.x86_64 libgcc-10.2.1-9.fc33.x86_64 libgcrypt-1.8.7-1.fc33.x86_64 libgpg-error-1.41-1.fc33.x86_64 libicu-67.1-4.fc33.x86_64 libjpeg-turbo-2.0.5-5.fc33.x86_64 libmount-2.36.1-1.fc33.x86_64 libpng-1.6.37-6.fc33.x86_64 libsecret-0.20.4-1.fc33.x86_64 libselinux-3.1-2.fc33.x86_64 libstdc++-10.2.1-9.fc33.x86_64 libuuid-2.36.1-1.fc33.x86_64 libxcb-1.13.1-5.fc33.x86_64 libxml2-2.9.10-8.fc33.x86_64 libzstd-1.4.9-1.fc33.x86_64 nss-mdns-0.14.1-9.fc33.x86_64 ocqt51210-libQt5Concurrent5-5.12.10-14.1.x86_64 ocqt51210-libQt5Core5-5.12.10-14.1.x86_64 ocqt51210-libQt5DBus5-5.12.10-14.1.x86_64 ocqt51210-libQt5Gui5-5.12.10-14.1.x86_64 ocqt51210-libQt5Network5-5.12.10-14.1.x86_64 ocqt51210-libQt5Widgets5-5.12.10-14.1.x86_64 ocqt51210-libQt5Xml5-5.12.10-14.1.x86_64 ocqt51210-qt5keychain1-0.12.0-2.7.x86_64 openssl-libs-1.1.1k-1.fc33.x86_64 pcre-8.44-2.fc33.x86_64 pcre2-10.36-4.fc33.x86_64 pcre2-utf16-10.36-4.fc33.x86_64 sqlite-libs-3.34.1-1.fc33.x86_64 sssd-client-2.4.2-2.fc33.x86_64 systemd-libs-246.13-1.fc33.x86_64 xz-libs-5.2.5-4.fc33.x86_64 zlib-1.2.11-23.fc33.x86_64
(gdb) where
#0  operator() (__closure=0x26a5c28) at /opt/ownCloud/qt-5.12.10/include/qt5/QtCore/qscopedpointer.h:116
#1  0x00000000004568a5 in std::function<void (bool)>::operator()(bool) const (__args#0=false, this=0x1514d30)
    at /usr/include/c++/10/bits/std_function.h:622
#2  operator() (__closure=0x1514d20) at /usr/src/debug/testpilotcloud-client-2.9.0-0.0.0.beta3.x86_64/src/gui/folder.cpp:1238
#3  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::Folder::slotAboutToRemoveAllFiles(OCC::SyncFileItem::Direction, std::function<void(bool)>)::<lambda()> >::call (arg=<optimized out>, f=...)
    at /opt/ownCloud/qt-5.12.10/include/qt5/QtCore/qobjectdefs_impl.h:146
#4  QtPrivate::Functor<OCC::Folder::slotAboutToRemoveAllFiles(OCC::SyncFileItem::Direction, std::function<void(bool)>)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /opt/ownCloud/qt-5.12.10/include/qt5/QtCore/qobjectdefs_impl.h:256
#5  QtPrivate::QFunctorSlotObject<OCC::Folder::slotAboutToRemoveAllFiles(OCC::SyncFileItem::Direction, std::function<void(bool)>)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, 
    this_=0x1514d10, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /opt/ownCloud/qt-5.12.10/include/qt5/QtCore/qobjectdefs_impl.h:439
#6  0x00007f00a827bf9d in QMetaObject::activate(QObject*, int, int, void**) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#7  0x00007f00a927bb5e in QDialog::finished(int) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#8  0x00007f00a92aa919 in QMessageBoxPrivate::_q_buttonClicked(QAbstractButton*) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#9  0x00007f00a827be60 in QMetaObject::activate(QObject*, int, int, void**) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#10 0x00007f00a921dedf in QDialogButtonBox::clicked(QAbstractButton*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#11 0x00007f00a921e5af in QDialogButtonBoxPrivate::_q_handleButtonClicked() () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#12 0x00007f00a827be60 in QMetaObject::activate(QObject*, int, int, void**) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#13 0x00007f00a9187922 in QAbstractButton::clicked(bool) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#14 0x00007f00a918820c in QAbstractButtonPrivate::emitClicked() () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#15 0x00007f00a918967f in QAbstractButtonPrivate::click() () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#16 0x00007f00a9189821 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#17 0x00007f00a90e285e in QWidget::event(QEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#18 0x00007f00a90a6e82 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#19 0x00007f00a90adcd6 in QApplication::notify(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#20 0x00007f00a8253662 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#21 0x00007f00a90acda3 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#22 0x00007f00a90faad5 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#23 0x00007f00a90fd6fe in QWidgetWindow::event(QEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#24 0x00007f00a90a6e82 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Widgets.so.5
#25 0x00007f00a8253662 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#26 0x00007f00a8b22d50 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Gui.so.5
#27 0x00007f00a8afbedc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Gui.so.5
#28 0x00007f00975168ea in xcbSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /opt/ownCloud/qt-5.12.10/lib64/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#29 0x00007f00a72aba9f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#30 0x00007f00a72fda98 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#31 0x00007f00a72a8e73 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#32 0x00007f00a82a4a22 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#33 0x00007f00a825224b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#34 0x00007f00a8259ade in QCoreApplication::exec() () from /opt/ownCloud/qt-5.12.10/lib64/libQt5Core.so.5
#35 0x00000000004452fa in main (argc=<optimized out>, argv=0x7ffd1671f2a0)
    at /usr/src/debug/testpilotcloud-client-2.9.0-0.0.0.beta3.x86_64/src/gui/main.cpp:153
(gdb)

**Comment by TheOneRing** [comment]
Please reopen if this still occurs
