### ISSUE TITLE
[QA] SQL Coredump after write failed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8960]
Seen in testpilotcloud client 2.9.0-beta3 on Linux Mint 20.2

* connect to demo.owncloud.org using vfs
* symlink the .sync*db* files out of the sync root folder into a very small filesystem mounted with `sudo mount -t tmpfs -o size=3M tmpfs /tmp/smallsyncroot`
* add 2000 files to the server using e.g. `randfiles.py -m 2000 -b 10 2000`
* the client starts discovery of the new files, the *wal jounral starts growing. It would normally grow to ca 4MB. 
* When it hits the 3MB limit, SQLite errors are logged according to #8787 but then the client crashes

the log has:
```
8-26 20:36:55:833 [ warning sync.propagator ]:	Could not complete propagation of "2000/0CqrLd4LXNnIOGXheDOV4n9nGuo2lYUjbFdy5jRiJpqA7LYPW3qigrMmL3KJ6jOWiFj0AmvKgUrr5KknUIlkANITeLSHu3iSf7bAiq0Jimy6WIH5wnXZEyPV6GVAE44cVh0knEutqv6iI0Kom4VRyq.testpilotcloud_virtual" by OCC::PropagateIgnoreJob(0x56385b066eb0) with status OCC::SyncFileItem::BlacklistedError and error: "File name too long (skipped due to earlier error, trying again in 2 second(s))"
08-26 20:36:55:837 [ info sync.propagator ]:	Starting SyncInstruction(CSYNC_INSTRUCTION_UPDATE_METADATA) propagation of "2000/0FQ3Y9PihnCTGd386kDvYiz54Z7nDe2n4EKaUfIr94FestcFdiOS8qFu.testpilotcloud_virtual" by OCC::PropagateUpdateMetaDataJob(0x563859c85f80)
08-26 20:36:55:837 [ info sync.database ]:	Updating file record for path: "2000/0FQ3Y9PihnCTGd386kDvYiz54Z7nDe2n4EKaUfIr94FestcFdiOS8qFu.testpilotcloud_virtual" inode: 11272385 modtime: 1630002749 type: CSyncEnums::ItemTypeVirtualFile etag: "d4d0ee0b2a280f529629b911139207a5" fileId: "00001845oc4xf38z3tuj" remotePerm: "RS" fileSize: 2 checksum: ""
08-26 20:36:55:838 [ warning sync.database.sql ]:	Sqlite exec statement error: 13 "database or disk is full" in "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);"
08-26 20:36:55:838 [ warning sync.propagator ]:	Could not complete propagation of "2000/0FQ3Y9PihnCTGd386kDvYiz54Z7nDe2n4EKaUfIr94FestcFdiOS8qFu.testpilotcloud_virtual" by OCC::PropagateUpdateMetaDataJob(0x563859c85f80) with status OCC::SyncFileItem::SoftError and error: "Could not update file : database or disk is full"
08-26 20:36:55:838 [ fatal default ]:	ENFORCE: "_state != Finished" in file /drone/src/src/linux-64-gcc/testpilotcloud-2.9.0-beta3.5019/src/libsync/owncloudpropagator.cpp, line 239 virtual void OCC::PropagateItemJob::done(OCC::SyncFileItem::Status, const QString&)
```

```
$ cat < EOF > ginit
set solib-search-path /tmp/.mount_testpiTnY3GU/usr/lib
set sysroot
EOF
$ gdb /tmp/.mount_testpiTnY3GU/usr/bin/testpilotcloud core -ix ginit
Core was generated by `/tmp/.mount_testpi1LnuyY/AppRun.wrapped --logfile -'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9f6cbb7780 (LWP 409173))]
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f9f6eb2c859 in __GI_abort () at abort.c:79
#2  0x00007f9f6f0fe825 in QMessageLogger::fatal(char const*, ...) const () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#3  0x00007f9f6fc73a49 in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#4  0x00007f9f6fc71865 in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#5  0x00007f9f6fc6f21c in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#6  0x00007f9f6fc74035 in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#7  0x00007f9f6fc73d9d in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#8  0x00007f9f6fc7429f in OCC::PropagateRootDirectory::scheduleSelfOrChild() ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#9  0x00007f9f6fc6f72a in OCC::OwncloudPropagator::scheduleNextJobImpl() ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libtestpilotcloudsync.so.0
#10 0x00007f9f6f252ac4 in QSingleShotTimer::timerEvent(QTimerEvent*) () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#11 0x00007f9f6f231f8c in QObject::event(QEvent*) () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#12 0x00007f9f70904bdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Widgets.so.5.12.11
#13 0x00007f9f70908820 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Widgets.so.5.12.11
#14 0x00007f9f6f25b788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#15 0x00007f9f6f276c66 in QTimerInfoList::activateTimers() () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#16 0x00007f9f6f276d41 in idleTimerSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#17 0x00007f9f6d5d1cca in g_main_context_dispatch () from /tmp/.mount_testpiTnY3GU/usr/lib/libglib-2.0.so.0.6600.4
#18 0x00007f9f6d5d1f00 in ?? () from /tmp/.mount_testpiTnY3GU/usr/lib/libglib-2.0.so.0.6600.4
#19 0x00007f9f6d5d1f8c in g_main_context_iteration () from /tmp/.mount_testpiTnY3GU/usr/lib/libglib-2.0.so.0.6600.4
#20 0x00007f9f6f268a0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#21 0x00007f9f6f34bd5b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#22 0x00007f9f6f267390 in QCoreApplication::exec() () from /tmp/.mount_testpiTnY3GU/usr/lib/libQt5Core.so.5.12.11
#23 0x0000563858b3a94f in ?? ()
#24 0x00007f9f6eb2e0b3 in __libc_start_main (main=0x563858b3a700, argc=3, argv=0x7ffd1b516c18, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd1b516c08) at ../csu/libc-start.c:308
#25 0x0000563858b3b06a in _start ()
(gdb)

**Comment by TheOneRing** [comment]
Probably fixed by the return in https://github.com/owncloud/client/commit/0f48279d4f895602c3fdb153b79147bfd25a860f#diff-a587a981368e02e7d0efe2a0b0ef8ac5e68e248fcc46eecdcffadedd5b2f1ed2R1162
