### ISSUE TITLE
[gui][tests-only] Passing tests that are in `Scenario Outline` are also reported as failed whenever one or more tests fail.

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9222]
When the tests are in Scenario Outline, they also get reported as failed (but they actually pass) whenever some other test fails.
Example log: from https://drone.owncloud.com/owncloud/client/9689/2/14
```json
[{
"Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: Expiry Date Mismatch: [object Object]\n    at Object.assertUserLastPublicShareDetails (/drone/src/middleware/src/helpers/sharingHelper.js:431:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
"Feature": "Sharing",
"Feature File": "tst_sharing",
"Scenario": "user changes the expiration date of an already existing public link using webUI",
"Test Step": "Then the fields of the last public link share response of user \"Alice\" should include on the server"
 },
{
"Error Details": "Error details not found",
"Feature": "Sharing",
"Feature File": "tst_sharing",
"Scenario": "simple sharing of folder by public link with different roles",
"Test Step": "role=Viewer, permissions=read"
},
{
"Error Details": "Error details not found",
"Feature": "Sharing",
"Feature File": "tst_sharing",
"Scenario": "change collaborator permissions of a file & folder",
"Test Step": "permissions=edit, expected-folder-permission=read, share, expected-file-permission=read, share"
}]
```
Here, the first test is the failed scenario. But the following two scenarios are actually passing. They are reported in the error log because those tests are in `Scenario Outline`.

I separated those scenario outline tests each in a separate `scenario` and ran the CI. The following is the error report:
from https://drone.owncloud.com/owncloud/client/9690/2/14
```json
[{
"Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: Expiry Date Mismatch: [object Object]\n    at Object.assertUserLastPublicShareDetails (/drone/src/middleware/src/helpers/sharingHelper.js:431:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
"Feature": "Sharing",
"Feature File": "tst_sharing",
"Scenario": "user changes the expiration date of an already existing public link for folder using client-UI",
"Test Step": "Then the fields of the last public link share response of user \"Alice\" on the server should include"
}]
```

Might need some fixes in `TestLogParser.py` (not sure).

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/client/pull/9232
