### ISSUE TITLE
desktop client 2.9.2 crash with ocis

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9330]
Seen with testpilotcloud client 2.9.2 on linux 
* connected to ocis.ocis-traefik.latest.owncloud.works
* using placeholder vfs

Steps to reproduce:
* login as user einstein
* wait for initial sync to complete
* start nemo
* use nemo to move a file (tp-0104_1205.log below) into the sync folder root.

The client starts to sync, then crashes reproducably. BAD.

Client log snippet and core stacktrace:

```
01-04 12:45:45:074 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://ocis.ocis-traefik.latest.owncloud.works/remote.php/webdav/tp-0104_1205.log") FINISHED WITH STATUS "OK"
01-04 12:45:45:075 [ debug sync.fileitem ]	[ OCC::SyncFileItem::toSyncJournalFileRecordWithInode ]:	"/home/testy/testpilotcloud4/tp-0104_1205.log" Retrieved inode  11142606 (previous item inode:  11142606 )
01-04 12:45:45:075 [ info sync.database ]:	Updating file record for path: "tp-0104_1205.log" inode: 11142606 modtime: 1641296143 type: CSyncEnums::ItemTypeFile etag: "906460aae07fc995b55d92d8d26e1ff9" fileId: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA4ODlkMTg4LWNiYjItNDRkOC1iZWRhLTMzMzViYzA1ODNlYQ==" remotePerm: "WDNVR" fileSize: 2150069 checksum: "SHA1:2f2fc0b5e7226c1a83e0c1afb7055e7da76a3b66"
01-04 12:45:45:075 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "SHA1"
01-04 12:45:45:075 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "INSERT OR IGNORE INTO checksumtype (name) VALUES (?1)"
01-04 12:45:45:075 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-04 12:45:45:075 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "SHA1"
01-04 12:45:45:075 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT id FROM checksumtype WHERE name=?1"
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 3854113491984099096
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 2 16
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 3 "tp-0104_1205.log"
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 4 11142606
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 5 0
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 6 0
01-04 12:45:45:076 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 7 0
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 8 1641296143
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 9 CSyncEnums::ItemTypeFile
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 10 "906460aae07fc995b55d92d8d26e1ff9"
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 11 "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA4ODlkMTg4LWNiYjItNDRkOC1iZWRhLTMzMzViYzA1ODNlYQ=="
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 12 "WDNVR"
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 13 2150069
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 14 0
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 15 "2f2fc0b5e7226c1a83e0c1afb7055e7da76a3b66"
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 16 1
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);"
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "tp-0104_1205.log"
01-04 12:45:45:078 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT pinState FROM flags WHERE ((?1 == path OR (?1 > (path||'/') AND ?1 < (path||'0'))) OR path == '') AND pinState is not null AND pinState != 0 ORDER BY length(path) DESC LIMIT 1;"
01-04 12:45:45:079 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "tp-0104_1205.log"
01-04 12:45:45:079 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "DELETE FROM uploadinfo WHERE path=?1"
01-04 12:45:45:079 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-04 12:45:45:079 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "upload file start" and starting new transaction
01-04 12:45:45:080 [ info sync.propagator ]:	Completed propagation of "tp-0104_1205.log" by OCC::PropagateUploadFileTUS(0x55c1182104d0) with status OCC::SyncFileItem::Success
01-04 12:45:45:080 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "tp-0104_1205.log" OCC::SyncFileItem::Success SyncInstruction(CSYNC_INSTRUCTION_NEW)
01-04 12:45:45:080 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:/home/testy/testpilotcloud4/tp-0104_1205.log" to QLocalSocket(0x7fbc5c005dc0)
01-04 12:45:45:081 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:/home/testy/testpilotcloud4" to QLocalSocket(0x7fbc5c005dc0)
01-04 12:45:45:081 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::slotItemCompleted ]:	wiped successful item "tp-0104_1205.log"
01-04 12:45:45:081 [ critical default ]:	ASSERT: "!_done" in file /pkg/src/owncloud-client/BUILD/testpilotcloud-2.9.2.6207/src/libsync/networkjobs.cpp, line 566 OCC::PropfindJob::start()::<lambda(const QString&, const QMap<QString, QString>&)>
01-04 12:45:45:081 [ debug sync.fileitem ]	[ OCC::SyncFileItem::toSyncJournalFileRecordWithInode ]:	"/home/testy/testpilotcloud4/tp-0104_1205.log" Retrieved inode  11142606 (previous item inode:  11142606 )
01-04 12:45:45:081 [ info sync.database ]:	Updating file record for path: "tp-0104_1205.log" inode: 11142606 modtime: 1641296143 type: CSyncEnums::ItemTypeFile etag: "906460aae07fc995b55d92d8d26e1ff9" fileId: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA4ODlkMTg4LWNiYjItNDRkOC1iZWRhLTMzMzViYzA1ODNlYQ==" remotePerm: "WDNVR" fileSize: 2150069 checksum: "SHA1:2f2fc0b5e7226c1a83e0c1afb7055e7da76a3b66"
01-04 12:45:45:081 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 3854113491984099096
01-04 12:45:45:081 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 2 16
01-04 12:45:45:081 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 3 "tp-0104_1205.log"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 4 11142606
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 5 0
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 6 0
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 7 0
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 8 1641296143
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 9 CSyncEnums::ItemTypeFile
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 10 "906460aae07fc995b55d92d8d26e1ff9"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 11 "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjA4ODlkMTg4LWNiYjItNDRkOC1iZWRhLTMzMzViYzA1ODNlYQ=="
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 12 "WDNVR"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 13 2150069
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 14 0
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 15 "2f2fc0b5e7226c1a83e0c1afb7055e7da76a3b66"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 16 1
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "tp-0104_1205.log"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT pinState FROM flags WHERE ((?1 == path OR (?1 > (path||'/') AND ?1 < (path||'0'))) OR path == '') AND pinState is not null AND pinState != 0 ORDER BY length(path) DESC LIMIT 1;"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "tp-0104_1205.log"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "DELETE FROM uploadinfo WHERE path=?1"
01-04 12:45:45:082 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-04 12:45:45:082 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "upload file start" and starting new transaction
01-04 12:45:45:083 [ fatal default ]:	ENFORCE: "_state != Finished" in file /pkg/src/owncloud-client/BUILD/testpilotcloud-2.9.2.6207/src/libsync/owncloudpropagator.cpp, line 239 virtual void OCC::PropagateItemJob::done(OCC::SyncFileItem::Status, const QString&)
Aborted (core dumped)
⏚ 2& [testy:~] 1m35s 134 $ ll coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4 
-rw-r-----+ 1 root root 7173665 Jan  4 12:45 coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4
⏚ 2& [testy:~] $ unlz coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4 
unlz4   unlzma  
⏚ 2& [testy:~] $ unlz coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4 
unlz4   unlzma  
⏚ 2& [testy:~] $ unlz4 coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4 
Decoding file coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000 
coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000: Permission denied
⏚ 2& [testy:~] 1 $ sudo unlz4 coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4 
Decoding file coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000 
coredump/core.testpi : decoded 167907328 bytes                                 
⏚ 2& [testy:~] $ which testp
testparm                                testpilotcloud/                         testpilotcloud-2.9.0-rc2.5135.AppImage  testpilotcloudcmd                       testpilot-debug.sh
⏚ 2& [testy:~] $ which testpilotcloud
/usr/bin/testpilotcloud
⏚ 2& [testy:~] $ gdb /usr/bin/testpilotcloud coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000
core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000      core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4
⏚ 2& [testy:~] $ gdb /usr/bin/testpilotcloud coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000
core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000      core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000.lz4
⏚ 2& [testy:~] $ gdb /usr/bin/testpilotcloud coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/testpilotcloud...
(No debugging symbols found in /usr/bin/testpilotcloud)
/home/testy/coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000: Permission denied.
(gdb) where
No stack.
(gdb) quit
⏚ 2& [testy:~] 9s $ sudo chmod a+rx coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000
⏚ 2& [testy:~] $ gdb /usr/bin/testpilotcloud coredump/core.testpilotcloud.1000.31c7f3e6af7148ffb56bddbb877695bf.2356278.1641296745000000000000
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/testpilotcloud...
(No debugging symbols found in /usr/bin/testpilotcloud)
[New LWP 2356278]
[New LWP 2356282]
[New LWP 2356279]
[New LWP 2356291]
[New LWP 2356280]
[New LWP 2356293]
[New LWP 2356300]
[New LWP 2356307]
[New LWP 2356354]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `testpilotcloud --showsettings --logdebug --logfile -'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fbc64a45800 (LWP 2356278))]
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fbc675f1859 in __GI_abort () at abort.c:79
#2  0x00007fbc67b9e2dd in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fbc6838fb9c in  () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#4  0x00007fbc6840f39f in  () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#5  0x00007fbc6840fc89 in  () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#6  0x00007fbc67dd8fb8 in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fbc68392d56 in OCC::PropfindJob::result(QMap<QString, QString> const&) () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#8  0x00007fbc683e07eb in  () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#9  0x00007fbc67dd8fb8 in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fbc68392c7e in OCC::LsColJob::directoryListingIterated(QString const&, QMap<QString, QString> const&) () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#11 0x00007fbc67dd8fb8 in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fbc68392b4e in OCC::LsColXMLParser::directoryListingIterated(QString const&, QMap<QString, QString> const&) () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#13 0x00007fbc683e62ce in OCC::LsColXMLParser::parse(QByteArray const&, QHash<QString, long long>*, QString const&) () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#14 0x00007fbc683e722a in OCC::LsColJob::finished() () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#15 0x00007fbc683deb0f in OCC::AbstractNetworkJob::slotFinished() () at /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
#16 0x00007fbc67dd8fb8 in QMetaObject::activate(QObject*, int, int, void**) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fbc68251bcc in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Network.so.5
#18 0x00007fbc682f8b2e in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Network.so.5
#19 0x00007fbc67dd98ba in QObject::event(QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fbc68b76e06 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fbc68b80300 in QApplication::notify(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fbc67dad46a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fbc67db00e8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fbc67e05b37 in  () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007fbc66ec217d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fbc66ec2400 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007fbc66ec24a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fbc67e05135 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007fbc67dac00b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007fbc67db3d76 in QCoreApplication::exec() () at /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x000055c1157039cc in  ()
#32 0x00007fbc675f30b3 in __libc_start_main (main=0x55c1157037c0, argc=5, argv=0x7fffd3acc468, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffd3acc458)
    at ../csu/libc-start.c:308
#33 0x000055c11570412e in _start ()
(gdb) up
#1  0x00007fbc675f1859 in __GI_abort () at abort.c:79
79	abort.c: No such file or directory.
(gdb) up
#2  0x00007fbc67b9e2dd in QMessageLogger::fatal(char const*, ...) const () from /opt/ownCloud/qt-5.12.10/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#3  0x00007fbc6838fb9c in ?? () from /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
(gdb) up
#4  0x00007fbc6840f39f in ?? () from /opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu/libtestpilotcloudsync.so.0
(gdb)

**Comment by jnweiger** [comment]
Coredump is also reproduced
* without using placeholder vfs
* by moving an empty folder into the sync root.

**Comment by TheOneRing** [comment]
This looks like an issue with ocis.
We performed a PROPFIND with a depths of 0 and receive multiple entries (cc: @butonic ). 
Please provide a log with httplogs enabled.

**Comment by jnweiger** [comment]
Not reproducable:
* when the server folder is completely empty, the first upload thorugh the client trigered the 
Remove everything popup a few times.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/9324#issuecomment-1005541348

The log of shows a 500 error.
I need http logs.
