### ISSUE TITLE
[tests-only][GUI] Public link sharing test failed nightly in 2.10 branch

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9392]
GUI test scenario `sharing of a file by public link with password and changing the password` failed nightly on 2.10 branch

https://drone.owncloud.com/owncloud/client/10467/3/14
```
[
    {
        "Error Details": "Exception: Step execution through test middleware failed. Error: Error: HTTP Request Failed: Could not download public share., Status: 401 undefined\n    at Object.checkStatus (/drone/src/middleware/src/helpers/httpHelper.js:44:11)\n    at Object.downloadLastPublicLinkResource (/drone/src/middleware/src/helpers/sharingHelper.js:511:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
        "Feature": "Sharing",
        "Feature File": "tst_sharing",
        "Scenario": "sharing of a file by public link with password and changing the password",
        "Test Step": "And the public should be able to download the file \"textfile0.txt\" with password \"password1234\" from the last created public link by \"Alice\" on the server"
    }
]
```

**Comment by saw-jan** [comment]
Can be reproduced locally by running the test multiple times.
Everything is working fine except when downloading the link there is sometimes `401 unauthorized` response which fails the test.

- `PUT` to create file - **OK**
- `POST` to create public link share with pwd - **OK**
- `PUT` to update created public link pwd - **OK**
- `GET` to download the public link shared file - **OK** (most of the time)
And sometimes returns `401 unauthorized` but passes everytime if implemented request retry for `401` case in test-middleware

Hardly intermittent. And nothing needs to be done in the client test code.
If this fails more frequently, we can then try fixing it in the test-middleware.

Closing this for now. We can revisit if it comes again
