### ISSUE TITLE
[tests-only][GUI] Scenario `Verify that you can create a subfolder with long name` failed nightly on master branch

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9393]
GUI test scenario `Verify that you can create a subfolder with long name` failed nightly on 2.10 branch

https://drone.owncloud.com/owncloud/client/10466/3/14
```
[
    {
        "Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: File should have content \"test content\", but found \"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n  <s:message>File with name Folder1/really long folder name with some spaces and special char such as $%\u00f1&amp;/test.txt could not be located</s:message>\n</d:error>\n\"\n    at fileShouldHaveContent (/drone/src/middleware/src/stepDefinitions/webdavContext.js:36:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
        "Feature": "Syncing files",
        "Feature File": "tst_syncing",
        "Scenario": "Verify that you can create a subfolder with long name",
        "Test Step": "And as \"Alice\" the file \"Folder1/really long folder name with some spaces and special char such as $%\u00f1&/test.txt\" on the server should have the content \"test content\""
    }
]
```

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/9109 could help as we could better track the creation of the file on the server.

**Comment by TheOneRing** [comment]
```02:39:05:426 AUT stdout: 01-27 02:39:05:352 [ warning sync.propagator ]:	Could not complete propagation of "Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt" by OCC::PropagateUploadFileV1(0x5619549fef00) with status OCC::SyncFileItem::Message and error: "Local file changed during sync. It will be resumed."

**Comment by Talank** [comment]
This test failed in 2.10 as well https://drone.owncloud.com/owncloud/client/10589/3/14

**Comment by Talank** [comment]
Failed again. 2 days in a row. https://drone.owncloud.com/owncloud/client/10595/3/14

**Comment by saw-jan** [comment]
Sometimes file `Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt` will not get synced to the server causing the test to fail.

**Comment by saw-jan** [comment]
Haven't seen this test failing. Closing this here.
