### ISSUE TITLE
[QA] 3.0.0 master crashes in ASSERT: "hasCapabilities()"

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9780]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When starting the client compiled from git a core dump is written, the logfile shows

```
6-08 11:13:11:222 [ fatal default ]:   ASSERT: "hasCapabilities()" in file /home/gabriele/development/owncloud/client/src/libsync/account.cpp, line 282
```

### Expected behavior

Client starts

### Steps to reproduce the issue

1. `git pull` on client master
2. cmake (here with theme btrtesting)
3. make
4. run the client

### Logs

[BtR-start.log.gz](https://github.com/owncloud/client/files/8860307/BtR-start.log.gz)

### Client version number

client 3.0.0 git master from 08. June 2022

### Desktop environment (Linux only)

openSUSE 15.3

**Comment by fmoc** [comment]
Please retry on a clean system (read: no old config files, but please make a backup!), I start to believe this is a migration issue.

**Comment by gabi18** [comment]
```
#0  0x00007ffff3fe3cdb in raise () from /lib64/libc.so.6
#1  0x00007ffff3fe5375 in abort () from /lib64/libc.so.6
#2  0x00007ffff4d9cc2f in QMessageLogger::fatal(char const*, ...) const () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#3  0x00007ffff4d9c551 in qt_assert(char const*, char const*, int) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#4  0x00007ffff67eeaae in OCC::Account::capabilities (this=0xd63950)
    at /home/gabriele/development/owncloud/client/src/libsync/account.cpp:282
#5  0x000000000057fe35 in OCC::ServerNotificationHandler::slotFetchNotifications (this=0xe8a380, ptr=...)
    at /home/gabriele/development/owncloud/client/src/gui/servernotificationhandler.cpp:43
#6  0x0000000000565f8b in OCC::ActivityWidget::slotRefreshNotifications (this=0xf73150, ptr=...)
    at /home/gabriele/development/owncloud/client/src/gui/activitywidget.cpp:142
#7  0x0000000000568ecf in OCC::ActivitySettings::slotRefresh (this=0xe8bf00, ptr=...)
    at /home/gabriele/development/owncloud/client/src/gui/activitywidget.cpp:572
#8  0x00000000004a7d44 in OCC::SettingsDialog::slotRefreshActivity (this=0xfa0f40, accountState=...)
    at /home/gabriele/development/owncloud/client/src/gui/settingsdialog.cpp:482
#9  0x00000000004a7cbb in OCC::SettingsDialog::slotRefreshActivityAccountStateSender (this=0xfa0f40)
    at /home/gabriele/development/owncloud/client/src/gui/settingsdialog.cpp:476
#10 0x00000000004abf99 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (OCC::SettingsDialog::*)()>::call(void (OCC::SettingsDialog::*)(), OCC::SettingsDialog*, void**) (
    f=(void (OCC::SettingsDialog::*)(OCC::SettingsDialog * const)) 0x4a7c54 <OCC::SettingsDialog::slotRefreshActivityAccountStateSender()>, o=0xfa0f40, arg=0x7fffffffc9c0) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:152
#11 0x00000000004abc11 in QtPrivate::FunctionPointer<void (OCC::SettingsDialog::*)()>::call<QtPrivate::List<>, void>(void (OCC::SettingsDialog::*)(), OCC::SettingsDialog*, void**) (
    f=(void (OCC::SettingsDialog::*)(OCC::SettingsDialog * const)) 0x4a7c54 <OCC::SettingsDialog::slotRefreshActivityAccountStateSender()>, o=0xfa0f40, arg=0x7fffffffc9c0) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:185
#12 0x00000000004ab776 in QtPrivate::QSlotObject<void (OCC::SettingsDialog::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0xea00b0, r=0xfa0f40, a=0x7fffffffc9c0, ret=0x0)
    at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:418
#13 0x00007ffff4fefa84 in void doActivate<false>(QObject*, int, void**) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#14 0x0000000000501dcb in OCC::AccountState::isConnectedChanged (this=0xd851f0)
    at /home/gabriele/development/owncloud/client/client-build/src/gui/owncloudCore_autogen/EWIEGA46WW/moc_accountstate.cpp:268
#15 0x00000000004d377d in OCC::AccountState::setState (this=0xd851f0, state=OCC::AccountState::Connected)
    at /home/gabriele/development/owncloud/client/src/gui/accountstate.cpp:181
#16 0x00000000004d4e99 in OCC::AccountState::slotConnectionValidatorResult (this=0xd851f0, 
    status=OCC::ConnectionValidator::Connected, errors=...)
    at /home/gabriele/development/owncloud/client/src/gui/accountstate.cpp:391
#17 0x00000000004d9a9f in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<OCC::ConnectionValidator::Status, QStringList const&>, void, void (OCC::AccountState::*)(OCC::ConnectionValidator::Status, QStringList const&)>::call (f=
    (void (OCC::AccountState::*)(OCC::AccountState * const, OCC::ConnectionValidator::Status, const QStringList &)) 0x4d495c <O--Type <RET> for more, q to quit, c to continue without paging--
CC::AccountState::slotConnectionValidatorResult(OCC::ConnectionValidator::Status, QStringList const&)>, o=0xd851f0, 
    arg=0x7fffffffcd20) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:152
#18 0x00000000004d9302 in QtPrivate::FunctionPointer<void (OCC::AccountState::*)(OCC::ConnectionValidator::Status, QStringList const&)>::call<QtPrivate::List<OCC::ConnectionValidator::Status, QStringList const&>, void> (f=
    (void (OCC::AccountState::*)(OCC::AccountState * const, OCC::ConnectionValidator::Status, const QStringList &)) 0x4d495c <OCC::AccountState::slotConnectionValidatorResult(OCC::ConnectionValidator::Status, QStringList const&)>, o=0xd851f0, 
    arg=0x7fffffffcd20) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:185
#19 0x00000000004d8d1e in QtPrivate::QSlotObject<void (OCC::AccountState::*)(OCC::ConnectionValidator::Status, QStringList const&), QtPrivate::List<OCC::ConnectionValidator::Status, QStringList const&>, void>::impl (which=1, this_=0xe9dd30, r=0xd851f0, 
    a=0x7fffffffcd20, ret=0x0) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:418
#20 0x00007ffff4fefa84 in void doActivate<false>(QObject*, int, void**) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#21 0x00000000005037fb in OCC::ConnectionValidator::connectionResult (this=0xf8e0d0, _t1=OCC::ConnectionValidator::Connected, 
    _t2=...)
    at /home/gabriele/development/owncloud/client/client-build/src/gui/owncloudCore_autogen/EWIEGA46WW/moc_connectionvalidator.cpp:254
#22 0x000000000052d86e in OCC::ConnectionValidator::reportResult (this=0xf8e0d0, status=OCC::ConnectionValidator::Connected)
    at /home/gabriele/development/owncloud/client/src/gui/connectionvalidator.cpp:333
#23 0x000000000052c1ce in OCC::ConnectionValidator::slotStatusFound (this=0xf8e0d0, url=..., info=...)
    at /home/gabriele/development/owncloud/client/src/gui/connectionvalidator.cpp:184
#24 0x000000000052b8cf in OCC::ConnectionValidator::<lambda()>::operator()(void) const (__closure=0xf7ac20)
    at /home/gabriele/development/owncloud/client/src/gui/connectionvalidator.cpp:123
#25 0x000000000052e10c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::ConnectionValidator::slotCheckServerAndAuth()::<lambda()> >::call(OCC::ConnectionValidator::<lambda()> &, void **) (f=..., arg=0x7fffffffcfd0)
    at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:146
#26 0x000000000052e016 in QtPrivate::Functor<OCC::ConnectionValidator::slotCheckServerAndAuth()::<lambda()>, 0>::call<QtPrivate::List<>, void>(OCC::ConnectionValidator::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffcfd0)
    at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:256
#27 0x000000000052dea2 in QtPrivate::QFunctorSlotObject<OCC::ConnectionValidator::slotCheckServerAndAuth()::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0xf7ac10, 
    r=0xf8e0d0, a=0x7fffffffcfd0, ret=0x0) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:443
#28 0x00007ffff4fefa84 in void doActivate<false>(QObject*, int, void**) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#29 0x00007ffff67d8db1 in OCC::CoreJob::finished (this=0x7fffdc016260)
    at /home/gabriele/development/owncloud/client/client-build/src/libsync/libsync_autogen/EWIEGA46WW/moc_abstractcorejob.cpp:155
#30 0x00007ffff68c0427 in OCC::CoreJob::setResult (this=0x7fffdc016260, result=...)
    at /home/gabriele/development/owncloud/client/src/libsync/abstractcorejob.cpp:72
#31 0x00007ffff68c0367 in OCC::AbstractCoreJobFactory::setJobResult (job=0x7fffdc016260, result=...)
    at /home/gabriele/development/owncloud/client/src/libsync/abstractcorejob.cpp:37
#32 0x00007ffff68be4e0 in OCC::CheckServerJobFactory::<lambda()>::operator()(void) const (__closure=0xf88760)
    at /home/gabriele/development/owncloud/client/src/libsync/networkjobs/checkserverjobfactory.cpp:130
#33 0x00007ffff68bee2c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::CheckServerJobFactory::startJob(const QUrl&)::<lambda()> >::call(OCC::CheckServerJobFactory::<lambda()> &, void **) (f=..., arg=0x7fffffffd2a0)
    at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:146
#34 0x00007ffff68beda6 in QtPrivate::Functor<OCC::CheckServerJobFactory::startJob(const QUrl&)::<lambda()>, 0>::call<QtPrivate::List<>, void>(OCC::CheckServerJobFactory::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffd2a0)
    at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:256
#35 0x00007ffff68bed4a in QtPrivate::QFunctorSlotObject<OCC::CheckServerJobFactory::startJob(const QUrl&)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0xf88750, 
    r=0x7fffdc016260, a=0x7fffffffd2a0, ret=0x0) at /opt/ownCloud/qt-5.15.2/include/qt5/QtCore/qobjectdefs_impl.h:443
#36 0x00007ffff4fefa84 in void doActivate<false>(QObject*, int, void**) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#37 0x00007ffff5a7d717 in QNetworkReplyHttpImplPrivate::finished() () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Network.so.5
#38 0x00007ffff5b0fde9 in QNetworkReplyHttpImpl::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Network.so.5
#39 0x00007ffff4fe68d3 in QObject::event(QEvent*) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#40 0x00007ffff74a8e4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Widgets.so.5
#41 0x00007ffff74af78f in QApplication::notify(QObject*, QEvent*) () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Widgets.so.5
#42 0x00007ffff4fb44e3 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#43 0x00007ffff4fb7691 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#44 0x00007ffff5013ec3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#45 0x00007ffff2bdb624 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#46 0x00007ffff2bdb9c0 in ?? () from /usr/lib64/libglib-2.0.so.0
#47 0x00007ffff2bdba4c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#48 0x00007ffff50135bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#49 0x00007ffff4fb2e9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#50 0x00007ffff4fbbfc3 in QCoreApplication::exec() () from /opt/ownCloud/qt-5.15.2/lib64/libQt5Core.so.5
#51 0x0000000000455e3e in main (argc=1, argv=0x7fffffffdba8)
    at /home/gabriele/development/owncloud/client/src/gui/main.cpp:126
```

**Comment by gabi18** [comment]
2.10.1 config file causing the core dump:
[btr-2-10-1.cfg.gz](https://github.com/owncloud/client/files/8938687/btr-2-10-1.cfg.gz)

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/9972
